from structure.lib.cross.errors.DiagnosticEntry import DiagnosticEntry
from structure.lib.cross.errors.DiagnosticRegistry import DiagnosticRegistry

diagnostic_registry = DiagnosticRegistry(
    [
        DiagnosticEntry(
            code="CONF-E0101",
            severity="error",
            title="Unknown configuration key",
            owner="configuration",
            status="active",
            docs="docs/Diagnostics.md#conf-e0101",
            introduced="1.0.0",
            problem_template="Configuration contains a key Structure does not recognize.",
            use_template="Remove the key or correct its spelling.",
        ),
        DiagnosticEntry(
            code="CONF-E0102",
            severity="error",
            title="Invalid configuration value",
            owner="configuration",
            status="active",
            docs="docs/Diagnostics.md#conf-e0102",
            introduced="1.0.0",
            problem_template="Configuration contains a known key with an invalid value.",
            use_template="Set the value to one of the allowed values.",
        ),
        DiagnosticEntry(
            code="DSL-E0401",
            severity="error",
            title="Unsupported symbolic expression",
            owner="dsl",
            status="active",
            docs="docs/Diagnostics.md#dsl-e0401",
            introduced="1.0.0",
            problem_template="Transform code uses Python behavior Structure cannot lower to Spark expressions.",
            use_template="Use Structure DSL helpers, an @expr_fn helper, or an explicit hook.",
        ),
        DiagnosticEntry(
            code="DSL-E0402",
            severity="error",
            title="Invalid transform structure",
            owner="dsl",
            status="active",
            docs="docs/Diagnostics.md#dsl-e0402",
            introduced="1.0.0",
            problem_template="Transform source does not match the Structure compiler contract.",
            use_template="Check transform decoration, method annotations, schema flow, and assigned output fields.",
        ),
        DiagnosticEntry(
            code="SCHEMA-E0301",
            severity="error",
            title="Nullable expression assigned to non-nullable field",
            owner="schema",
            status="active",
            docs="docs/Diagnostics.md#schema-e0301",
            introduced="1.0.0",
            problem_template="An output assignment may produce null for a non-nullable field.",
            use_template="Guard the value with where(value.is_not_null()) or provide a non-null default.",
        ),
        DiagnosticEntry(
            code="SCHEMA-E0302",
            severity="error",
            title="Explicit conversion required",
            owner="schema",
            status="active",
            docs="docs/Diagnostics.md#schema-e0302",
            introduced="1.0.0",
            problem_template="An output assignment requires semantic parsing or conversion that must be explicit.",
            use_template="Use a Structure conversion helper such as to_decimal(...).",
        ),
        DiagnosticEntry(
            code="SCHEMA-E0303",
            severity="error",
            title="Incompatible output field type",
            owner="schema",
            status="active",
            docs="docs/Diagnostics.md#schema-e0303",
            introduced="1.0.0",
            problem_template="An output assignment type is not compatible with the target field type.",
            use_template="Use a compatible expression type or an explicit conversion helper.",
        ),
        DiagnosticEntry(
            code="JOIN-E0601",
            severity="error",
            title="Unsupported join condition",
            owner="join",
            status="active",
            docs="docs/Diagnostics.md#join-e0601",
            introduced="1.0.0",
            problem_template="A join_one(...) condition does not match the v1 equality-key contract.",
            use_template="Use equality key pairs combined with &, or move custom join logic into a hook.",
        ),
        DiagnosticEntry(
            code="JOIN-W0601",
            severity="warning",
            title="join_one uniqueness is not proven",
            owner="join",
            status="active",
            docs="docs/Diagnostics.md#join-w0601",
            introduced="1.0.0",
            problem_template="Structure cannot prove the right-side join key is unique.",
            use_template="Mark the joined key as primary_key=True, declare uniqueness metadata, or use join_many when appropriate.",
        ),
        DiagnosticEntry(
            code="BACKEND-E2401",
            severity="error",
            title="Unsupported backend target",
            owner="backend",
            status="active",
            docs="docs/Diagnostics.md#backend-e2401",
            introduced="1.0.0",
            problem_template="Structure has no capability profile for the configured backend.",
            use_template='Set target_backend = "pyspark" for v1.',
        ),
        DiagnosticEntry(
            code="BACKEND-E2402",
            severity="error",
            title="Unsupported backend capability",
            owner="backend",
            status="active",
            docs="docs/Diagnostics.md#backend-e2402",
            introduced="1.0.0",
            problem_template="The configured backend cannot lower the requested Structure feature.",
            use_template="Choose a supported operation, use a hook, or wait until the feature is promoted.",
        ),
        DiagnosticEntry(
            code="GEN-E0901",
            severity="error",
            title="Generated output is stale",
            owner="generation",
            status="active",
            docs="docs/Diagnostics.md#gen-e0901",
            introduced="1.0.0",
            problem_template="Generated files differ from current source and configuration.",
            use_template="Run `structure compile`, review the generated diff, and commit the generated changes.",
        ),
        DiagnosticEntry(
            code="GEN-E0902",
            severity="error",
            title="Generated transform is not importable",
            owner="generation",
            status="active",
            docs="docs/Diagnostics.md#gen-e0902",
            introduced="1.0.0",
            problem_template="Structure could not import the generated PySpark class for this transform.",
            use_template=(
                "Run `structure compile`, ensure the generated source root is importable, "
                'or set execution_mode = "online".'
            ),
        ),
        DiagnosticEntry(
            code="ONLINE-E1201",
            severity="error",
            title="Transform input is missing",
            owner="runtime",
            status="active",
            docs="docs/Diagnostics.md#online-e1201",
            introduced="1.0.0",
            problem_template="A transform invocation is missing one or more declared inputs.",
            use_template="Pass every declared input DataFrame before calling run(session).",
        ),
        DiagnosticEntry(
            code="ONLINE-E1202",
            severity="error",
            title="Online PySpark runner is not configured",
            owner="runtime",
            status="active",
            docs="docs/Diagnostics.md#online-e1202",
            introduced="1.0.0",
            problem_template="The session has no live PySpark executor.",
            use_template='Pass an online_executor to StructureSession or use execution_mode = "generated".',
        ),
        DiagnosticEntry(
            code="ONLINE-E1203",
            severity="error",
            title="Execution mode is unsupported",
            owner="runtime",
            status="active",
            docs="docs/Diagnostics.md#online-e1203",
            introduced="1.0.0",
            problem_template="The session execution mode is not supported.",
            use_template='Use execution_mode = "online" or execution_mode = "generated".',
        ),
        DiagnosticEntry(
            code="CLI-X1101",
            severity="internal",
            title="Unexpected internal failure",
            owner="cli",
            status="active",
            docs="docs/Diagnostics.md#cli-x1101",
            introduced="1.0.0",
            problem_template="Structure hit an unclassified internal failure while running a CLI command.",
            use_template="Rerun with the same command and report the diagnostic code with a concise reproduction.",
        ),
        DiagnosticEntry(
            code="STREAM-E0801",
            severity="error",
            title="Transform is not streaming-compatible",
            owner="streaming",
            status="active",
            docs="docs/Diagnostics.md#stream-e0801",
            introduced="1.0.0",
            problem_template="The transform contains an operation that is batch-only in v1 streaming compatibility.",
            use_template="Keep the transform batch-only or rewrite the operation using v1 streaming-compatible shapes.",
        ),
        DiagnosticEntry(
            code="STREAM-W0801",
            severity="warning",
            title="Hook streaming compatibility is unknown",
            owner="streaming",
            status="active",
            docs="docs/Diagnostics.md#stream-w0801",
            introduced="1.0.0",
            problem_template="A hook contains arbitrary PySpark code Structure cannot prove streaming-compatible.",
            use_template="Mark the hook streaming_safe=True only after verifying it satisfies the streaming contract.",
        ),
    ]
)
