from structure.lib.cross.errors.DiagnosticEntry import DiagnosticEntry
from structure.lib.cross.errors.DiagnosticRegistry import DiagnosticRegistry

diagnostic_registry = DiagnosticRegistry(
    [
        DiagnosticEntry(
            code="CONF-E0101",
            severity="error",
            title="Unknown configuration key",
            owner="configuration",
            status="active",
            docs="docs/Diagnostics.md#conf-e0101",
            introduced="1.0.0",
            problem_template="Configuration contains a key Structure does not recognize.",
            use_template="Remove the key or correct its spelling.",
        ),
        DiagnosticEntry(
            code="CONF-E0102",
            severity="error",
            title="Invalid configuration value",
            owner="configuration",
            status="active",
            docs="docs/Diagnostics.md#conf-e0102",
            introduced="1.0.0",
            problem_template="Configuration contains a known key with an invalid value.",
            use_template="Set the value to one of the allowed values.",
        ),
        DiagnosticEntry(
            code="DSL-E0401",
            severity="error",
            title="Unsupported symbolic expression",
            owner="dsl",
            status="active",
            docs="docs/Diagnostics.md#dsl-e0401",
            introduced="1.0.0",
            problem_template="Transform code uses Python behavior Structure cannot lower to Spark expressions.",
            use_template='Use Structure DSL helpers, @special(type="expr"), @special(type="udf"), or an explicit hook.',
        ),
        DiagnosticEntry(
            code="DSL-E0402",
            severity="error",
            title="Invalid transform structure",
            owner="dsl",
            status="active",
            docs="docs/Diagnostics.md#dsl-e0402",
            introduced="1.0.0",
            problem_template="Transform source does not match the Structure compiler contract.",
            use_template="Check transform decoration, method annotations, schema flow, and assigned output fields.",
        ),
        DiagnosticEntry(
            code="DSL-W0403",
            severity="warning",
            title="Python UDF is optimizer-opaque",
            owner="dsl",
            status="active",
            docs="docs/Diagnostics.md#dsl-w0403",
            introduced="1.0.0",
            problem_template="Transform code uses a Python UDF that Spark cannot inspect or optimize.",
            use_template='Keep the UDF only when Python execution is intentional, or set @transform(warn_on_udfs=False).',
        ),
        DiagnosticEntry(
            code="SCHEMA-E0301",
            severity="error",
            title="Nullable expression assigned to non-nullable field",
            owner="schema",
            status="active",
            docs="docs/Diagnostics.md#schema-e0301",
            introduced="1.0.0",
            problem_template="An output assignment may produce null for a non-nullable field.",
            use_template="Guard the value with where(value.is_not_null()) or provide a non-null default.",
        ),
        DiagnosticEntry(
            code="SCHEMA-E0302",
            severity="error",
            title="Explicit conversion required",
            owner="schema",
            status="active",
            docs="docs/Diagnostics.md#schema-e0302",
            introduced="1.0.0",
            problem_template="An output assignment requires semantic parsing or conversion that must be explicit.",
            use_template="Use a Structure conversion helper such as to_decimal(...).",
        ),
        DiagnosticEntry(
            code="SCHEMA-E0303",
            severity="error",
            title="Incompatible output field type",
            owner="schema",
            status="active",
            docs="docs/Diagnostics.md#schema-e0303",
            introduced="1.0.0",
            problem_template="An output assignment type is not compatible with the target field type.",
            use_template="Use a compatible expression type or an explicit conversion helper.",
        ),
        DiagnosticEntry(
            code="JOIN-E0601",
            severity="error",
            title="Unsupported join condition",
            owner="join",
            status="active",
            docs="docs/Diagnostics.md#join-e0601",
            introduced="1.0.0",
            problem_template="A lookup_join(...) condition does not match the equality-key contract.",
            use_template="Use equality key pairs combined with &, or move custom join logic into a hook.",
        ),
        DiagnosticEntry(
            code="JOIN-W0601",
            severity="warning",
            title="lookup_join uniqueness is not proven",
            owner="join",
            status="active",
            docs="docs/Diagnostics.md#join-w0601",
            introduced="1.0.0",
            problem_template="Structure cannot prove the right-side join key is unique.",
            use_template="Use JoinDedupe.latest_by(...) or JoinDedupe.earliest_by(...), or use left_join/inner_join when multiplication is intended.",
        ),
        DiagnosticEntry(
            code="REL-E0701",
            severity="error",
            title="Relation cardinality assertion failed",
            owner="relation",
            status="active",
            docs="docs/Diagnostics.md#rel-e0701",
            introduced="1.0.0",
            problem_template="An exactly_one(...) relation assertion found zero or multiple rows.",
            use_template="Filter or aggregate the relation before asserting exactly_one(...), or remove the assertion if multiple rows are valid.",
        ),
        DiagnosticEntry(
            code="REL-E0702",
            severity="error",
            title="Relation uniqueness assertion failed",
            owner="relation",
            status="active",
            docs="docs/Diagnostics.md#rel-e0702",
            introduced="1.0.0",
            problem_template="A require_unique(...) relation assertion found duplicate keys.",
            use_template="Deduplicate, aggregate, or correct the source relation before asserting require_unique(...).",
        ),
        DiagnosticEntry(
            code="REL-E0703",
            severity="error",
            title="Relation predicate assertion failed",
            owner="relation",
            status="active",
            docs="docs/Diagnostics.md#rel-e0703",
            introduced="1.0.0",
            problem_template="A require_all(...) relation assertion found rows that do not satisfy the predicate.",
            use_template="Filter or correct invalid rows before asserting require_all(...), or loosen the predicate if those rows are valid.",
        ),
        DiagnosticEntry(
            code="REL-E0704",
            severity="error",
            title="Relation reference assertion failed",
            owner="relation",
            status="active",
            docs="docs/Diagnostics.md#rel-e0704",
            introduced="1.0.0",
            problem_template="A require_reference(...) relation assertion found values without a reference row.",
            use_template="Correct the referenced catalog, allow nulls only when they are valid, or filter invalid rows before asserting require_reference(...).",
        ),
        DiagnosticEntry(
            code="REL-E0705",
            severity="error",
            title="Relation priority selection failed",
            owner="relation",
            status="active",
            docs="docs/Diagnostics.md#rel-e0705",
            introduced="1.0.0",
            problem_template="A select_first_qualified(...) relation selection found a missing or tied candidate.",
            use_template="Correct the eligibility predicate, add a deterministic priority tie-breaker, or allow missing candidates when absence is valid.",
        ),
        DiagnosticEntry(
            code="REL-E0706",
            severity="error",
            title="Relation parent hierarchy assertion failed",
            owner="relation",
            status="active",
            docs="docs/Diagnostics.md#rel-e0706",
            introduced="1.0.0",
            problem_template="A require_parent_hierarchy(...) relation assertion found an invalid parent hierarchy.",
            use_template="Correct missing parents, cycles, depth overruns, or child ordering before asserting the hierarchy.",
        ),
        DiagnosticEntry(
            code="BACKEND-E2401",
            severity="error",
            title="Unsupported backend target",
            owner="backend",
            status="active",
            docs="docs/Diagnostics.md#backend-e2401",
            introduced="1.0.0",
            problem_template="Structure has no capability profile for the configured backend.",
            use_template='Set plugin.default = "pyspark" for v1.',
        ),
        DiagnosticEntry(
            code="BACKEND-E2402",
            severity="error",
            title="Unsupported backend capability",
            owner="backend",
            status="active",
            docs="docs/Diagnostics.md#backend-e2402",
            introduced="1.0.0",
            problem_template="The configured backend cannot lower the requested Structure feature.",
            use_template="Choose a supported operation, use a hook, or wait until the feature is promoted.",
        ),
        DiagnosticEntry(
            code="CONNECT-E2601",
            severity="error",
            title="Spark Connect boundary is unsupported",
            owner="backend",
            status="active",
            docs="docs/Diagnostics.md#connect-e2601",
            introduced="1.0.0",
            problem_template="Runtime code touched a Spark API boundary that Spark Connect cannot expose.",
            use_template=(
                "Use Spark Connect DataFrame APIs or set [tool.structure.plugin.pyspark] variant = \"ordinary\"."
            ),
        ),
        DiagnosticEntry(
            code="GEN-E0901",
            severity="error",
            title="Generated output is stale",
            owner="generation",
            status="active",
            docs="docs/Diagnostics.md#gen-e0901",
            introduced="1.0.0",
            problem_template="Generated files differ from current source and configuration.",
            use_template="Run `structure compile`, review the generated diff, and commit the generated changes.",
        ),
        DiagnosticEntry(
            code="GEN-E0902",
            severity="error",
            title="Generated transform is not importable",
            owner="generation",
            status="active",
            docs="docs/Diagnostics.md#gen-e0902",
            introduced="1.0.0",
            problem_template="Structure could not import the generated PySpark class for this transform.",
            use_template=(
                "Run `structure compile`, ensure the generated source root is importable, "
                'or switch to direct execution with execution_mode = "online".'
            ),
        ),
        DiagnosticEntry(
            code="GEN-E0903",
            severity="error",
            title="Embedded hook cannot be generated",
            owner="generation",
            status="active",
            docs="docs/Diagnostics.md#gen-e0903",
            introduced="1.0.0",
            problem_template="A raw hook depends on source state that generated PySpark does not package.",
            use_template="Use local imports and a standalone hook body, or remove embed_hooks.",
        ),
        DiagnosticEntry(
            code="ONLINE-E1201",
            severity="error",
            title="Transform input is missing",
            owner="runtime",
            status="active",
            docs="docs/Diagnostics.md#online-e1201",
            introduced="1.0.0",
            problem_template="A transform invocation is missing one or more declared inputs.",
            use_template="Pass every declared input DataFrame before calling run(session).",
        ),
        DiagnosticEntry(
            code="ONLINE-E1202",
            severity="error",
            title="Direct PySpark runner is not configured",
            owner="runtime",
            status="active",
            docs="docs/Diagnostics.md#online-e1202",
            introduced="1.0.0",
            problem_template="The session has no live PySpark executor.",
            use_template=(
                'Pass a SparkSession or custom online_executor to StructureSession, or switch to generated-code '
                'execution with execution_mode = "generated".'
            ),
        ),
        DiagnosticEntry(
            code="ONLINE-E1203",
            severity="error",
            title="Execution mode is unsupported",
            owner="runtime",
            status="active",
            docs="docs/Diagnostics.md#online-e1203",
            introduced="1.0.0",
            problem_template="The session execution mode is not supported.",
            use_template='Use execution_mode = "online" or execution_mode = "generated".',
        ),
        DiagnosticEntry(
            code="CLI-X1101",
            severity="internal",
            title="Unexpected internal failure",
            owner="cli",
            status="active",
            docs="docs/Diagnostics.md#cli-x1101",
            introduced="1.0.0",
            problem_template="Structure hit an unclassified internal failure while running a CLI command.",
            use_template="Rerun with the same command and report the diagnostic code with a concise reproduction.",
        ),
        DiagnosticEntry(
            code="STREAM-E0801",
            severity="error",
            title="Transform is not streaming-compatible",
            owner="streaming",
            status="active",
            docs="docs/Diagnostics.md#stream-e0801",
            introduced="1.0.0",
            problem_template="A transform step contains an operation that is not compatible with streaming execution.",
            use_template=(
                "Keep the transform batch-only, add the required watermark or event-time bound, "
                "or rewrite the operation using a supported streaming shape."
            ),
        ),
        DiagnosticEntry(
            code="STREAM-W0801",
            severity="warning",
            title="Hook streaming compatibility is unknown",
            owner="streaming",
            status="active",
            docs="docs/Diagnostics.md#stream-w0801",
            introduced="1.0.0",
            problem_template="A hook contains arbitrary PySpark code Structure cannot prove streaming-compatible.",
            use_template="Mark the hook streaming=True only after verifying it satisfies the streaming contract.",
        ),
        DiagnosticEntry(
            code="STREAM-W0802",
            severity="warning",
            title="Streaming aggregate state is unbounded",
            owner="streaming",
            status="active",
            docs="docs/Diagnostics.md#stream-w0802",
            introduced="1.0.0",
            problem_template="A Spark-valid streaming aggregate does not have watermark-bounded state.",
            use_template="Use an event-time or session window with a matching watermark, or accept the caller-owned unbounded-state policy.",
        ),
        DiagnosticEntry(
            code="STREAM-E0802",
            severity="error",
            title="Streaming output is not accepted by downstream input",
            owner="streaming",
            status="active",
            docs="docs/Diagnostics.md#stream-e0802",
            introduced="1.0.0",
            problem_template="A streaming stage output is consumed by a downstream input that does not accept streaming data.",
            use_template=(
                "Declare the downstream input with streaming=True, or explicitly allow the "
                "stream-to-batch boundary with allow_stream_to_batch=True."
            ),
        ),
    ]
)
