status = error
name = SparkIntegration

appender.console.type = Console
appender.console.name = STDERR
appender.console.target = SYSTEM_ERR
appender.console.layout.type = PatternLayout
appender.console.layout.pattern = %d{HH:mm:ss.SSS} %-5p %c{1}: %m%n%throwable

rootLogger.level = warn
rootLogger.appenderRef.stderr.ref = STDERR
