# Generated by Structure. Do not edit by hand.
# Source: examples.security.schemas.alarms

from pyspark.sql import types as T


TEAM_VULNERABILITY_ALARM_SCHEMA = T.StructType([
    T.StructField("delivery_key", T.StringType(), False),
    T.StructField("vuln_id", T.StringType(), False),
    T.StructField("team_id", T.StringType(), False),
    T.StructField("team_name", T.StringType(), False),
    T.StructField("severity", T.StringType(), False),
    T.StructField("target_date", T.DateType(), False),
    T.StructField("instructions", T.StringType(), False),
])
