# Generated by Structure. Do not edit by hand.
# Source: examples.security.schemas.assets

from pyspark.sql import types as T


DEVICE_TYPE_SCHEMA = T.StructType([
    T.StructField("id", T.StringType(), False),
    T.StructField("nature", T.StringType(), False),
    T.StructField("type", T.StringType(), False),
    T.StructField("make", T.StringType(), False),
    T.StructField("platform", T.StringType(), False),
    T.StructField("model", T.StringType(), False),
    T.StructField("version", T.StringType(), False),
])

SOFTWARE_SCHEMA = T.StructType([
    T.StructField("id", T.StringType(), False),
    T.StructField("nature", T.StringType(), False),
    T.StructField("name", T.StringType(), False),
    T.StructField("vendor", T.StringType(), False),
    T.StructField("version", T.StringType(), False),
])

APP_SCHEMA = T.StructType(SOFTWARE_SCHEMA.fields)

O_S_SCHEMA = T.StructType(SOFTWARE_SCHEMA.fields)

SCANNER_SCHEMA = T.StructType(SOFTWARE_SCHEMA.fields)

DEVICE_SCHEMA = T.StructType([
    T.StructField("id", T.StringType(), False),
    T.StructField("device_type_id", T.StringType(), False),
    T.StructField("owner_id", T.StringType(), False),
    T.StructField("os_id", T.StringType(), False),
    T.StructField("apps", T.ArrayType(APP_SCHEMA, containsNull=False), False),
    T.StructField("vuln_ids", T.ArrayType(T.StringType(), containsNull=False), False),
])
