# Generated by Structure. Do not edit by hand.
# Source: examples.security.schemas.events

from pyspark.sql import types as T


RAW_EVENT_SCHEMA = T.StructType([
    T.StructField("id", T.StringType(), False),
    T.StructField("device_id", T.StringType(), False),
    T.StructField("scanner_id", T.StringType(), False),
    T.StructField("occurred_at", T.TimestampType(), False),
    T.StructField("event_family", T.StringType(), False),
])

APP_EVENT_SCHEMA = T.StructType(RAW_EVENT_SCHEMA.fields + [
    T.StructField("app_id", T.StringType(), False),
    T.StructField("action", T.StringType(), False),
    T.StructField("version", T.StringType(), False),
])

VULN_EVENT_SCHEMA = T.StructType(RAW_EVENT_SCHEMA.fields + [
    T.StructField("vuln_id", T.StringType(), False),
    T.StructField("action", T.StringType(), False),
    T.StructField("description", T.StringType(), False),
    T.StructField("instructions", T.StringType(), False),
])
