# Generated by Structure. Do not edit by hand.
# Source: examples.stocks.transforms.advanced.Advanced

from pyspark.sql import DataFrame, SparkSession
from pyspark.sql import Window
from pyspark.sql import functions as F
from pyspark.sql import types as T
from examples.structure_generated.stocks.runtime.schema_assert import TransformResult, assert_schema, project_schema
from examples.structure_generated.stocks.pyspark.schemas.indicators import ADVANCED_INDICATOR_SCHEMA
from examples.structure_generated.stocks.pyspark.schemas.market import BENCHMARK_RETURN_SCHEMA, DAILY_RETURN_SCHEMA


class AdvancedGenerated:

    def __init__(self, *, spark: SparkSession, ctx=None):
        self.spark = spark
        self.ctx = ctx

    def run(
        self,
        *,
        returns: DataFrame,
        benchmarks: DataFrame,
    ) -> TransformResult:
        assert_schema(returns, DAILY_RETURN_SCHEMA, name="DailyReturn", mode="strict")
        assert_schema(benchmarks, BENCHMARK_RETURN_SCHEMA, name="BenchmarkReturn", mode="strict")
        _input_returns = returns
        _input_benchmarks = benchmarks

        # Step method: calculate
        indicators = returns.alias("daily_return")
        benchmarks_joined = benchmarks.alias("benchmarks")
        indicators = indicators.join(
            benchmarks_joined,
            (F.col("daily_return.trade_date") == F.col("benchmarks.trade_date")),
            "inner",
        )
        indicators = indicators.select(
            F.col("daily_return.symbol"),
            F.col("daily_return.trade_date"),
            F.col("daily_return.return_1d"),
            F.col("benchmarks.return_1d").alias("benchmark_return"),
            (F.col("daily_return.return_1d") - F.col("benchmarks.return_1d")).alias("excess_return"),
            F.rank().over(Window.partitionBy(F.col("daily_return.trade_date")).orderBy(F.col("daily_return.return_1d").desc())).cast(T.LongType()).alias("daily_return_rank"),
            ((F.col("daily_return.close") / F.max(F.col("daily_return.close")).over(Window.partitionBy(F.col("daily_return.symbol")).orderBy(F.col("daily_return.trade_date").asc()).rowsBetween(-19, Window.currentRow))) - F.lit(1.0)).alias("drawdown"),
            F.stddev(F.col("daily_return.return_1d")).over(Window.partitionBy(F.col("daily_return.symbol")).orderBy(F.col("daily_return.trade_date").asc()).rowsBetween(-19, Window.currentRow)).alias("realized_volatility_20"),
        )

        # Step method: indicators
        indicators = indicators.alias("advanced_indicator")
        assert_schema(indicators, ADVANCED_INDICATOR_SCHEMA, name="AdvancedIndicator", mode="strict")
        return TransformResult({"indicators": indicators}, single=True, schema={"indicators": ADVANCED_INDICATOR_SCHEMA})
