# Generated by Structure. Do not edit by hand.
# Source: examples.store.transforms.merchandising.Merchandising.Merchandising

from __future__ import annotations
from pyspark.sql import DataFrame, SparkSession
from pyspark.sql import Window
from pyspark.sql import functions as F
from pyspark.sql import types as T
from examples.structure_generated.store.runtime.schema_assert import TransformResult, assert_schema, project_schema
from examples.structure_generated.store.pyspark.schemas.catalog import (
    CATALOG_PRODUCT_SCHEMA,
    RECOMMENDATION_CANDIDATE_SCHEMA,
)
from examples.structure_generated.store.pyspark.schemas.common import TENANT_KEY_SCHEMA
from examples.structure_generated.store.pyspark.schemas.feedback import PRODUCT_RECOMMENDATION_SIGNAL_SCHEMA
from examples.structure_generated.store.pyspark.schemas.merchandising_intermediate import (
    RANKED_RECOMMENDATION_CANDIDATE_SCHEMA,
)
from examples.structure_generated.store.pyspark.schemas.policy import (
    MERCHANDISING_BOOST_SCHEMA,
    MERCHANDISING_POLICY_SCHEMA,
    MERCHANDISING_SUPPRESSION_SCHEMA,
)
from examples.structure_generated.store.pyspark.schemas.product import BLOCKED_PRODUCT_SCHEMA, PRODUCT_SCHEMA
from examples.structure_generated.store.pyspark.schemas.promotion import PROMOTION_SCHEMA
from examples.structure_generated.store.pyspark.schemas.recommendation import (
    RECOMMENDATION_REQUEST_SCHEMA,
    RECOMMENDATION_RUN_SCHEMA,
    RECOMMENDED_PRODUCT_SCHEMA,
)


class PrepareCatalogGenerated:
    def _step_cataloged_prepare_0(self, frames):
        # Step method: cataloged.prepare
        cataloged__products = frames["products"].alias("product")
        cataloged__products = cataloged__products.where((F.col("product.active")))
        blocked_products_joined = frames["blocked_products"].alias("blocked_products")
        cataloged__products = cataloged__products.join(
            blocked_products_joined,
            (
                (F.col("blocked_products.tenant.tenant_id") == F.col("product.tenant.tenant_id"))
                & (F.col("blocked_products.id") == F.col("product.id"))
            ),
            "left_anti",
        )
        promotions_2_joined = frames["promotions"].alias("promotions_2")
        cataloged__products = cataloged__products.join(
            promotions_2_joined,
            (
                (F.col("promotions_2.tenant.tenant_id") == F.col("product.tenant.tenant_id"))
                & (
                    (F.lower(F.trim(F.col("promotions_2.code"))) == F.lower(F.trim(F.col("product.id"))))
                    | F.lower(F.trim(F.col("promotions_2.code"))).eqNullSafe(F.lower(F.trim(F.col("product.category"))))
                )
            ),
            "left",
        )
        cataloged__products = cataloged__products.select(
            F.col("product.tenant"),
            F.col("product.audit"),
            F.col("product.id").alias("product_id"),
            F.col("product.name").alias("product_name"),
            F.col("product.category"),
            F.col("product.active"),
            F.col("product.list_price"),
            F.col("product.rating"),
            F.col("promotions_2.code").isNotNull().alias("has_promotion"),
            F.col("promotions_2.code").alias("promotion_code"),
            F.col("promotions_2.name").alias("promotion_name"),
            F.col("promotions_2.discount").alias("promotion_discount"),
            F.lit(1.0).alias("base_score"),
            F.when(F.col("promotions_2.code").isNotNull(), F.lit(0.5)).otherwise(F.lit(0.0)).alias("promotion_score"),
            F.lit(True).alias("eligible"),
        )
        assert_schema(cataloged__products, CATALOG_PRODUCT_SCHEMA, name="CatalogProduct", mode="strict")
        return {
            "cataloged__products": cataloged__products,
        }


class SelectRecommendationCandidatesGenerated:
    def _step_recommended_selected_select_1(self, frames):
        # Step method: recommended.selected.select
        recommended__selected__requests = frames["requests"].alias("recommendation_request")
        cataloged__products_joined = frames["cataloged__products"].alias("cataloged__products")
        recommended__selected__requests = recommended__selected__requests.join(
            cataloged__products_joined,
            (
                (
                    (F.col("cataloged__products.tenant.tenant_id") == F.col("recommendation_request.tenant.tenant_id"))
                    & F.col("cataloged__products.eligible")
                )
                & (
                    F.col("recommendation_request.category").isNull()
                    | F.col("recommendation_request.category").eqNullSafe(F.col("cataloged__products.category"))
                )
            ),
            "inner",
        )
        recommended__selected__requests = recommended__selected__requests.select(
            F.col("recommendation_request.tenant"),
            F.col("recommendation_request.id").alias("request_id"),
            F.col("recommendation_request.requested_at"),
            F.col("recommendation_request.customer_id"),
            F.col("recommendation_request.strategy_id"),
            F.col("recommendation_request.policy_version"),
            F.col("recommendation_request.category").alias("category_filter"),
            F.col("recommendation_request.collection_id"),
            F.col("cataloged__products.product_id"),
            F.col("cataloged__products.product_name"),
            F.col("cataloged__products.category"),
            F.col("cataloged__products.has_promotion"),
            F.col("cataloged__products.promotion_code"),
            F.col("cataloged__products.base_score"),
            F.col("cataloged__products.promotion_score"),
            F.lit(0.0).alias("inventory_boost"),
        )
        assert_schema(
            recommended__selected__requests,
            RECOMMENDATION_CANDIDATE_SCHEMA,
            name="RecommendationCandidate",
            mode="strict",
        )
        return {
            "recommended__selected__requests": recommended__selected__requests,
        }


class RankRecommendationCandidatesGenerated:
    def _step_recommended_ranked_rank_2(self, frames):
        # Step method: recommended.ranked.rank
        recommended__ranked__candidates = frames["recommended__selected__requests"].alias("recommendation_candidate")
        policy_joined = frames["policy"].alias("policy")
        recommended__ranked__candidates = recommended__ranked__candidates.join(
            policy_joined,
            (
                (
                    (F.col("policy.tenant.tenant_id") == F.col("recommendation_candidate.tenant.tenant_id"))
                    & (F.col("policy.strategy_id") == F.col("recommendation_candidate.strategy_id"))
                )
                & (F.col("policy.policy_version") == F.col("recommendation_candidate.policy_version"))
            ),
            "inner",
        )
        boosts_2_joined = frames["boosts"].alias("boosts_2")
        recommended__ranked__candidates = recommended__ranked__candidates.join(
            boosts_2_joined,
            (
                (
                    (
                        (F.col("boosts_2.tenant.tenant_id") == F.col("recommendation_candidate.tenant.tenant_id"))
                        & (F.col("boosts_2.policy_version") == F.col("policy.policy_version"))
                    )
                    & F.col("boosts_2.active")
                )
                & (
                    F.col("boosts_2.product_id").eqNullSafe(F.col("recommendation_candidate.product_id"))
                    | F.col("boosts_2.category").eqNullSafe(F.col("recommendation_candidate.category"))
                )
            ),
            "left",
        )
        suppressions_3_joined = frames["suppressions"].alias("suppressions_3")
        recommended__ranked__candidates = recommended__ranked__candidates.join(
            suppressions_3_joined,
            (
                (
                    (
                        (F.col("suppressions_3.tenant.tenant_id") == F.col("recommendation_candidate.tenant.tenant_id"))
                        & (F.col("suppressions_3.policy_version") == F.col("policy.policy_version"))
                    )
                    & F.col("suppressions_3.active")
                )
                & (
                    F.col("suppressions_3.product_id").eqNullSafe(F.col("recommendation_candidate.product_id"))
                    | F.col("suppressions_3.category").eqNullSafe(F.col("recommendation_candidate.category"))
                )
            ),
            "left",
        )
        recommended__ranked__candidates = recommended__ranked__candidates.where(
            ((F.coalesce(F.col("suppressions_3.exclude"), F.lit(False)) == F.lit(False)))
        )
        signals_4_joined = frames["signals"].alias("signals_4")
        recommended__ranked__candidates = recommended__ranked__candidates.join(
            signals_4_joined,
            (
                (
                    (F.col("signals_4.tenant.tenant_id") == F.col("recommendation_candidate.tenant.tenant_id"))
                    & (F.col("signals_4.strategy_id") == F.col("recommendation_candidate.strategy_id"))
                )
                & (F.col("signals_4.product_id") == F.col("recommendation_candidate.product_id"))
            ),
            "left",
        )
        recommended__ranked__candidates = recommended__ranked__candidates.select(
            F.col("recommendation_candidate.tenant"),
            F.col("recommendation_candidate.request_id"),
            F.col("recommendation_candidate.strategy_id"),
            F.col("policy.policy_version"),
            F.col("recommendation_candidate.product_id"),
            F.col("recommendation_candidate.product_name"),
            F.col("recommendation_candidate.category"),
            F.row_number()
            .over(
                Window.partitionBy(
                    F.col("recommendation_candidate.tenant.tenant_id"), F.col("recommendation_candidate.request_id")
                ).orderBy(
                    (
                        (
                            (
                                (
                                    (
                                        F.col("recommendation_candidate.base_score")
                                        + F.col("recommendation_candidate.promotion_score")
                                    )
                                    + F.coalesce(F.col("boosts_2.boost_score"), F.lit(0.0))
                                )
                                + F.col("recommendation_candidate.inventory_boost")
                            )
                            + F.coalesce(
                                F.when(
                                    (
                                        (
                                            F.coalesce(F.col("signals_4.impression_count"), F.lit(0))
                                            >= F.col("policy.minimum_feedback_impressions")
                                        )
                                        & F.col("signals_4.click_through_rate").isNotNull()
                                    ),
                                    (F.col("signals_4.click_through_rate") * F.col("policy.feedback_weight")),
                                ).otherwise(F.lit(0.0)),
                                F.lit(0.0),
                            )
                        )
                        - F.coalesce(F.col("suppressions_3.penalty"), F.lit(0.0))
                    ).desc(),
                    F.coalesce(F.col("suppressions_3.penalty"), F.lit(0.0)).asc(),
                    F.col("recommendation_candidate.inventory_boost").desc(),
                    F.col("recommendation_candidate.product_id").asc(),
                )
            )
            .cast(T.LongType())
            .alias("rank"),
            F.col("recommendation_candidate.base_score"),
            F.col("recommendation_candidate.promotion_score"),
            F.coalesce(F.col("boosts_2.boost_score"), F.lit(0.0)).alias("boost_score"),
            F.coalesce(F.col("suppressions_3.penalty"), F.lit(0.0)).alias("suppression_penalty"),
            F.col("recommendation_candidate.inventory_boost"),
            F.coalesce(
                F.when(
                    (
                        (
                            F.coalesce(F.col("signals_4.impression_count"), F.lit(0))
                            >= F.col("policy.minimum_feedback_impressions")
                        )
                        & F.col("signals_4.click_through_rate").isNotNull()
                    ),
                    (F.col("signals_4.click_through_rate") * F.col("policy.feedback_weight")),
                ).otherwise(F.lit(0.0)),
                F.lit(0.0),
            ).alias("feedback_score"),
            (
                (
                    (
                        (
                            (
                                F.col("recommendation_candidate.base_score")
                                + F.col("recommendation_candidate.promotion_score")
                            )
                            + F.coalesce(F.col("boosts_2.boost_score"), F.lit(0.0))
                        )
                        + F.col("recommendation_candidate.inventory_boost")
                    )
                    + F.coalesce(
                        F.when(
                            (
                                (
                                    F.coalesce(F.col("signals_4.impression_count"), F.lit(0))
                                    >= F.col("policy.minimum_feedback_impressions")
                                )
                                & F.col("signals_4.click_through_rate").isNotNull()
                            ),
                            (F.col("signals_4.click_through_rate") * F.col("policy.feedback_weight")),
                        ).otherwise(F.lit(0.0)),
                        F.lit(0.0),
                    )
                )
                - F.coalesce(F.col("suppressions_3.penalty"), F.lit(0.0))
            ).alias("final_score"),
            (
                F.coalesce(F.col("signals_4.impression_count"), F.lit(0))
                >= F.col("policy.minimum_feedback_impressions")
            ).alias("feedback_contributed"),
            F.col("policy.maximum_results"),
        )
        assert_schema(
            recommended__ranked__candidates,
            RANKED_RECOMMENDATION_CANDIDATE_SCHEMA,
            name="RankedRecommendationCandidate",
            mode="strict",
        )
        return {
            "recommended__ranked__candidates": recommended__ranked__candidates,
        }


class SelectRecommendedProductsGenerated:
    def _step_recommended_admitted_select_products_3(self, frames):
        # Step method: recommended.admitted.select_products
        recommended__admitted__ranked_candidates = frames["recommended__ranked__candidates"].alias(
            "ranked_recommendation_candidate"
        )
        recommended__admitted__ranked_candidates = recommended__admitted__ranked_candidates.where(
            (
                (
                    F.col("ranked_recommendation_candidate.rank")
                    <= F.col("ranked_recommendation_candidate.maximum_results")
                )
            )
        )
        recommended__admitted__ranked_candidates = recommended__admitted__ranked_candidates.select(
            F.col("ranked_recommendation_candidate.tenant"),
            F.col("ranked_recommendation_candidate.request_id"),
            F.col("ranked_recommendation_candidate.strategy_id"),
            F.col("ranked_recommendation_candidate.policy_version"),
            F.col("ranked_recommendation_candidate.product_id"),
            F.col("ranked_recommendation_candidate.product_name"),
            F.col("ranked_recommendation_candidate.category"),
            F.col("ranked_recommendation_candidate.rank"),
            F.col("ranked_recommendation_candidate.base_score"),
            F.col("ranked_recommendation_candidate.promotion_score"),
            F.col("ranked_recommendation_candidate.boost_score"),
            F.col("ranked_recommendation_candidate.suppression_penalty"),
            F.col("ranked_recommendation_candidate.inventory_boost"),
            F.col("ranked_recommendation_candidate.feedback_score"),
            F.col("ranked_recommendation_candidate.final_score"),
            F.col("ranked_recommendation_candidate.feedback_contributed"),
        )
        assert_schema(
            recommended__admitted__ranked_candidates,
            RECOMMENDED_PRODUCT_SCHEMA,
            name="RecommendedProduct",
            mode="strict",
        )
        return {
            "recommended__admitted__ranked_candidates": recommended__admitted__ranked_candidates,
        }


class SummarizeRecommendationRunsGenerated:
    def _step_recommended_summarized_summarize_4(self, frames):
        # Step method: recommended.summarized.summarize
        recommended__summarized__requests = frames["requests"].alias("recommendation_request")
        policy_joined = frames["policy"].alias("policy")
        recommended__summarized__requests = recommended__summarized__requests.join(
            policy_joined,
            (
                (
                    (F.col("policy.tenant.tenant_id") == F.col("recommendation_request.tenant.tenant_id"))
                    & (F.col("policy.strategy_id") == F.col("recommendation_request.strategy_id"))
                )
                & (F.col("policy.policy_version") == F.col("recommendation_request.policy_version"))
            ),
            "inner",
        )
        recommended__admitted__ranked_candidates_2_joined = frames["recommended__admitted__ranked_candidates"].alias(
            "recommended__admitted__ranked_candidates_2"
        )
        recommended__summarized__requests = recommended__summarized__requests.join(
            recommended__admitted__ranked_candidates_2_joined,
            (
                (
                    (
                        F.col("recommended__admitted__ranked_candidates_2.tenant.tenant_id")
                        == F.col("recommendation_request.tenant.tenant_id")
                    )
                    & (
                        F.col("recommended__admitted__ranked_candidates_2.request_id")
                        == F.col("recommendation_request.id")
                    )
                )
                & (F.col("recommended__admitted__ranked_candidates_2.policy_version") == F.col("policy.policy_version"))
            ),
            "left",
        )
        recommended__summarized__requests = (
            recommended__summarized__requests.groupBy(
                F.col("recommendation_request.tenant.tenant_id").alias("tenant_id"),
                F.col("recommendation_request.id").alias("request_id"),
                F.col("recommendation_request.strategy_id").alias("strategy_id"),
                F.col("policy.policy_version").alias("policy_version"),
            )
            .agg(
                F.first(F.col("recommendation_request.tenant"), ignorenulls=False).alias("tenant"),
                F.sum(
                    F.when(
                        F.col("recommended__admitted__ranked_candidates_2.product_id").isNotNull(), F.lit(1)
                    ).otherwise(F.lit(0))
                )
                .cast(T.LongType())
                .alias("result_count"),
                F.bool_or(
                    F.coalesce(F.col("recommended__admitted__ranked_candidates_2.feedback_contributed"), F.lit(False))
                )
                .cast(T.BooleanType())
                .alias("feedback_contributed"),
            )
            .select(
                F.col("tenant"),
                F.col("request_id"),
                F.col("strategy_id"),
                F.col("policy_version"),
                F.col("result_count"),
                F.col("feedback_contributed"),
            )
        )
        return {
            "recommended__summarized__requests": recommended__summarized__requests,
        }


class MerchandisingGenerated(
    PrepareCatalogGenerated,
    SelectRecommendationCandidatesGenerated,
    RankRecommendationCandidatesGenerated,
    SelectRecommendedProductsGenerated,
    SummarizeRecommendationRunsGenerated,
):

    def __init__(self, *, spark: SparkSession, ctx=None):
        self.spark = spark
        self.ctx = ctx

    def run(
        self,
        *,
        products: DataFrame,
        blocked_products: DataFrame,
        promotions: DataFrame,
        requests: DataFrame,
        policy: DataFrame,
        boosts: DataFrame,
        suppressions: DataFrame,
        signals: DataFrame,
    ) -> TransformResult:
        assert_schema(products, PRODUCT_SCHEMA, name="Product", mode="strict")
        assert_schema(blocked_products, BLOCKED_PRODUCT_SCHEMA, name="BlockedProduct", mode="strict")
        assert_schema(promotions, PROMOTION_SCHEMA, name="Promotion", mode="strict")
        assert_schema(requests, RECOMMENDATION_REQUEST_SCHEMA, name="RecommendationRequest", mode="strict")
        assert_schema(policy, MERCHANDISING_POLICY_SCHEMA, name="MerchandisingPolicy", mode="strict")
        assert_schema(boosts, MERCHANDISING_BOOST_SCHEMA, name="MerchandisingBoost", mode="strict")
        assert_schema(suppressions, MERCHANDISING_SUPPRESSION_SCHEMA, name="MerchandisingSuppression", mode="strict")
        assert_schema(signals, PRODUCT_RECOMMENDATION_SIGNAL_SCHEMA, name="ProductRecommendationSignal", mode="strict")
        _input_products = products
        _input_blocked_products = blocked_products
        _input_promotions = promotions
        _input_requests = requests
        _input_policy = policy
        _input_boosts = boosts
        _input_suppressions = suppressions
        _input_signals = signals
        frames = {
            "products": products,
            "blocked_products": blocked_products,
            "promotions": promotions,
            "requests": requests,
            "policy": policy,
            "boosts": boosts,
            "suppressions": suppressions,
            "signals": signals,
            "input:products": _input_products,
            "input:blocked_products": _input_blocked_products,
            "input:promotions": _input_promotions,
            "input:requests": _input_requests,
            "input:policy": _input_policy,
            "input:boosts": _input_boosts,
            "input:suppressions": _input_suppressions,
            "input:signals": _input_signals,
        }
        frames.update(self._step_cataloged_prepare_0(frames))
        frames.update(self._step_recommended_selected_select_1(frames))
        frames.update(self._step_recommended_ranked_rank_2(frames))
        frames.update(self._step_recommended_admitted_select_products_3(frames))
        frames.update(self._step_recommended_summarized_summarize_4(frames))

        # Step method: recommended_products
        recommended_products = frames["recommended__admitted__ranked_candidates"].alias("recommended_product")
        assert_schema(recommended_products, RECOMMENDED_PRODUCT_SCHEMA, name="RecommendedProduct", mode="strict")

        # Step method: recommendation_runs
        recommendation_runs = frames["recommended__summarized__requests"].alias("recommendation_run")
        assert_schema(recommendation_runs, RECOMMENDATION_RUN_SCHEMA, name="RecommendationRun", mode="strict")
        return TransformResult(
            {"recommended_products": recommended_products, "recommendation_runs": recommendation_runs},
            single=False,
            schema={
                "recommended_products": RECOMMENDED_PRODUCT_SCHEMA,
                "recommendation_runs": RECOMMENDATION_RUN_SCHEMA,
            },
        )
