# Generated by Structure. Do not edit by hand.
# Source: examples.store.transforms.merchandising.catalog.PrepareCatalog.PrepareCatalog

from __future__ import annotations
from pyspark.sql import DataFrame, SparkSession
from pyspark.sql import functions as F
from pyspark.sql import types as T
from examples.structure_generated.store.runtime.schema_assert import TransformResult, assert_schema, project_schema
from examples.structure_generated.store.pyspark.schemas.catalog import CATALOG_PRODUCT_SCHEMA
from examples.structure_generated.store.pyspark.schemas.product import BLOCKED_PRODUCT_SCHEMA, PRODUCT_SCHEMA
from examples.structure_generated.store.pyspark.schemas.promotion import PROMOTION_SCHEMA


class PrepareCatalogGenerated:

    def __init__(self, *, spark: SparkSession, ctx=None):
        self.spark = spark
        self.ctx = ctx

    def run(
        self,
        *,
        products: DataFrame,
        blocked_products: DataFrame,
        promotions: DataFrame,
    ) -> TransformResult:
        assert_schema(products, PRODUCT_SCHEMA, name="Product", mode="strict")
        assert_schema(blocked_products, BLOCKED_PRODUCT_SCHEMA, name="BlockedProduct", mode="strict")
        assert_schema(promotions, PROMOTION_SCHEMA, name="Promotion", mode="strict")
        _input_products = products
        _input_blocked_products = blocked_products
        _input_promotions = promotions

        # Step method: prepare
        products = products.alias("product")
        products = products.where((F.col("product.active")))
        blocked_products_joined = blocked_products.alias("blocked_products")
        products = products.join(
            blocked_products_joined,
            (
                (F.col("blocked_products.tenant.tenant_id") == F.col("product.tenant.tenant_id"))
                & (F.col("blocked_products.id") == F.col("product.id"))
            ),
            "left_anti",
        )
        promotions_2_joined = promotions.alias("promotions_2")
        products = products.join(
            promotions_2_joined,
            (
                (F.col("promotions_2.tenant.tenant_id") == F.col("product.tenant.tenant_id"))
                & (
                    (F.lower(F.trim(F.col("promotions_2.code"))) == F.lower(F.trim(F.col("product.id"))))
                    | F.lower(F.trim(F.col("promotions_2.code"))).eqNullSafe(F.lower(F.trim(F.col("product.category"))))
                )
            ),
            "left",
        )
        products = products.select(
            F.col("product.tenant"),
            F.col("product.audit"),
            F.col("product.id").alias("product_id"),
            F.col("product.name").alias("product_name"),
            F.col("product.category"),
            F.col("product.active"),
            F.col("product.list_price"),
            F.col("product.rating"),
            F.col("promotions_2.code").isNotNull().alias("has_promotion"),
            F.col("promotions_2.code").alias("promotion_code"),
            F.col("promotions_2.name").alias("promotion_name"),
            F.col("promotions_2.discount").alias("promotion_discount"),
            F.lit(1.0).alias("base_score"),
            F.when(F.col("promotions_2.code").isNotNull(), F.lit(0.5)).otherwise(F.lit(0.0)).alias("promotion_score"),
            F.lit(True).alias("eligible"),
        )

        # Step method: catalog
        catalog = products.alias("catalog_product")
        assert_schema(catalog, CATALOG_PRODUCT_SCHEMA, name="CatalogProduct", mode="strict")
        return TransformResult({"catalog": catalog}, single=True, schema={"catalog": CATALOG_PRODUCT_SCHEMA})
