# Generated by Structure. Do not edit by hand.
# Source: examples.store.transforms.merchandising.recommender.Recommender.Recommender

from __future__ import annotations
from pyspark.sql import DataFrame, SparkSession
from pyspark.sql import Window
from pyspark.sql import functions as F
from pyspark.sql import types as T
from examples.structure_generated.store.runtime.schema_assert import TransformResult, assert_schema, project_schema
from examples.structure_generated.store.pyspark.schemas.catalog import (
    CATALOG_PRODUCT_SCHEMA,
    RECOMMENDATION_CANDIDATE_SCHEMA,
)
from examples.structure_generated.store.pyspark.schemas.common import TENANT_KEY_SCHEMA
from examples.structure_generated.store.pyspark.schemas.feedback import PRODUCT_RECOMMENDATION_SIGNAL_SCHEMA
from examples.structure_generated.store.pyspark.schemas.merchandising_intermediate import (
    RANKED_RECOMMENDATION_CANDIDATE_SCHEMA,
)
from examples.structure_generated.store.pyspark.schemas.policy import (
    MERCHANDISING_BOOST_SCHEMA,
    MERCHANDISING_POLICY_SCHEMA,
    MERCHANDISING_SUPPRESSION_SCHEMA,
)
from examples.structure_generated.store.pyspark.schemas.recommendation import (
    RECOMMENDATION_REQUEST_SCHEMA,
    RECOMMENDATION_RUN_SCHEMA,
    RECOMMENDED_PRODUCT_SCHEMA,
)


class SelectRecommendationCandidatesGenerated:
    def _step_selected_select_0(self, frames):
        # Step method: selected.select
        selected__requests = frames["requests"].alias("recommendation_request")
        catalog_joined = frames["catalog"].alias("catalog")
        selected__requests = selected__requests.join(
            catalog_joined,
            (
                (
                    (F.col("catalog.tenant.tenant_id") == F.col("recommendation_request.tenant.tenant_id"))
                    & F.col("catalog.eligible")
                )
                & (
                    F.col("recommendation_request.category").isNull()
                    | F.col("recommendation_request.category").eqNullSafe(F.col("catalog.category"))
                )
            ),
            "inner",
        )
        selected__requests = selected__requests.select(
            F.col("recommendation_request.tenant"),
            F.col("recommendation_request.id").alias("request_id"),
            F.col("recommendation_request.requested_at"),
            F.col("recommendation_request.customer_id"),
            F.col("recommendation_request.strategy_id"),
            F.col("recommendation_request.policy_version"),
            F.col("recommendation_request.category").alias("category_filter"),
            F.col("recommendation_request.collection_id"),
            F.col("catalog.product_id"),
            F.col("catalog.product_name"),
            F.col("catalog.category"),
            F.col("catalog.has_promotion"),
            F.col("catalog.promotion_code"),
            F.col("catalog.base_score"),
            F.col("catalog.promotion_score"),
            F.lit(0.0).alias("inventory_boost"),
        )
        assert_schema(
            selected__requests, RECOMMENDATION_CANDIDATE_SCHEMA, name="RecommendationCandidate", mode="strict"
        )
        return {
            "selected__requests": selected__requests,
        }


class RankRecommendationCandidatesGenerated:
    def _step_ranked_rank_1(self, frames):
        # Step method: ranked.rank
        ranked__candidates = frames["selected__requests"].alias("recommendation_candidate")
        policy_joined = frames["policy"].alias("policy")
        ranked__candidates = ranked__candidates.join(
            policy_joined,
            (
                (
                    (F.col("policy.tenant.tenant_id") == F.col("recommendation_candidate.tenant.tenant_id"))
                    & (F.col("policy.strategy_id") == F.col("recommendation_candidate.strategy_id"))
                )
                & (F.col("policy.policy_version") == F.col("recommendation_candidate.policy_version"))
            ),
            "inner",
        )
        boosts_2_joined = frames["boosts"].alias("boosts_2")
        ranked__candidates = ranked__candidates.join(
            boosts_2_joined,
            (
                (
                    (
                        (F.col("boosts_2.tenant.tenant_id") == F.col("recommendation_candidate.tenant.tenant_id"))
                        & (F.col("boosts_2.policy_version") == F.col("policy.policy_version"))
                    )
                    & F.col("boosts_2.active")
                )
                & (
                    F.col("boosts_2.product_id").eqNullSafe(F.col("recommendation_candidate.product_id"))
                    | F.col("boosts_2.category").eqNullSafe(F.col("recommendation_candidate.category"))
                )
            ),
            "left",
        )
        suppressions_3_joined = frames["suppressions"].alias("suppressions_3")
        ranked__candidates = ranked__candidates.join(
            suppressions_3_joined,
            (
                (
                    (
                        (F.col("suppressions_3.tenant.tenant_id") == F.col("recommendation_candidate.tenant.tenant_id"))
                        & (F.col("suppressions_3.policy_version") == F.col("policy.policy_version"))
                    )
                    & F.col("suppressions_3.active")
                )
                & (
                    F.col("suppressions_3.product_id").eqNullSafe(F.col("recommendation_candidate.product_id"))
                    | F.col("suppressions_3.category").eqNullSafe(F.col("recommendation_candidate.category"))
                )
            ),
            "left",
        )
        ranked__candidates = ranked__candidates.where(
            ((F.coalesce(F.col("suppressions_3.exclude"), F.lit(False)) == F.lit(False)))
        )
        signals_4_joined = frames["signals"].alias("signals_4")
        ranked__candidates = ranked__candidates.join(
            signals_4_joined,
            (
                (
                    (F.col("signals_4.tenant.tenant_id") == F.col("recommendation_candidate.tenant.tenant_id"))
                    & (F.col("signals_4.strategy_id") == F.col("recommendation_candidate.strategy_id"))
                )
                & (F.col("signals_4.product_id") == F.col("recommendation_candidate.product_id"))
            ),
            "left",
        )
        ranked__candidates = ranked__candidates.select(
            F.col("recommendation_candidate.tenant"),
            F.col("recommendation_candidate.request_id"),
            F.col("recommendation_candidate.strategy_id"),
            F.col("policy.policy_version"),
            F.col("recommendation_candidate.product_id"),
            F.col("recommendation_candidate.product_name"),
            F.col("recommendation_candidate.category"),
            F.row_number()
            .over(
                Window.partitionBy(
                    F.col("recommendation_candidate.tenant.tenant_id"), F.col("recommendation_candidate.request_id")
                ).orderBy(
                    (
                        (
                            (
                                (
                                    (
                                        F.col("recommendation_candidate.base_score")
                                        + F.col("recommendation_candidate.promotion_score")
                                    )
                                    + F.coalesce(F.col("boosts_2.boost_score"), F.lit(0.0))
                                )
                                + F.col("recommendation_candidate.inventory_boost")
                            )
                            + F.coalesce(
                                F.when(
                                    (
                                        (
                                            F.coalesce(F.col("signals_4.impression_count"), F.lit(0))
                                            >= F.col("policy.minimum_feedback_impressions")
                                        )
                                        & F.col("signals_4.click_through_rate").isNotNull()
                                    ),
                                    (F.col("signals_4.click_through_rate") * F.col("policy.feedback_weight")),
                                ).otherwise(F.lit(0.0)),
                                F.lit(0.0),
                            )
                        )
                        - F.coalesce(F.col("suppressions_3.penalty"), F.lit(0.0))
                    ).desc(),
                    F.coalesce(F.col("suppressions_3.penalty"), F.lit(0.0)).asc(),
                    F.col("recommendation_candidate.inventory_boost").desc(),
                    F.col("recommendation_candidate.product_id").asc(),
                )
            )
            .cast(T.LongType())
            .alias("rank"),
            F.col("recommendation_candidate.base_score"),
            F.col("recommendation_candidate.promotion_score"),
            F.coalesce(F.col("boosts_2.boost_score"), F.lit(0.0)).alias("boost_score"),
            F.coalesce(F.col("suppressions_3.penalty"), F.lit(0.0)).alias("suppression_penalty"),
            F.col("recommendation_candidate.inventory_boost"),
            F.coalesce(
                F.when(
                    (
                        (
                            F.coalesce(F.col("signals_4.impression_count"), F.lit(0))
                            >= F.col("policy.minimum_feedback_impressions")
                        )
                        & F.col("signals_4.click_through_rate").isNotNull()
                    ),
                    (F.col("signals_4.click_through_rate") * F.col("policy.feedback_weight")),
                ).otherwise(F.lit(0.0)),
                F.lit(0.0),
            ).alias("feedback_score"),
            (
                (
                    (
                        (
                            (
                                F.col("recommendation_candidate.base_score")
                                + F.col("recommendation_candidate.promotion_score")
                            )
                            + F.coalesce(F.col("boosts_2.boost_score"), F.lit(0.0))
                        )
                        + F.col("recommendation_candidate.inventory_boost")
                    )
                    + F.coalesce(
                        F.when(
                            (
                                (
                                    F.coalesce(F.col("signals_4.impression_count"), F.lit(0))
                                    >= F.col("policy.minimum_feedback_impressions")
                                )
                                & F.col("signals_4.click_through_rate").isNotNull()
                            ),
                            (F.col("signals_4.click_through_rate") * F.col("policy.feedback_weight")),
                        ).otherwise(F.lit(0.0)),
                        F.lit(0.0),
                    )
                )
                - F.coalesce(F.col("suppressions_3.penalty"), F.lit(0.0))
            ).alias("final_score"),
            (
                F.coalesce(F.col("signals_4.impression_count"), F.lit(0))
                >= F.col("policy.minimum_feedback_impressions")
            ).alias("feedback_contributed"),
            F.col("policy.maximum_results"),
        )
        assert_schema(
            ranked__candidates,
            RANKED_RECOMMENDATION_CANDIDATE_SCHEMA,
            name="RankedRecommendationCandidate",
            mode="strict",
        )
        return {
            "ranked__candidates": ranked__candidates,
        }


class SelectRecommendedProductsGenerated:
    def _step_admitted_select_products_2(self, frames):
        # Step method: admitted.select_products
        admitted__ranked_candidates = frames["ranked__candidates"].alias("ranked_recommendation_candidate")
        admitted__ranked_candidates = admitted__ranked_candidates.where(
            (
                (
                    F.col("ranked_recommendation_candidate.rank")
                    <= F.col("ranked_recommendation_candidate.maximum_results")
                )
            )
        )
        admitted__ranked_candidates = admitted__ranked_candidates.select(
            F.col("ranked_recommendation_candidate.tenant"),
            F.col("ranked_recommendation_candidate.request_id"),
            F.col("ranked_recommendation_candidate.strategy_id"),
            F.col("ranked_recommendation_candidate.policy_version"),
            F.col("ranked_recommendation_candidate.product_id"),
            F.col("ranked_recommendation_candidate.product_name"),
            F.col("ranked_recommendation_candidate.category"),
            F.col("ranked_recommendation_candidate.rank"),
            F.col("ranked_recommendation_candidate.base_score"),
            F.col("ranked_recommendation_candidate.promotion_score"),
            F.col("ranked_recommendation_candidate.boost_score"),
            F.col("ranked_recommendation_candidate.suppression_penalty"),
            F.col("ranked_recommendation_candidate.inventory_boost"),
            F.col("ranked_recommendation_candidate.feedback_score"),
            F.col("ranked_recommendation_candidate.final_score"),
            F.col("ranked_recommendation_candidate.feedback_contributed"),
        )
        assert_schema(admitted__ranked_candidates, RECOMMENDED_PRODUCT_SCHEMA, name="RecommendedProduct", mode="strict")
        return {
            "admitted__ranked_candidates": admitted__ranked_candidates,
        }


class SummarizeRecommendationRunsGenerated:
    def _step_summarized_summarize_3(self, frames):
        # Step method: summarized.summarize
        summarized__requests = frames["requests"].alias("recommendation_request")
        policy_joined = frames["policy"].alias("policy")
        summarized__requests = summarized__requests.join(
            policy_joined,
            (
                (
                    (F.col("policy.tenant.tenant_id") == F.col("recommendation_request.tenant.tenant_id"))
                    & (F.col("policy.strategy_id") == F.col("recommendation_request.strategy_id"))
                )
                & (F.col("policy.policy_version") == F.col("recommendation_request.policy_version"))
            ),
            "inner",
        )
        admitted__ranked_candidates_2_joined = frames["admitted__ranked_candidates"].alias(
            "admitted__ranked_candidates_2"
        )
        summarized__requests = summarized__requests.join(
            admitted__ranked_candidates_2_joined,
            (
                (
                    (
                        F.col("admitted__ranked_candidates_2.tenant.tenant_id")
                        == F.col("recommendation_request.tenant.tenant_id")
                    )
                    & (F.col("admitted__ranked_candidates_2.request_id") == F.col("recommendation_request.id"))
                )
                & (F.col("admitted__ranked_candidates_2.policy_version") == F.col("policy.policy_version"))
            ),
            "left",
        )
        summarized__requests = (
            summarized__requests.groupBy(
                F.col("recommendation_request.tenant.tenant_id").alias("tenant_id"),
                F.col("recommendation_request.id").alias("request_id"),
                F.col("recommendation_request.strategy_id").alias("strategy_id"),
                F.col("policy.policy_version").alias("policy_version"),
            )
            .agg(
                F.first(F.col("recommendation_request.tenant"), ignorenulls=False).alias("tenant"),
                F.sum(
                    F.when(F.col("admitted__ranked_candidates_2.product_id").isNotNull(), F.lit(1)).otherwise(F.lit(0))
                )
                .cast(T.LongType())
                .alias("result_count"),
                F.bool_or(F.coalesce(F.col("admitted__ranked_candidates_2.feedback_contributed"), F.lit(False)))
                .cast(T.BooleanType())
                .alias("feedback_contributed"),
            )
            .select(
                F.col("tenant"),
                F.col("request_id"),
                F.col("strategy_id"),
                F.col("policy_version"),
                F.col("result_count"),
                F.col("feedback_contributed"),
            )
        )
        return {
            "summarized__requests": summarized__requests,
        }


class RecommenderGenerated(
    SelectRecommendationCandidatesGenerated,
    RankRecommendationCandidatesGenerated,
    SelectRecommendedProductsGenerated,
    SummarizeRecommendationRunsGenerated,
):

    def __init__(self, *, spark: SparkSession, ctx=None):
        self.spark = spark
        self.ctx = ctx

    def run(
        self,
        *,
        requests: DataFrame,
        catalog: DataFrame,
        policy: DataFrame,
        boosts: DataFrame,
        suppressions: DataFrame,
        signals: DataFrame,
    ) -> TransformResult:
        assert_schema(requests, RECOMMENDATION_REQUEST_SCHEMA, name="RecommendationRequest", mode="strict")
        assert_schema(catalog, CATALOG_PRODUCT_SCHEMA, name="CatalogProduct", mode="strict")
        assert_schema(policy, MERCHANDISING_POLICY_SCHEMA, name="MerchandisingPolicy", mode="strict")
        assert_schema(boosts, MERCHANDISING_BOOST_SCHEMA, name="MerchandisingBoost", mode="strict")
        assert_schema(suppressions, MERCHANDISING_SUPPRESSION_SCHEMA, name="MerchandisingSuppression", mode="strict")
        assert_schema(signals, PRODUCT_RECOMMENDATION_SIGNAL_SCHEMA, name="ProductRecommendationSignal", mode="strict")
        _input_requests = requests
        _input_catalog = catalog
        _input_policy = policy
        _input_boosts = boosts
        _input_suppressions = suppressions
        _input_signals = signals
        frames = {
            "requests": requests,
            "catalog": catalog,
            "policy": policy,
            "boosts": boosts,
            "suppressions": suppressions,
            "signals": signals,
            "input:requests": _input_requests,
            "input:catalog": _input_catalog,
            "input:policy": _input_policy,
            "input:boosts": _input_boosts,
            "input:suppressions": _input_suppressions,
            "input:signals": _input_signals,
        }
        frames.update(self._step_selected_select_0(frames))
        frames.update(self._step_ranked_rank_1(frames))
        frames.update(self._step_admitted_select_products_2(frames))
        frames.update(self._step_summarized_summarize_3(frames))

        # Step method: recommended_products
        recommended_products = frames["admitted__ranked_candidates"].alias("recommended_product")
        assert_schema(recommended_products, RECOMMENDED_PRODUCT_SCHEMA, name="RecommendedProduct", mode="strict")

        # Step method: recommendation_runs
        recommendation_runs = frames["summarized__requests"].alias("recommendation_run")
        assert_schema(recommendation_runs, RECOMMENDATION_RUN_SCHEMA, name="RecommendationRun", mode="strict")
        return TransformResult(
            {"recommended_products": recommended_products, "recommendation_runs": recommendation_runs},
            single=False,
            schema={
                "recommended_products": RECOMMENDED_PRODUCT_SCHEMA,
                "recommendation_runs": RECOMMENDATION_RUN_SCHEMA,
            },
        )
