# Generated by Structure. Do not edit by hand.
# Source: examples.store.transforms.fulfillment.summarize.FulfillmentAnalytics

from __future__ import annotations
from pyspark.sql import DataFrame, SparkSession
from pyspark.sql import functions as F
from pyspark.sql import types as T
from examples.structure_generated.store.runtime.schema_assert import TransformResult, assert_schema, project_schema
from examples.structure_generated.store.pyspark.schemas.common import TENANT_KEY_SCHEMA
from examples.structure_generated.store.pyspark.schemas.plan import (
    FULFILLMENT_ALLOCATION_SCHEMA,
    FULFILLMENT_BACKORDER_SCHEMA,
    FULFILLMENT_PLAN_SCHEMA,
)
from examples.structure_generated.store.pyspark.schemas.summary import (
    DAILY_FULFILLMENT_SUMMARY_SCHEMA,
    WAREHOUSE_LOAD_SUMMARY_SCHEMA,
)


class FulfillmentAnalyticsGenerated:

    def __init__(self, *, spark: SparkSession, ctx=None):
        self.spark = spark
        self.ctx = ctx

    def run(
        self,
        *,
        plans: DataFrame,
        allocations: DataFrame,
        backorders: DataFrame,
    ) -> TransformResult:
        assert_schema(plans, FULFILLMENT_PLAN_SCHEMA, name="FulfillmentPlan", mode="strict")
        assert_schema(allocations, FULFILLMENT_ALLOCATION_SCHEMA, name="FulfillmentAllocation", mode="strict")
        assert_schema(backorders, FULFILLMENT_BACKORDER_SCHEMA, name="FulfillmentBackorder", mode="strict")
        _input_plans = plans
        _input_allocations = allocations
        _input_backorders = backorders

        # Step method: summarize_daily_totals
        daily_totals = plans.alias("fulfillment_plan")
        daily_totals = (
            daily_totals.groupBy(
                F.col("fulfillment_plan.tenant.tenant_id").alias("tenant_id"),
                F.col("fulfillment_plan.business.order_date").alias("business_date"),
            )
            .agg(
                F.first(F.col("fulfillment_plan.tenant"), ignorenulls=False).alias("tenant"),
                F.count(F.lit(1)).cast(T.LongType()).alias("demand_line_count"),
                F.sum(
                    F.when((F.col("fulfillment_plan.plan_status") == F.lit('allocated')), F.lit(1)).otherwise(F.lit(0))
                )
                .cast(T.LongType())
                .alias("allocated_line_count"),
                F.sum(
                    F.when((F.col("fulfillment_plan.plan_status") == F.lit('partially_allocated')), F.lit(1)).otherwise(
                        F.lit(0)
                    )
                )
                .cast(T.LongType())
                .alias("partially_allocated_line_count"),
                F.sum(
                    F.when((F.col("fulfillment_plan.plan_status") == F.lit('backordered')), F.lit(1)).otherwise(
                        F.lit(0)
                    )
                )
                .cast(T.LongType())
                .alias("backordered_line_count"),
                F.sum(F.col("fulfillment_plan.requested_quantity")).cast(T.LongType()).alias("requested_units"),
                F.sum(F.col("fulfillment_plan.allocated_quantity")).cast(T.LongType()).alias("allocated_units"),
                F.sum(F.col("fulfillment_plan.backordered_quantity")).cast(T.LongType()).alias("backordered_units"),
                F.sum(F.lit(0.0)).cast(T.DoubleType()).alias("fill_rate"),
                F.sum(F.lit(0.0)).cast(T.DoubleType()).alias("backorder_rate"),
            )
            .select(
                F.col("tenant"),
                F.col("business_date"),
                F.col("demand_line_count"),
                F.col("allocated_line_count"),
                F.col("partially_allocated_line_count"),
                F.col("backordered_line_count"),
                F.col("requested_units"),
                F.col("allocated_units"),
                F.col("backordered_units"),
                F.col("fill_rate"),
                F.col("backorder_rate"),
            )
        )
        assert_schema(daily_totals, DAILY_FULFILLMENT_SUMMARY_SCHEMA, name="DailyFulfillmentSummary", mode="strict")

        # Step method: publish_daily_summary
        daily_summary = daily_totals.alias("daily_fulfillment_summary")
        daily_summary = daily_summary.select(
            F.col("daily_fulfillment_summary.tenant"),
            F.col("daily_fulfillment_summary.business_date"),
            F.col("daily_fulfillment_summary.demand_line_count"),
            F.col("daily_fulfillment_summary.allocated_line_count"),
            F.col("daily_fulfillment_summary.partially_allocated_line_count"),
            F.col("daily_fulfillment_summary.backordered_line_count"),
            F.col("daily_fulfillment_summary.requested_units"),
            F.col("daily_fulfillment_summary.allocated_units"),
            F.col("daily_fulfillment_summary.backordered_units"),
            F.when(
                (F.col("daily_fulfillment_summary.requested_units") > F.lit(0)),
                (
                    F.col("daily_fulfillment_summary.allocated_units")
                    / F.col("daily_fulfillment_summary.requested_units")
                ),
            )
            .otherwise(F.lit(None))
            .alias("fill_rate"),
            F.when(
                (F.col("daily_fulfillment_summary.requested_units") > F.lit(0)),
                (
                    F.col("daily_fulfillment_summary.backordered_units")
                    / F.col("daily_fulfillment_summary.requested_units")
                ),
            )
            .otherwise(F.lit(None))
            .alias("backorder_rate"),
        )
        assert_schema(daily_summary, DAILY_FULFILLMENT_SUMMARY_SCHEMA, name="DailyFulfillmentSummary", mode="strict")

        # Step method: summarize_warehouse_load
        warehouse_load_summary = allocations.alias("fulfillment_allocation")
        warehouse_load_summary = (
            warehouse_load_summary.groupBy(
                F.col("fulfillment_allocation.tenant.tenant_id").alias("tenant_id"),
                F.col("fulfillment_allocation.warehouse_id").alias("warehouse_id"),
                F.col("fulfillment_allocation.business.order_date").alias("business_date"),
            )
            .agg(
                F.first(F.col("fulfillment_allocation.tenant"), ignorenulls=False).alias("tenant"),
                F.count(F.lit(1)).cast(T.LongType()).alias("planned_line_count"),
                F.sum(F.col("fulfillment_allocation.allocated_quantity")).cast(T.LongType()).alias("allocated_units"),
                F.countDistinct(F.col("fulfillment_allocation.product_id"))
                .cast(T.LongType())
                .alias("distinct_products"),
                F.countDistinct(F.col("fulfillment_allocation.customer_id")).cast(T.LongType()).alias("customer_count"),
            )
            .select(
                F.col("tenant"),
                F.col("warehouse_id"),
                F.col("business_date"),
                F.col("planned_line_count"),
                F.col("allocated_units"),
                F.col("distinct_products"),
                F.col("customer_count"),
            )
        )

        # Step method: daily_summary
        daily_summary = daily_summary.alias("daily_fulfillment_summary")
        assert_schema(daily_summary, DAILY_FULFILLMENT_SUMMARY_SCHEMA, name="DailyFulfillmentSummary", mode="strict")

        # Step method: warehouse_load_summary
        warehouse_load_summary = warehouse_load_summary.alias("warehouse_load_summary")
        assert_schema(warehouse_load_summary, WAREHOUSE_LOAD_SUMMARY_SCHEMA, name="WarehouseLoadSummary", mode="strict")
        return TransformResult(
            {"daily_summary": daily_summary, "warehouse_load_summary": warehouse_load_summary},
            single=False,
            schema={
                "daily_summary": DAILY_FULFILLMENT_SUMMARY_SCHEMA,
                "warehouse_load_summary": WAREHOUSE_LOAD_SUMMARY_SCHEMA,
            },
        )
