# Generated by Structure. Do not edit by hand.
# Source: examples.search.transforms.scoring.lexical.SelectPopularQueries.SelectPopularQueries

from __future__ import annotations
from pyspark.sql import DataFrame, SparkSession
from pyspark.sql import Window
from pyspark.sql import functions as F
from pyspark.sql import types as T
from examples.structure_generated.search.runtime.schema_assert import (
    TransformResult,
    assert_schema,
    project_schema,
    apply_plan_boundary,
    close_plan_boundaries,
)
from examples.structure_generated.search.pyspark.schemas.clicks import DAILY_IMPRESSIONS_SCHEMA
from examples.structure_generated.search.pyspark.schemas.scoring_intermediate import POPULAR_QUERY_CANDIDATE_SCHEMA
from examples.structure_generated.search.pyspark.schemas.search import QUERY_POPULARITY_SCHEMA, SEARCH_QUERY_SCHEMA


class SelectPopularQueriesGenerated:

    def __init__(self, *, spark: SparkSession, ctx=None):
        self.spark = spark
        self.ctx = ctx

    def close(self) -> None:
        close_plan_boundaries(self.spark)

    def run(
        self,
        *,
        queries: DataFrame,
        daily_impressions: DataFrame,
    ) -> TransformResult:
        assert_schema(queries, SEARCH_QUERY_SCHEMA, name="SearchQuery", mode="strict")
        assert_schema(daily_impressions, DAILY_IMPRESSIONS_SCHEMA, name="DailyImpressions", mode="strict")
        _input_queries = queries
        _input_daily_impressions = daily_impressions

        # Step method: summarize_popularity
        popularities = daily_impressions.alias("daily_impressions")
        popularities = (
            popularities.groupBy(
                F.lower(F.regexp_replace(F.trim(F.col("daily_impressions.query")), '\\s+', ' ')).alias("query"),
            )
            .agg(
                F.sum(F.col("daily_impressions.impression_count")).cast(T.LongType()).alias("impression_count"),
            )
            .select(
                F.col("query"),
                F.col("impression_count"),
            )
        )
        assert_schema(popularities, QUERY_POPULARITY_SCHEMA, name="QueryPopularity", mode="strict")

        # Step method: rank_queries
        ranked_queries = queries.alias("search_query")
        popularities_joined = popularities.alias("popularities")
        ranked_queries = ranked_queries.join(
            popularities_joined,
            (
                F.col("popularities.query")
                == F.lower(F.regexp_replace(F.trim(F.col("search_query.content")), '\\s+', ' '))
            ),
            "left",
        )
        ranked_queries = ranked_queries.select(
            F.col("search_query.id"),
            F.col("search_query.queryset"),
            F.col("search_query.content"),
            F.col("search_query.requested_at"),
            F.col("search_query.labels"),
            F.col("search_query.is_question"),
            F.col("search_query.is_time_sensitive"),
            F.col("search_query.language"),
            F.coalesce(F.col("popularities.impression_count"), F.lit(0)).alias("impression_count"),
            F.row_number()
            .over(
                Window.partitionBy(F.lit(1)).orderBy(
                    F.coalesce(F.col("popularities.impression_count"), F.lit(0)).desc_nulls_last(),
                    F.lower(F.regexp_replace(F.trim(F.col("search_query.content")), '\\s+', ' ')).asc_nulls_first(),
                    F.col("search_query.id").asc_nulls_first(),
                )
            )
            .cast(T.LongType())
            .alias("popularity_rank"),
        )
        assert_schema(ranked_queries, POPULAR_QUERY_CANDIDATE_SCHEMA, name="PopularQueryCandidate", mode="strict")

        # Step method: select_queries
        selected_queries = ranked_queries.alias("popular_query_candidate")
        selected_queries = selected_queries.where(((F.col("popular_query_candidate.popularity_rank") <= F.lit(1000))))
        selected_queries = selected_queries.select(
            F.col("popular_query_candidate.id"),
            F.col("popular_query_candidate.queryset"),
            F.col("popular_query_candidate.content"),
            F.col("popular_query_candidate.requested_at"),
            F.col("popular_query_candidate.labels"),
            F.col("popular_query_candidate.is_question"),
            F.col("popular_query_candidate.is_time_sensitive"),
            F.col("popular_query_candidate.language"),
        )

        # Step method: selected_queries
        selected_queries = selected_queries.alias("search_query")
        assert_schema(selected_queries, SEARCH_QUERY_SCHEMA, name="SearchQuery", mode="strict")
        return TransformResult(
            {"selected_queries": selected_queries}, single=True, schema={"selected_queries": SEARCH_QUERY_SCHEMA}
        )
