from structure import Schema
from structure.platform.pyspark.dsl.field import *


class OrderRevenueRollup(Schema):
    tenant_id = string(nullable=True)
    product_category = string(nullable=True)
    order_date = date(nullable=True)
    grouping_id = integer(nullable=False)
    category_subtotal = boolean(nullable=True)
    order_count = long(nullable=False)
    large_order_count = long(nullable=False)
    large_units = long(nullable=True)
    any_large_order = boolean(nullable=True)
    all_large_orders = boolean(nullable=True)
    quantity_stddev = double(nullable=True)
    quantity_variance = double(nullable=True)
    quantity_median = long(nullable=True)
    quantity_total = long(nullable=False)
    quantity_price_corr = double(nullable=True)
    quantity_price_covar = double(nullable=True)
    estimated_customers = long(nullable=False)
    first_customer_id = string(nullable=True)
    last_customer_id = string(nullable=True)
    customer_ids = array(string(), contains_null=False, nullable=True)
    order_ids = array(string(), contains_null=False, nullable=True)


class OrderProductCube(Schema):
    tenant_id = string(nullable=True)
    product_category = string(nullable=True)
    customer_tier = string(nullable=True)
    grouping_id = integer(nullable=False)
    order_count = long(nullable=False)
    distinct_customers = long(nullable=False)
    gross_total = decimal(22, 2, nullable=False)


class OrderCustomerWindow(Schema):
    tenant_id = string(nullable=False)
    customer_id = string(nullable=False)
    order_id = string(nullable=False)
    quantity = long(nullable=False)
    percent_rank = double(nullable=False)
    cume_dist = double(nullable=False)
    quantity_tile = integer(nullable=False)
    first_order_id = string(nullable=True)
    last_order_id = string(nullable=True)
    second_order_id = string(nullable=True)
    running_units = long(nullable=False)
    running_avg_units = double(nullable=True)
    running_min_units = long(nullable=False)
    running_max_units = long(nullable=False)
    running_order_count = long(nullable=False)


class OrderCollectionSource(Schema):
    id = string(nullable=False)
    tags = array(string(), contains_null=False, nullable=True)
    extra_tags = array(string(), contains_null=False, nullable=True)
    nested_tags = array(array(string(), contains_null=False), contains_null=False, nullable=True)
    scores = array(integer(), contains_null=False, nullable=True)
    attributes = map(string(), string(), nullable=True)
    extra_attributes = map(string(), string(), nullable=True)


class OrderCollectionProfile(Schema):
    id = string(nullable=False)
    tag_count = integer(nullable=True)
    contains_priority = boolean(nullable=True)
    contains_region = boolean(nullable=True)
    default_tags = array(string(), contains_null=False, nullable=False)
    repeated_tags = array(string(), contains_null=False, nullable=False)
    all_tags = array(string(), contains_null=False, nullable=True)
    tags_without_extra = array(string(), contains_null=False, nullable=True)
    first_tag = string(nullable=True)
    safe_tag = string(nullable=True)
    region = string(nullable=True)
    safe_region = string(nullable=True)
    normalized_tags = array(string(), contains_null=True, nullable=True)
    sorted_tags = array(string(), contains_null=False, nullable=True)
    flat_tags = array(string(), contains_null=False, nullable=True)
    score_total = integer(nullable=True)
    tag_position = long(nullable=True)
    has_priority = boolean(nullable=True)
    all_tags_present = boolean(nullable=True)
    normalized_attributes = map(string(), string(), nullable=True)
    zipped_attributes = map(string(), string(), value_contains_null=True, nullable=True)
    attribute_keys = array(string(), contains_null=False, nullable=True)
    attribute_values = array(string(), contains_null=False, nullable=True)
    roundtrip_attributes = map(string(), string(), nullable=True)
    merged_attributes = map(string(), string(), nullable=True)
