# Generated by Structure. Do not edit by hand.
# Source: testing.model.v3.orders.transforms.order

from pyspark.sql import DataFrame, SparkSession
from pyspark.sql import Window
from pyspark.sql import functions as F
from pyspark.sql import types as T
from testing.model.v3.orders.transforms.order import EnrichOrders
from testing.model.v3.structure_generated.orders.runtime.schema_assert import TransformResult, assert_schema, project_schema
from testing.model.v3.structure_generated.orders.pyspark.schemas.customer import CUSTOMER_SCHEMA
from testing.model.v3.structure_generated.orders.pyspark.schemas.order import ORDER_FULFILLMENT_SCHEMA, ORDER_NORMALIZED_SCHEMA, ORDER_PUBLISHED_SCHEMA, ORDER_RAW_SCHEMA, ORDER_WITH_CUSTOMER_SCHEMA, ORDER_WITH_PRODUCT_SCHEMA, ORDER_WITH_PROMOTION_SCHEMA
from testing.model.v3.structure_generated.orders.pyspark.schemas.product import BLOCKED_PRODUCT_SCHEMA, PRODUCT_SCHEMA
from testing.model.v3.structure_generated.orders.pyspark.schemas.promotion import PROMOTION_SCHEMA
from testing.model.v3.structure_generated.orders.pyspark.schemas.shipment import SHIPMENT_SCHEMA


STRUCTURE_ARTIFACT_FINGERPRINTS = {'testing.model.v3.orders.transforms.order.EnrichOrders': 'f86c6db2b655d219e3100682126dc9977796fc3ae8037011c31d900e6ea08cc8'}


class EnrichOrdersGenerated:

    def __init__(self, *, spark: SparkSession, ctx=None,
        orders: DataFrame,
        customers: DataFrame,
        products: DataFrame,
        blocked_products: DataFrame,
        promotions: DataFrame,
        shipments: DataFrame,
    ):
        self.spark = spark
        self.ctx = ctx
        self._ran = False
        self._input_orders = orders
        self._input_customers = customers
        self._input_products = products
        self._input_blocked_products = blocked_products
        self._input_promotions = promotions
        self._input_shipments = shipments
        self._impl = EnrichOrders()

    def normalize(self):
        # Step method: normalize
        orders = self.use_current_orders(orders=self._input_orders, spark=self.spark, ctx=self.ctx)
        orders = self.orders.alias("order_raw")
        orders = orders.where((F.col("order_raw.id").isNotNull()) & (F.col("order_raw.customer_id").isNotNull()) & (F.col("order_raw.product_id").isNotNull()))
        orders = orders.select(
            F.col("order_raw.tenant"),
            F.col("order_raw.audit"),
            F.col("order_raw.business"),
            F.lower(F.trim(F.col("order_raw.id"))).alias("id"),
            F.lower(F.trim(F.col("order_raw.customer_id"))).alias("customer_id"),
            F.lower(F.trim(F.col("order_raw.product_id"))).alias("product_id"),
            F.lower(F.trim(F.col("order_raw.promo-code"))).alias("promotion_code"),
            F.coalesce(F.col("order_raw.total").cast("decimal(12,2)"), F.lit(0)).alias("total"),
            F.coalesce(F.col("order_raw.discount").cast("decimal(12,2)"), F.lit(0)).alias("discount"),
            (F.coalesce(F.col("order_raw.total").cast("decimal(12,2)"), F.lit(0)) - F.coalesce(F.col("order_raw.discount").cast("decimal(12,2)"), F.lit(0))).cast(T.DecimalType(12, 2)).alias("net_total"),
            F.coalesce(F.col("order_raw.quantity"), F.lit(1)).cast(T.LongType()).alias("quantity"),
            F.filter(F.transform(F.col("order_raw.tags"), lambda item: F.lower(F.trim(item))), lambda item: item.isNotNull()).alias("tags"),
            F.map_filter(F.transform_values(F.col("order_raw.attributes"), lambda key, value: F.lower(F.trim(value))), lambda key, value: value.isNotNull()).alias("attributes"),
            F.col("order_raw.shipping"),
            (F.coalesce(F.col("order_raw.total").cast("decimal(12,2)"), F.lit(0)) > F.lit(1000)).alias("is_large"),
        )
        orders = self.remove_negative_totals(orders=orders, spark=self.spark, ctx=self.ctx)
        assert_schema(orders, ORDER_NORMALIZED_SCHEMA, name="OrderNormalized", mode="strict")
        assert_schema(orders, ORDER_NORMALIZED_SCHEMA, name="OrderNormalized", mode="strict")
        self.orders = orders

    def add_customer(self):
        # Step method: add_customer
        orders = self.orders.alias("order_normalized")
        customers_joined = F.broadcast(self.customers.alias("customers"))
        orders = orders.join(
            customers_joined,
            ((F.col("customers.tenant.tenant_id") == F.col("order_normalized.tenant.tenant_id")) & (F.lower(F.trim(F.col("customers.id"))) == F.col("order_normalized.customer_id"))),
            "left",
        )
        orders = orders.select(
            F.col("order_normalized.tenant"),
            F.col("order_normalized.audit"),
            F.col("order_normalized.business"),
            F.col("order_normalized.id"),
            F.col("order_normalized.customer_id"),
            F.col("order_normalized.product_id"),
            F.col("order_normalized.promotion_code"),
            F.col("order_normalized.total"),
            F.col("order_normalized.discount"),
            F.col("order_normalized.net_total"),
            F.col("order_normalized.quantity"),
            F.col("order_normalized.tags"),
            F.col("order_normalized.attributes"),
            F.col("order_normalized.shipping"),
            F.col("order_normalized.is_large"),
            F.col("customers.name").alias("customer_name"),
            F.col("customers.tier").alias("customer_tier"),
            F.col("customers.region").alias("customer_region"),
        )
        assert_schema(orders, ORDER_WITH_CUSTOMER_SCHEMA, name="OrderWithCustomer", mode="strict")
        orders = orders.persist()
        self.orders = orders

    def add_product(self):
        # Step method: add_product
        orders = self.orders.alias("order_with_customer")
        products_joined = self.products.alias("products")
        orders = orders.join(
            products_joined,
            ((F.col("products.tenant.tenant_id") == F.col("order_with_customer.tenant.tenant_id")) & (F.col("products.id") == F.col("order_with_customer.product_id"))),
            "left_semi",
        )
        blocked_products_2_joined = self.blocked_products.alias("blocked_products_2")
        orders = orders.join(
            blocked_products_2_joined,
            ((F.col("blocked_products_2.tenant.tenant_id") == F.col("order_with_customer.tenant.tenant_id")) & (F.col("blocked_products_2.id") == F.col("order_with_customer.product_id"))),
            "left_anti",
        )
        products_3_joined = self.products.alias("products_3").withColumn("__structure_products_3_rank", F.row_number().over(Window.partitionBy(F.col("products_3.tenant.tenant_id"), F.col("products_3.id")).orderBy(F.col("products_3.audit.ingested_at").desc()))).where(F.col("__structure_products_3_rank") == F.lit(1)).drop("__structure_products_3_rank").alias("products_3")
        orders = orders.join(
            products_3_joined,
            ((F.col("products_3.tenant.tenant_id") == F.col("order_with_customer.tenant.tenant_id")) & (F.col("products_3.id") == F.col("order_with_customer.product_id"))),
            "left",
        )
        orders = orders.where((F.col("products_3.id").isNotNull()))
        orders = orders.select(
            F.col("order_with_customer.tenant"),
            F.col("order_with_customer.audit"),
            F.col("order_with_customer.business"),
            F.col("order_with_customer.id"),
            F.col("order_with_customer.customer_id"),
            F.col("order_with_customer.product_id"),
            F.col("order_with_customer.promotion_code"),
            F.col("order_with_customer.total"),
            F.col("order_with_customer.discount"),
            F.col("order_with_customer.net_total"),
            F.col("order_with_customer.quantity"),
            F.col("order_with_customer.tags"),
            F.col("order_with_customer.attributes"),
            F.col("order_with_customer.shipping"),
            F.col("order_with_customer.is_large"),
            F.col("order_with_customer.customer_name"),
            F.col("order_with_customer.customer_tier"),
            F.col("order_with_customer.customer_region"),
            F.col("products_3.name").alias("product_name"),
            F.col("products_3.category").alias("product_category"),
            F.col("products_3.active").alias("product_active"),
            F.col("products_3.list_price").alias("product_list_price"),
        )
        assert_schema(orders, ORDER_WITH_PRODUCT_SCHEMA, name="OrderWithProduct", mode="strict")
        self.orders = orders

    def add_promotion(self):
        # Step method: add_promotion
        orders = self.orders.alias("order_with_product")
        promotions_joined = self.promotions.alias("promotions")
        orders = orders.join(
            promotions_joined,
            (((F.col("promotions.tenant.tenant_id") == F.col("order_with_product.tenant.tenant_id")) & F.lower(F.trim(F.col("promotions.code"))).eqNullSafe(F.col("order_with_product.promotion_code"))) & ((F.col("promotions.valid_from") <= F.col("order_with_product.business.order_date")) & ((F.col("order_with_product.business.order_date") < F.col("promotions.valid_to")) | F.col("promotions.valid_to").isNull()))),
            "left",
        )
        orders = orders.select(
            F.col("order_with_product.tenant"),
            F.col("order_with_product.audit"),
            F.col("order_with_product.business"),
            F.col("order_with_product.id"),
            F.col("order_with_product.customer_id"),
            F.col("order_with_product.product_id"),
            F.col("order_with_product.promotion_code"),
            F.col("order_with_product.total"),
            F.col("order_with_product.discount"),
            F.col("order_with_product.net_total"),
            F.col("order_with_product.quantity"),
            F.col("order_with_product.tags"),
            F.col("order_with_product.attributes"),
            F.col("order_with_product.shipping"),
            F.col("order_with_product.is_large"),
            F.col("order_with_product.customer_name"),
            F.col("order_with_product.customer_tier"),
            F.col("order_with_product.customer_region"),
            F.col("order_with_product.product_name"),
            F.col("order_with_product.product_category"),
            F.col("order_with_product.product_active"),
            F.col("order_with_product.product_list_price"),
            F.col("promotions.name").alias("promotion_name"),
            F.col("promotions.discount").alias("promotion_discount"),
        )
        assert_schema(orders, ORDER_WITH_PROMOTION_SCHEMA, name="OrderWithPromotion", mode="strict")
        self.orders = orders

    def add_shipments(self):
        # Step method: add_shipments
        orders = self.orders.alias("order_with_promotion")
        shipments_joined = self.shipments.hint("shuffle_hash").alias("shipments")
        orders = orders.join(
            shipments_joined,
            ((F.col("shipments.tenant.tenant_id") == F.col("order_with_promotion.tenant.tenant_id")) & (F.col("shipments.order_id") == F.col("order_with_promotion.id"))),
            "inner",
        )
        orders = orders.select(
            F.col("order_with_promotion.tenant"),
            F.col("order_with_promotion.audit"),
            F.col("order_with_promotion.business"),
            F.col("order_with_promotion.id"),
            F.col("order_with_promotion.customer_id"),
            F.col("order_with_promotion.product_id"),
            F.col("order_with_promotion.promotion_code"),
            F.col("order_with_promotion.total"),
            F.col("order_with_promotion.discount"),
            F.col("order_with_promotion.net_total"),
            F.col("order_with_promotion.quantity"),
            F.col("order_with_promotion.tags"),
            F.col("order_with_promotion.attributes"),
            F.col("order_with_promotion.shipping"),
            F.col("order_with_promotion.is_large"),
            F.col("order_with_promotion.customer_name"),
            F.col("order_with_promotion.customer_tier"),
            F.col("order_with_promotion.customer_region"),
            F.col("order_with_promotion.product_name"),
            F.col("order_with_promotion.product_category"),
            F.col("order_with_promotion.product_active"),
            F.col("order_with_promotion.product_list_price"),
            F.col("order_with_promotion.promotion_name"),
            F.col("order_with_promotion.promotion_discount"),
            F.col("shipments.line_number").alias("shipment_line"),
            F.col("shipments.carrier"),
            F.col("shipments.tracking_number"),
            F.col("shipments.shipped_at"),
        )
        orders = self.note_lookup_inputs(orders=orders, customers=self._input_customers, products=self._input_products, spark=self.spark, ctx=self.ctx)
        assert_schema(orders, ORDER_FULFILLMENT_SCHEMA, name="OrderFulfillment", mode="allow_extra_columns")
        assert_schema(orders, ORDER_FULFILLMENT_SCHEMA, name="OrderFulfillment", mode="allow_extra_columns")
        self.orders = orders

    def publish(self):
        # Step method: publish
        published = self.orders.alias("order_fulfillment")
        published = published.select(
            F.col("order_fulfillment.tenant"),
            F.col("order_fulfillment.business"),
            F.col("order_fulfillment.id"),
            F.col("order_fulfillment.customer_id"),
            F.col("order_fulfillment.customer_name"),
            F.col("order_fulfillment.customer_tier"),
            F.col("order_fulfillment.product_name"),
            F.col("order_fulfillment.product_category"),
            F.col("order_fulfillment.promotion_name"),
            F.col("order_fulfillment.total"),
            F.col("order_fulfillment.discount"),
            F.col("order_fulfillment.net_total"),
            F.col("order_fulfillment.quantity"),
            F.col("order_fulfillment.carrier"),
            F.col("order_fulfillment.tracking_number"),
            F.col("order_fulfillment.shipped_at"),
            F.col("order_fulfillment.is_large"),
            F.col("order_fulfillment.promotion_name").isNotNull().alias("has_promotion"),
        )
        published = self.add_quality_columns(published=published, spark=self.spark, ctx=self.ctx)
        assert_schema(published, ORDER_PUBLISHED_SCHEMA, name="OrderPublished", mode="allow_extra_columns")
        published = project_schema(published, ORDER_PUBLISHED_SCHEMA)
        assert_schema(published, ORDER_PUBLISHED_SCHEMA, name="OrderPublished", mode="strict")
        self.published = published

    def run(self) -> TransformResult:
        if self._ran:
            raise RuntimeError("A mirrored generated transform instance can run only once.")
        self._ran = True
        self.orders = self._input_orders
        assert_schema(self.orders, ORDER_RAW_SCHEMA, name="OrderRaw", mode="strict")
        self.customers = self._input_customers
        assert_schema(self.customers, CUSTOMER_SCHEMA, name="Customer", mode="strict")
        self.products = self._input_products
        assert_schema(self.products, PRODUCT_SCHEMA, name="Product", mode="strict")
        self.blocked_products = self._input_blocked_products
        assert_schema(self.blocked_products, BLOCKED_PRODUCT_SCHEMA, name="BlockedProduct", mode="strict")
        self.promotions = self._input_promotions
        assert_schema(self.promotions, PROMOTION_SCHEMA, name="Promotion", mode="strict")
        self.shipments = self._input_shipments
        assert_schema(self.shipments, SHIPMENT_SCHEMA, name="Shipment", mode="strict")
        self.normalize()
        self.add_customer()
        self.add_product()
        self.add_promotion()
        self.add_shipments()
        self.publish()

        # Step method: published
        published = self.published.alias("order_published")
        assert_schema(published, ORDER_PUBLISHED_SCHEMA, name="OrderPublished", mode="strict")
        self.published = published
        return TransformResult({"published": self.published}, single=True, schema={"published": ORDER_PUBLISHED_SCHEMA})

    def use_current_orders(self, *, orders, spark, ctx):
        return self._impl.use_current_orders(orders=orders, spark=spark, ctx=ctx)

    def remove_negative_totals(self, *, orders, spark, ctx):
        return self._impl.remove_negative_totals(orders=orders, spark=spark, ctx=ctx)

    def note_lookup_inputs(self, *, orders, customers, products, spark, ctx):
        return self._impl.note_lookup_inputs(orders=orders, customers=customers, products=products, spark=spark, ctx=ctx)

    def add_quality_columns(self, *, published, spark, ctx):
        return self._impl.add_quality_columns(published=published, spark=spark, ctx=ctx)
