# Generated by Structure. Do not edit by hand.
# Source: examples.store.transforms.recommender.signals.purchases.BuildPurchaseSignals

from __future__ import annotations
import datetime
from pyspark.sql import DataFrame, SparkSession
from pyspark.sql import functions as F
from pyspark.sql import types as T
from examples.structure_generated.store.runtime.schema_assert import (
    TransformResult,
    assert_schema,
    project_schema,
    apply_plan_boundary,
    close_plan_boundaries,
)
from examples.structure_generated.store.pyspark.schemas.feedback import (
    RECOMMENDATION_IMPRESSION_SCHEMA,
    RECOMMENDATION_PURCHASE_SCHEMA,
)
from examples.structure_generated.store.pyspark.schemas.order import ORDER_FULFILLMENT_SCHEMA


class BuildPurchaseSignalsGenerated:

    def __init__(self, *, spark: SparkSession, ctx=None):
        self.spark = spark
        self.ctx = ctx

    def close(self) -> None:
        close_plan_boundaries(self.spark)

    def run(
        self,
        *,
        fulfilled_orders: DataFrame,
        impressions: DataFrame,
    ) -> TransformResult:
        assert_schema(fulfilled_orders, ORDER_FULFILLMENT_SCHEMA, name="OrderFulfillment", mode="strict")
        assert_schema(impressions, RECOMMENDATION_IMPRESSION_SCHEMA, name="RecommendationImpression", mode="strict")
        _input_fulfilled_orders = fulfilled_orders
        _input_impressions = impressions

        # Step method: attribute
        fulfilled_orders = fulfilled_orders.alias("order_fulfillment")
        impressions_joined = impressions.alias("impressions")
        fulfilled_orders = fulfilled_orders.join(
            impressions_joined,
            (
                (
                    (
                        (F.col("impressions.tenant.tenant_id") == F.col("order_fulfillment.tenant.tenant_id"))
                        & (F.col("impressions.product_id") == F.col("order_fulfillment.product_id"))
                    )
                    & F.col("impressions.customer_id").eqNullSafe(F.col("order_fulfillment.customer_id"))
                )
                & (
                    (
                        F.coalesce(
                            F.col("order_fulfillment.shipped_at"),
                            F.to_timestamp(F.col("order_fulfillment.business.order_date")),
                            F.lit(datetime.datetime(1970, 1, 1, 0, 0, tzinfo=datetime.timezone.utc)),
                        )
                        >= (F.col("impressions.shown_at") - F.expr("INTERVAL 0 seconds"))
                    )
                    & (
                        F.coalesce(
                            F.col("order_fulfillment.shipped_at"),
                            F.to_timestamp(F.col("order_fulfillment.business.order_date")),
                            F.lit(datetime.datetime(1970, 1, 1, 0, 0, tzinfo=datetime.timezone.utc)),
                        )
                        <= (F.col("impressions.shown_at") + F.expr("INTERVAL 30 days"))
                    )
                )
            ),
            "left",
        )
        fulfilled_orders = fulfilled_orders.select(
            F.col("order_fulfillment.tenant"),
            F.col("order_fulfillment.id").alias("order_id"),
            F.col("impressions.request_id"),
            F.col("order_fulfillment.customer_id"),
            F.col("impressions.session_id"),
            F.col("order_fulfillment.product_id"),
            F.col("impressions.id").alias("recommendation_impression_id"),
            F.coalesce(
                F.col("order_fulfillment.shipped_at"),
                F.to_timestamp(F.col("order_fulfillment.business.order_date")),
                F.lit(datetime.datetime(1970, 1, 1, 0, 0, tzinfo=datetime.timezone.utc)),
            ).alias("occurred_at"),
            F.when(F.col("impressions.id").isNotNull(), F.lit('attributed'))
            .otherwise(F.lit('unattributed'))
            .alias("attribution_status"),
            F.col("order_fulfillment.quantity"),
        )

        # Step method: purchases
        purchases = fulfilled_orders.alias("recommendation_purchase")
        assert_schema(purchases, RECOMMENDATION_PURCHASE_SCHEMA, name="RecommendationPurchase", mode="strict")
        return TransformResult(
            {"purchases": purchases}, single=True, schema={"purchases": RECOMMENDATION_PURCHASE_SCHEMA}
        )
