# Generated by Structure. Do not edit by hand.
# Source: examples.search.transforms.analyze.AnalyzeText

from __future__ import annotations
from pyspark.sql import DataFrame, SparkSession
from pyspark.sql import functions as F
from pyspark.sql import types as T
from examples.structure_generated.search.runtime.schema_assert import TransformResult, assert_schema, project_schema
from examples.structure_generated.search.pyspark.schemas.analytics import (
    DOCUMENT_PROFILE_SCHEMA,
    DOCUMENT_STATISTICS_SCHEMA,
    PARAGRAPH_STATISTICS_SCHEMA,
    SECTION_STATISTICS_SCHEMA,
    SENTENCE_STATISTICS_SCHEMA,
    SIMILAR_DOCUMENT_SCHEMA,
)
from examples.structure_generated.search.pyspark.schemas.text import (
    PARAGRAPH_SCHEMA,
    SECTION_SCHEMA,
    SENTENCE_SCHEMA,
    WORD_SCHEMA,
)


class AnalyzeTextGenerated:

    def __init__(self, *, spark: SparkSession, ctx=None):
        self.spark = spark
        self.ctx = ctx

    def run(
        self,
        *,
        words: DataFrame,
        sentences: DataFrame,
        paragraphs: DataFrame,
        sections: DataFrame,
        comparison_left: DataFrame,
        comparison_right: DataFrame,
    ) -> TransformResult:
        assert_schema(words, WORD_SCHEMA, name="Word", mode="strict")
        assert_schema(sentences, SENTENCE_SCHEMA, name="Sentence", mode="strict")
        assert_schema(paragraphs, PARAGRAPH_SCHEMA, name="Paragraph", mode="strict")
        assert_schema(sections, SECTION_SCHEMA, name="Section", mode="strict")
        assert_schema(comparison_left, DOCUMENT_PROFILE_SCHEMA, name="DocumentProfile", mode="strict")
        assert_schema(comparison_right, DOCUMENT_PROFILE_SCHEMA, name="DocumentProfile", mode="strict")
        _input_words = words
        _input_sentences = sentences
        _input_paragraphs = paragraphs
        _input_sections = sections
        _input_comparison_left = comparison_left
        _input_comparison_right = comparison_right

        # Step method: sentence_stats
        sentence_statistics = words.alias("word")
        sentences_joined = sentences.alias("sentences")
        sentence_statistics = sentence_statistics.join(
            sentences_joined,
            (F.col("word.sentence_id") == F.col("sentences.id")),
            "inner",
        )
        sentence_statistics = (
            sentence_statistics.groupBy(
                F.col("sentences.id").alias("sentence_id"),
                F.col("sentences.document_id").alias("document_id"),
                F.col("sentences.paragraph_id").alias("paragraph_id"),
                F.col("sentences.section_id").alias("section_id"),
                F.col("sentences.ordinal").alias("ordinal"),
            )
            .agg(
                F.count(F.lit(1)).cast(T.LongType()).alias("word_count"),
                F.countDistinct(F.col("word.token")).cast(T.LongType()).alias("distinct_words"),
                F.avg(F.length(F.col("word.token"))).cast(T.DoubleType()).alias("average_word_length"),
            )
            .select(
                F.col("sentence_id"),
                F.col("document_id"),
                F.col("paragraph_id"),
                F.col("section_id"),
                F.col("ordinal"),
                F.col("word_count"),
                F.col("distinct_words"),
                F.col("average_word_length"),
            )
        )
        assert_schema(sentence_statistics, SENTENCE_STATISTICS_SCHEMA, name="SentenceStatistics", mode="strict")

        # Step method: paragraph_stats
        paragraph_statistics = words.alias("word")
        paragraph_statistics = (
            paragraph_statistics.groupBy(
                F.col("word.paragraph_id").alias("paragraph_id"),
                F.col("word.document_id").alias("document_id"),
                F.col("word.section_id").alias("section_id"),
            )
            .agg(
                F.min(F.col("word.paragraph_ordinal")).cast(T.IntegerType()).alias("ordinal"),
                F.count(F.lit(1)).cast(T.LongType()).alias("word_count"),
                F.countDistinct(F.col("word.sentence_id")).cast(T.LongType()).alias("sentence_count"),
                F.avg(F.length(F.col("word.token"))).cast(T.DoubleType()).alias("average_word_length"),
            )
            .select(
                F.col("paragraph_id"),
                F.col("document_id"),
                F.col("section_id"),
                F.col("ordinal"),
                F.col("word_count"),
                F.col("sentence_count"),
                F.col("average_word_length"),
            )
        )
        assert_schema(paragraph_statistics, PARAGRAPH_STATISTICS_SCHEMA, name="ParagraphStatistics", mode="strict")

        # Step method: section_stats
        section_statistics = words.alias("word")
        sections_joined = sections.alias("sections")
        section_statistics = section_statistics.join(
            sections_joined,
            (F.col("word.section_id") == F.col("sections.id")),
            "inner",
        )
        section_statistics = (
            section_statistics.groupBy(
                F.col("sections.id").alias("section_id"),
                F.col("sections.document_id").alias("document_id"),
                F.col("sections.ordinal").alias("section_ordinal"),
                F.col("sections.heading").alias("heading"),
            )
            .agg(
                F.countDistinct(F.col("word.paragraph_id")).cast(T.LongType()).alias("paragraph_count"),
                F.countDistinct(F.col("word.sentence_id")).cast(T.LongType()).alias("sentence_count"),
                F.count(F.lit(1)).cast(T.LongType()).alias("word_count"),
                F.avg(F.length(F.col("word.token"))).cast(T.DoubleType()).alias("average_word_length"),
            )
            .select(
                F.col("section_id"),
                F.col("document_id"),
                F.col("section_ordinal"),
                F.col("heading"),
                F.col("paragraph_count"),
                F.col("sentence_count"),
                F.col("word_count"),
                F.col("average_word_length"),
            )
        )
        assert_schema(section_statistics, SECTION_STATISTICS_SCHEMA, name="SectionStatistics", mode="strict")

        # Step method: document_stats
        document_statistics = words.alias("word")
        document_statistics = (
            document_statistics.groupBy(
                F.col("word.document_id").alias("document_id"),
            )
            .agg(
                F.countDistinct(F.col("word.section_id")).cast(T.LongType()).alias("section_count"),
                F.countDistinct(F.col("word.paragraph_id")).cast(T.LongType()).alias("paragraph_count"),
                F.countDistinct(F.col("word.sentence_id")).cast(T.LongType()).alias("sentence_count"),
                F.count(F.lit(1)).cast(T.LongType()).alias("word_count"),
                F.countDistinct(F.col("word.token")).cast(T.LongType()).alias("distinct_words"),
                F.avg(F.length(F.col("word.token"))).cast(T.DoubleType()).alias("average_word_length"),
            )
            .select(
                F.col("document_id"),
                F.col("section_count"),
                F.col("paragraph_count"),
                F.col("sentence_count"),
                F.col("word_count"),
                F.col("distinct_words"),
                F.col("average_word_length"),
            )
        )
        assert_schema(document_statistics, DOCUMENT_STATISTICS_SCHEMA, name="DocumentStatistics", mode="strict")

        # Step method: similar
        similar_documents = comparison_left.alias("document_profile")
        comparison_right_joined = comparison_right.alias("comparison_right")
        similar_documents = similar_documents.join(
            comparison_right_joined,
            (
                (
                    (F.col("document_profile.source") == F.col("comparison_right.source"))
                    & (F.col("document_profile.language") == F.col("comparison_right.language"))
                )
                & (F.col("document_profile.title_prefix") == F.col("comparison_right.title_prefix"))
            ),
            "inner",
        )
        similar_documents = similar_documents.where(
            ((F.col("document_profile.document_id") < F.col("comparison_right.document_id")))
        )
        similar_documents = similar_documents.select(
            F.col("document_profile.document_id").alias("left_document_id"),
            F.col("comparison_right.document_id").alias("right_document_id"),
            F.col("document_profile.source"),
            F.col("document_profile.language"),
            F.col("document_profile.title_prefix"),
            F.levenshtein(F.col("document_profile.title"), F.col("comparison_right.title")).alias("title_distance"),
            F.levenshtein(
                F.col("document_profile.normalized_content"), F.col("comparison_right.normalized_content")
            ).alias("content_distance"),
        )

        # Step method: sentence_statistics
        sentence_statistics = sentence_statistics.alias("sentence_statistics")
        assert_schema(sentence_statistics, SENTENCE_STATISTICS_SCHEMA, name="SentenceStatistics", mode="strict")

        # Step method: paragraph_statistics
        paragraph_statistics = paragraph_statistics.alias("paragraph_statistics")
        assert_schema(paragraph_statistics, PARAGRAPH_STATISTICS_SCHEMA, name="ParagraphStatistics", mode="strict")

        # Step method: section_statistics
        section_statistics = section_statistics.alias("section_statistics")
        assert_schema(section_statistics, SECTION_STATISTICS_SCHEMA, name="SectionStatistics", mode="strict")

        # Step method: document_statistics
        document_statistics = document_statistics.alias("document_statistics")
        assert_schema(document_statistics, DOCUMENT_STATISTICS_SCHEMA, name="DocumentStatistics", mode="strict")

        # Step method: similar_documents
        similar_documents = similar_documents.alias("similar_document")
        assert_schema(similar_documents, SIMILAR_DOCUMENT_SCHEMA, name="SimilarDocument", mode="strict")
        return TransformResult(
            {
                "sentence_statistics": sentence_statistics,
                "paragraph_statistics": paragraph_statistics,
                "section_statistics": section_statistics,
                "document_statistics": document_statistics,
                "similar_documents": similar_documents,
            },
            single=False,
            schema={
                "sentence_statistics": SENTENCE_STATISTICS_SCHEMA,
                "paragraph_statistics": PARAGRAPH_STATISTICS_SCHEMA,
                "section_statistics": SECTION_STATISTICS_SCHEMA,
                "document_statistics": DOCUMENT_STATISTICS_SCHEMA,
                "similar_documents": SIMILAR_DOCUMENT_SCHEMA,
            },
        )
