# Generated by Structure. Do not edit by hand.
# Source: examples.search.transforms.features.BuildQueryFeatures

from __future__ import annotations
from pyspark.sql import DataFrame, SparkSession
from pyspark.sql import functions as F
from pyspark.sql import types as T
from examples.structure_generated.search.runtime.schema_assert import TransformResult, assert_schema, project_schema
from examples.structure_generated.search.pyspark.schemas.features import (
    EXPANDED_QUERY_FEATURE_TOKEN_SCHEMA,
    QUERY_FEATURES_SCHEMA,
    QUERY_FEATURE_TOKEN_SCHEMA,
    QUERY_TOKEN_SUMMARY_SCHEMA,
)
from examples.structure_generated.search.pyspark.schemas.search import SEARCH_QUERY_SCHEMA


class BuildQueryFeaturesGenerated:

    def __init__(self, *, spark: SparkSession, ctx=None):
        self.spark = spark
        self.ctx = ctx

    def run(
        self,
        *,
        queries: DataFrame,
    ) -> TransformResult:
        assert_schema(queries, SEARCH_QUERY_SCHEMA, name="SearchQuery", mode="strict")
        _input_queries = queries

        # Step method: expand_tokens
        expanded_query_tokens = queries.alias("search_query")
        expanded_query_tokens = expanded_query_tokens.select(
            "*",
            F.posexplode(
                F.transform(
                    F.split(F.trim(F.col("search_query.content")), '\\s+', -1),
                    lambda item: F.struct(
                        F.col("search_query.id").alias("query_id"),
                        F.lower(F.regexp_replace(F.trim(item), '^[^A-Za-z0-9]+|[^A-Za-z0-9]+$', '')).alias("token"),
                    ),
                )
            ).alias("__structure_query_feature_token_1_pos", "__structure_query_feature_token_1_item"),
        )
        expanded_query_tokens = expanded_query_tokens.withColumn(
            "ordinal",
            F.col("__structure_query_feature_token_1_pos").cast(T.LongType()),
        )
        expanded_query_tokens = expanded_query_tokens.withColumn(
            "query_id",
            F.col("__structure_query_feature_token_1_item.query_id"),
        )
        expanded_query_tokens = expanded_query_tokens.withColumn(
            "token",
            F.col("__structure_query_feature_token_1_item.token"),
        )
        expanded_query_tokens = expanded_query_tokens.drop(
            "__structure_query_feature_token_1_pos", "__structure_query_feature_token_1_item"
        )
        expanded_query_tokens = expanded_query_tokens.where(((F.col("token") != F.lit(''))))
        expanded_query_tokens = expanded_query_tokens.select(
            F.col("query_id"),
            F.col("token"),
            F.col("ordinal"),
        )
        assert_schema(
            expanded_query_tokens, EXPANDED_QUERY_FEATURE_TOKEN_SCHEMA, name="ExpandedQueryFeatureToken", mode="strict"
        )

        # Step method: select_tokens
        query_tokens = expanded_query_tokens.alias("expanded_query_feature_token")
        query_tokens = query_tokens.select(
            F.col("expanded_query_feature_token.query_id"),
            F.col("expanded_query_feature_token.token"),
        )
        assert_schema(query_tokens, QUERY_FEATURE_TOKEN_SCHEMA, name="QueryFeatureToken", mode="strict")

        # Step method: summarize
        query_token_summaries = query_tokens.alias("query_feature_token")
        query_token_summaries = (
            query_token_summaries.groupBy(
                F.col("query_feature_token.query_id").alias("query_id"),
            )
            .agg(
                F.count(F.lit(1)).cast(T.LongType()).alias("token_count"),
                F.countDistinct(F.col("query_feature_token.token")).cast(T.LongType()).alias("distinct_token_count"),
            )
            .select(
                F.col("query_id"),
                F.col("token_count"),
                F.col("distinct_token_count"),
            )
        )
        assert_schema(query_token_summaries, QUERY_TOKEN_SUMMARY_SCHEMA, name="QueryTokenSummary", mode="strict")

        # Step method: build
        query_features = queries.alias("search_query")
        query_token_summaries_joined = query_token_summaries.alias("query_token_summaries")
        query_features = query_features.join(
            query_token_summaries_joined,
            (F.col("query_token_summaries.query_id") == F.col("search_query.id")),
            "left",
        )
        query_features = query_features.select(
            F.col("search_query.id").alias("query_id"),
            F.col("search_query.queryset"),
            F.col("search_query.language"),
            F.lower(F.regexp_replace(F.trim(F.col("search_query.content")), '\\s+', ' ')).alias("normalized_content"),
            F.coalesce(F.col("query_token_summaries.token_count"), F.lit(0)).alias("token_count"),
            F.coalesce(F.col("query_token_summaries.distinct_token_count"), F.lit(0)).alias("distinct_token_count"),
            F.col("search_query.is_question"),
            F.col("search_query.is_time_sensitive"),
        )

        # Step method: query_features
        query_features = query_features.alias("query_features")
        assert_schema(query_features, QUERY_FEATURES_SCHEMA, name="QueryFeatures", mode="strict")
        return TransformResult(
            {"query_features": query_features}, single=True, schema={"query_features": QUERY_FEATURES_SCHEMA}
        )
