# Generated by Structure. Do not edit by hand.
# Source: examples.search.transforms.similarities.ReduceSimilarityScores.ReduceSimilarityScores

from pyspark.sql import DataFrame, SparkSession
from pyspark.sql import functions as F
from pyspark.sql import types as T
from examples.search.transforms.similarities.ReduceSimilarityScores import ReduceSimilarityScores
from examples.structure_generated.search.runtime.schema_assert import TransformResult, assert_schema, project_schema
from examples.structure_generated.search.pyspark.schemas.search import DOCUMENT_BM25_SCORE_SCHEMA, DOCUMENT_OVERLAP_SCORE_SCHEMA, PARAGRAPH_BM25_SCORE_SCHEMA, PARAGRAPH_OVERLAP_SCORE_SCHEMA, SECTION_BM25_SCORE_SCHEMA, SECTION_OVERLAP_SCORE_SCHEMA, SENTENCE_BM25_SCORE_SCHEMA, SENTENCE_OVERLAP_SCORE_SCHEMA
from examples.structure_generated.search.pyspark.schemas.similarity import DOCUMENT_SIMILARITY_QUERY_SCHEMA, DOCUMENT_SIMILARITY_SCHEMA, PARAGRAPH_SIMILARITY_QUERY_SCHEMA, PARAGRAPH_SIMILARITY_SCHEMA, SECTION_SIMILARITY_QUERY_SCHEMA, SECTION_SIMILARITY_SCHEMA, SENTENCE_SIMILARITY_QUERY_SCHEMA, SENTENCE_SIMILARITY_SCHEMA


class ReduceSimilarityScoresGenerated:

    def __init__(self, *, spark: SparkSession, ctx=None):
        self.spark = spark
        self.ctx = ctx
        self._impl = ReduceSimilarityScores()

    def run(
        self,
        *,
        document_queries: DataFrame,
        section_queries: DataFrame,
        paragraph_queries: DataFrame,
        sentence_queries: DataFrame,
        document_overlap_scores: DataFrame,
        section_overlap_scores: DataFrame,
        paragraph_overlap_scores: DataFrame,
        sentence_overlap_scores: DataFrame,
        document_bm25_scores: DataFrame,
        section_bm25_scores: DataFrame,
        paragraph_bm25_scores: DataFrame,
        sentence_bm25_scores: DataFrame,
    ) -> TransformResult:
        assert_schema(document_queries, DOCUMENT_SIMILARITY_QUERY_SCHEMA, name="DocumentSimilarityQuery", mode="strict")
        assert_schema(section_queries, SECTION_SIMILARITY_QUERY_SCHEMA, name="SectionSimilarityQuery", mode="strict")
        assert_schema(paragraph_queries, PARAGRAPH_SIMILARITY_QUERY_SCHEMA, name="ParagraphSimilarityQuery", mode="strict")
        assert_schema(sentence_queries, SENTENCE_SIMILARITY_QUERY_SCHEMA, name="SentenceSimilarityQuery", mode="strict")
        assert_schema(document_overlap_scores, DOCUMENT_OVERLAP_SCORE_SCHEMA, name="DocumentOverlapScore", mode="strict")
        assert_schema(section_overlap_scores, SECTION_OVERLAP_SCORE_SCHEMA, name="SectionOverlapScore", mode="strict")
        assert_schema(paragraph_overlap_scores, PARAGRAPH_OVERLAP_SCORE_SCHEMA, name="ParagraphOverlapScore", mode="strict")
        assert_schema(sentence_overlap_scores, SENTENCE_OVERLAP_SCORE_SCHEMA, name="SentenceOverlapScore", mode="strict")
        assert_schema(document_bm25_scores, DOCUMENT_BM25_SCORE_SCHEMA, name="DocumentBm25Score", mode="strict")
        assert_schema(section_bm25_scores, SECTION_BM25_SCORE_SCHEMA, name="SectionBm25Score", mode="strict")
        assert_schema(paragraph_bm25_scores, PARAGRAPH_BM25_SCORE_SCHEMA, name="ParagraphBm25Score", mode="strict")
        assert_schema(sentence_bm25_scores, SENTENCE_BM25_SCORE_SCHEMA, name="SentenceBm25Score", mode="strict")
        _input_document_queries = document_queries
        _input_section_queries = section_queries
        _input_paragraph_queries = paragraph_queries
        _input_sentence_queries = sentence_queries
        _input_document_overlap_scores = document_overlap_scores
        _input_section_overlap_scores = section_overlap_scores
        _input_paragraph_overlap_scores = paragraph_overlap_scores
        _input_sentence_overlap_scores = sentence_overlap_scores
        _input_document_bm25_scores = document_bm25_scores
        _input_section_bm25_scores = section_bm25_scores
        _input_paragraph_bm25_scores = paragraph_bm25_scores
        _input_sentence_bm25_scores = sentence_bm25_scores

        # Step method: declare_similarities
        declare_similarities_base = document_queries.alias("document_similarity_query")
        document_similarities = declare_similarities_base.select(
            F.col("document_similarity_query.document_id").alias("left_document_id"),
            F.lit('').alias("right_document_id"),
            F.lit(0.0).alias("score_overlap"),
            F.lit(0.0).alias("bm25_left_to_right"),
            F.lit(0.0).alias("bm25_right_to_left"),
            F.lit(0.0).alias("bm25_mean"),
        )
        section_similarities = declare_similarities_base.select(
            F.col("document_similarity_query.document_id").alias("left_document_id"),
            F.lit('').alias("left_section_id"),
            F.lit('').alias("right_document_id"),
            F.lit('').alias("right_section_id"),
            F.lit(0.0).alias("score_overlap"),
            F.lit(0.0).alias("bm25_left_to_right"),
            F.lit(0.0).alias("bm25_right_to_left"),
            F.lit(0.0).alias("bm25_mean"),
        )
        paragraph_similarities = declare_similarities_base.select(
            F.col("document_similarity_query.document_id").alias("left_document_id"),
            F.lit('').alias("left_section_id"),
            F.lit('').alias("left_paragraph_id"),
            F.lit('').alias("right_document_id"),
            F.lit('').alias("right_section_id"),
            F.lit('').alias("right_paragraph_id"),
            F.lit(0.0).alias("score_overlap"),
            F.lit(0.0).alias("bm25_left_to_right"),
            F.lit(0.0).alias("bm25_right_to_left"),
            F.lit(0.0).alias("bm25_mean"),
        )
        sentence_similarities = declare_similarities_base.select(
            F.col("document_similarity_query.document_id").alias("left_document_id"),
            F.lit('').alias("left_section_id"),
            F.lit('').alias("left_paragraph_id"),
            F.lit('').alias("left_sentence_id"),
            F.lit('').alias("right_document_id"),
            F.lit('').alias("right_section_id"),
            F.lit('').alias("right_paragraph_id"),
            F.lit('').alias("right_sentence_id"),
            F.lit(0.0).alias("score_overlap"),
            F.lit(0.0).alias("bm25_left_to_right"),
            F.lit(0.0).alias("bm25_right_to_left"),
            F.lit(0.0).alias("bm25_mean"),
        )
        document_similarities, section_similarities, paragraph_similarities, sentence_similarities = self._impl.reduce(document_queries=_input_document_queries, section_queries=_input_section_queries, paragraph_queries=_input_paragraph_queries, sentence_queries=_input_sentence_queries, document_overlap_scores=_input_document_overlap_scores, section_overlap_scores=_input_section_overlap_scores, paragraph_overlap_scores=_input_paragraph_overlap_scores, sentence_overlap_scores=_input_sentence_overlap_scores, document_bm25_scores=_input_document_bm25_scores, section_bm25_scores=_input_section_bm25_scores, paragraph_bm25_scores=_input_paragraph_bm25_scores, sentence_bm25_scores=_input_sentence_bm25_scores, document_similarities=document_similarities, section_similarities=section_similarities, paragraph_similarities=paragraph_similarities, sentence_similarities=sentence_similarities, spark=self.spark, ctx=self.ctx)
        assert_schema(document_similarities, DOCUMENT_SIMILARITY_SCHEMA, name="DocumentSimilarity", mode="strict")

        # Step method: document_similarities
        document_similarities = document_similarities.alias("document_similarity")
        assert_schema(document_similarities, DOCUMENT_SIMILARITY_SCHEMA, name="DocumentSimilarity", mode="strict")

        # Step method: section_similarities
        section_similarities = section_similarities.alias("section_similarity")
        assert_schema(section_similarities, SECTION_SIMILARITY_SCHEMA, name="SectionSimilarity", mode="strict")

        # Step method: paragraph_similarities
        paragraph_similarities = paragraph_similarities.alias("paragraph_similarity")
        assert_schema(paragraph_similarities, PARAGRAPH_SIMILARITY_SCHEMA, name="ParagraphSimilarity", mode="strict")

        # Step method: sentence_similarities
        sentence_similarities = sentence_similarities.alias("sentence_similarity")
        assert_schema(sentence_similarities, SENTENCE_SIMILARITY_SCHEMA, name="SentenceSimilarity", mode="strict")
        return TransformResult({"document_similarities": document_similarities, "section_similarities": section_similarities, "paragraph_similarities": paragraph_similarities, "sentence_similarities": sentence_similarities}, single=False, schema={"document_similarities": DOCUMENT_SIMILARITY_SCHEMA, "section_similarities": SECTION_SIMILARITY_SCHEMA, "paragraph_similarities": PARAGRAPH_SIMILARITY_SCHEMA, "sentence_similarities": SENTENCE_SIMILARITY_SCHEMA})
