# Generated by Structure. Do not edit by hand.
# Source: examples.search.transforms.search.SearchDocuments

from pyspark.sql import DataFrame, SparkSession
from pyspark.sql import Window
from pyspark.sql import functions as F
from pyspark.sql import types as T
from examples.structure_generated.search.runtime.schema_assert import TransformResult, assert_schema, project_schema
from examples.structure_generated.search.pyspark.schemas.relevance import DOCUMENT_POPULARITY_SCHEMA, QUERY_DOCUMENT_SIGNALS_SCHEMA, RELEVANCE_POLICY_SCHEMA
from examples.structure_generated.search.pyspark.schemas.search import DOCUMENT_SCORE_SCHEMA, DOCUMENT_SEARCH_CANDIDATE_SCHEMA, DOCUMENT_SEARCH_RESULT_SCHEMA, SEARCH_QUERY_SCHEMA
from examples.structure_generated.search.pyspark.schemas.text import DOCUMENT_SCHEMA


class RetrieveDocumentsGenerated:
    def _step_select_candidates_0(self, frames):
        # Step method: select_candidates
        candidates = frames["documents"].alias("document")
        document_scores_joined = frames["document_scores"].alias("document_scores")
        candidates = candidates.join(
            document_scores_joined,
            (F.col("document.id") == F.col("document_scores.document_id")),
            "inner",
        )
        queries_2_joined = frames["queries"].alias("queries_2")
        candidates = candidates.join(
            queries_2_joined,
            (F.col("queries_2.id") == F.col("document_scores.query_id")),
            "inner",
        )
        candidates = candidates.where((F.col("document_scores.score").isNotNull()))
        candidates = candidates.select(
            F.col("queries_2.id").alias("search_query_id"),
            F.col("document_scores.experiment_id"),
            F.lower(F.regexp_replace(F.trim(F.col("queries_2.content")), '\\s+', ' ')).alias("query"),
            F.row_number().over(Window.partitionBy(F.col("queries_2.id"), F.col("document_scores.experiment_id")).orderBy(F.col("document_scores.score").desc_nulls_last(), F.col("document.id").asc_nulls_first())).cast(T.LongType()).alias("candidate_rank"),
            F.col("document.id").alias("document_id"),
            F.col("document.title"),
            F.col("document.url"),
            F.col("document_scores.score"),
            F.lit(0.0).alias("score_feedback"),
            F.lit(0.0).alias("score_rank"),
            F.lit(0.0).alias("score_weight"),
            F.lit(0.0).alias("feedback_weight"),
        )
        assert_schema(candidates, DOCUMENT_SEARCH_CANDIDATE_SCHEMA, name="DocumentSearchCandidate", mode="strict")
        return {
            "candidates": candidates,
        }


class RerankDocumentsGenerated:
    def _step_score_candidates_1(self, frames):
        # Step method: score_candidates
        scored_candidates = frames["candidates"].alias("document_search_candidate")
        scored_candidates = scored_candidates.where(((F.col("document_search_candidate.candidate_rank") <= F.lit(100))))
        query_document_signals_joined = frames["query_document_signals"].alias("query_document_signals")
        scored_candidates = scored_candidates.join(
            query_document_signals_joined,
            ((F.col("query_document_signals.query") == F.col("document_search_candidate.query")) & (F.col("query_document_signals.document_id") == F.col("document_search_candidate.document_id"))),
            "left",
        )
        document_popularity_2_joined = frames["document_popularity"].alias("document_popularity_2")
        scored_candidates = scored_candidates.join(
            document_popularity_2_joined,
            (F.col("document_popularity_2.document_id") == F.col("document_search_candidate.document_id")),
            "left",
        )
        policy_3_joined = frames["policy"].alias("policy_3")
        scored_candidates = scored_candidates.crossJoin(policy_3_joined)
        scored_candidates = scored_candidates.select(
            F.col("document_search_candidate.search_query_id"),
            F.col("document_search_candidate.experiment_id"),
            F.col("document_search_candidate.query"),
            F.col("document_search_candidate.candidate_rank"),
            F.col("document_search_candidate.document_id"),
            F.col("document_search_candidate.title"),
            F.col("document_search_candidate.url"),
            F.col("document_search_candidate.score"),
            ((F.lit(0.8) * F.coalesce(F.col("query_document_signals.normalized_score"), F.lit(0.0))) + (F.lit(0.2) * F.coalesce(F.col("document_popularity_2.normalized_score"), F.lit(0.0)))).alias("score_feedback"),
            F.lit(0.0).alias("score_rank"),
            F.col("policy_3.score_weight"),
            F.col("policy_3.feedback_weight"),
        )
        assert_schema(scored_candidates, DOCUMENT_SEARCH_CANDIDATE_SCHEMA, name="DocumentSearchCandidate", mode="strict")
        return {
            "scored_candidates": scored_candidates,
        }

    def _step_normalize_score_2(self, frames):
        # Step method: normalize_score
        normalized_candidates = frames["scored_candidates"].alias("document_search_candidate")
        normalized_candidates = normalized_candidates.select(
            F.col("document_search_candidate.search_query_id"),
            F.col("document_search_candidate.experiment_id"),
            F.col("document_search_candidate.query"),
            F.col("document_search_candidate.candidate_rank"),
            F.col("document_search_candidate.document_id"),
            F.col("document_search_candidate.title"),
            F.col("document_search_candidate.url"),
            F.col("document_search_candidate.score"),
            F.col("document_search_candidate.score_feedback"),
            (((F.col("document_search_candidate.score_weight") * F.col("document_search_candidate.score")) / F.max(F.col("document_search_candidate.score")).over(Window.partitionBy(F.col("document_search_candidate.search_query_id"), F.col("document_search_candidate.experiment_id")).orderBy(F.col("document_search_candidate.document_id").asc()).rowsBetween(Window.unboundedPreceding, Window.unboundedFollowing))) + (F.col("document_search_candidate.feedback_weight") * F.col("document_search_candidate.score_feedback"))).alias("score_rank"),
            F.col("document_search_candidate.score_weight"),
            F.col("document_search_candidate.feedback_weight"),
        )
        assert_schema(normalized_candidates, DOCUMENT_SEARCH_CANDIDATE_SCHEMA, name="DocumentSearchCandidate", mode="strict")
        return {
            "normalized_candidates": normalized_candidates,
        }

    def _step_rank_results_3(self, frames):
        # Step method: rank_results
        results = frames["normalized_candidates"].alias("document_search_candidate")
        results = results.select(
            F.col("document_search_candidate.search_query_id"),
            F.col("document_search_candidate.experiment_id"),
            F.row_number().over(Window.partitionBy(F.col("document_search_candidate.search_query_id"), F.col("document_search_candidate.experiment_id")).orderBy(F.col("document_search_candidate.score_rank").desc_nulls_last(), F.col("document_search_candidate.document_id").asc_nulls_first())).cast(T.LongType()).alias("rank"),
            F.col("document_search_candidate.candidate_rank"),
            F.col("document_search_candidate.document_id"),
            F.col("document_search_candidate.title"),
            F.col("document_search_candidate.url"),
            F.col("document_search_candidate.score"),
            F.col("document_search_candidate.score_feedback"),
            F.col("document_search_candidate.score_rank"),
        )
        return {
            "results": results,
        }


class SearchDocumentsGenerated(RetrieveDocumentsGenerated, RerankDocumentsGenerated):

    def __init__(self, *, spark: SparkSession, ctx=None):
        self.spark = spark
        self.ctx = ctx

    def run(
        self,
        *,
        queries: DataFrame,
        documents: DataFrame,
        document_scores: DataFrame,
        query_document_signals: DataFrame,
        document_popularity: DataFrame,
        policy: DataFrame,
    ) -> TransformResult:
        assert_schema(queries, SEARCH_QUERY_SCHEMA, name="SearchQuery", mode="strict")
        assert_schema(documents, DOCUMENT_SCHEMA, name="Document", mode="strict")
        assert_schema(document_scores, DOCUMENT_SCORE_SCHEMA, name="DocumentScore", mode="strict")
        assert_schema(query_document_signals, QUERY_DOCUMENT_SIGNALS_SCHEMA, name="QueryDocumentSignals", mode="strict")
        assert_schema(document_popularity, DOCUMENT_POPULARITY_SCHEMA, name="DocumentPopularity", mode="strict")
        assert_schema(policy, RELEVANCE_POLICY_SCHEMA, name="RelevancePolicy", mode="strict")
        _input_queries = queries
        _input_documents = documents
        _input_document_scores = document_scores
        _input_query_document_signals = query_document_signals
        _input_document_popularity = document_popularity
        _input_policy = policy
        frames = {
            "queries": queries,
            "documents": documents,
            "document_scores": document_scores,
            "query_document_signals": query_document_signals,
            "document_popularity": document_popularity,
            "policy": policy,
            "input:queries": _input_queries,
            "input:documents": _input_documents,
            "input:document_scores": _input_document_scores,
            "input:query_document_signals": _input_query_document_signals,
            "input:document_popularity": _input_document_popularity,
            "input:policy": _input_policy,
        }
        frames.update(self._step_select_candidates_0(frames))
        frames.update(self._step_score_candidates_1(frames))
        frames.update(self._step_normalize_score_2(frames))
        frames.update(self._step_rank_results_3(frames))

        # Step method: candidates
        candidates = frames["candidates"].alias("document_search_candidate")
        assert_schema(candidates, DOCUMENT_SEARCH_CANDIDATE_SCHEMA, name="DocumentSearchCandidate", mode="strict")

        # Step method: results
        results = frames["results"].alias("document_search_result")
        assert_schema(results, DOCUMENT_SEARCH_RESULT_SCHEMA, name="DocumentSearchResult", mode="strict")
        return TransformResult({"candidates": candidates, "results": results}, single=False, schema={"candidates": DOCUMENT_SEARCH_CANDIDATE_SCHEMA, "results": DOCUMENT_SEARCH_RESULT_SCHEMA})
