# Generated by Structure. Do not edit by hand.
# Source: examples.search.transforms.similarity.Similarity

from pyspark.sql import DataFrame, SparkSession
from pyspark.sql import Window
from pyspark.sql import functions as F
from pyspark.sql import types as T
from examples.structure_generated.search.runtime.schema_assert import TransformResult, assert_schema, project_schema
from examples.structure_generated.search.pyspark.schemas.similarity import DOCUMENT_SIMILARITY_SCHEMA, INDEXED_SIMILAR_DOCUMENT_SCHEMA, SIMILARITY_DOCUMENT_QUERY_SCHEMA
from examples.structure_generated.search.pyspark.schemas.text import DOCUMENT_SCHEMA


class SimilarityGenerated:

    def __init__(self, *, spark: SparkSession, ctx=None):
        self.spark = spark
        self.ctx = ctx

    def run(
        self,
        *,
        query: DataFrame,
        documents: DataFrame,
        document_similarities: DataFrame,
    ) -> TransformResult:
        assert_schema(query, SIMILARITY_DOCUMENT_QUERY_SCHEMA, name="SimilarityDocumentQuery", mode="strict")
        assert_schema(documents, DOCUMENT_SCHEMA, name="Document", mode="strict")
        assert_schema(document_similarities, DOCUMENT_SIMILARITY_SCHEMA, name="DocumentSimilarity", mode="strict")
        _input_query = query
        _input_documents = documents
        _input_document_similarities = document_similarities

        # Step method: rank
        ranked_documents = query.alias("similarity_document_query")
        document_similarities_joined = document_similarities.alias("document_similarities")
        ranked_documents = ranked_documents.join(
            document_similarities_joined,
            ((F.col("similarity_document_query.id") == F.col("document_similarities.left_document_id")) | (F.col("similarity_document_query.id") == F.col("document_similarities.right_document_id"))),
            "inner",
        )
        documents_2_joined = documents.alias("documents_2")
        ranked_documents = ranked_documents.join(
            documents_2_joined,
            (F.col("documents_2.id") == F.when((F.col("similarity_document_query.id") == F.col("document_similarities.left_document_id")), F.col("document_similarities.right_document_id")).otherwise(F.col("document_similarities.left_document_id"))),
            "inner",
        )
        ranked_documents = ranked_documents.select(
            F.col("documents_2.id"),
            F.col("documents_2.collection_id"),
            F.col("documents_2.source"),
            F.col("documents_2.title"),
            F.col("documents_2.url"),
            F.col("documents_2.content"),
            F.col("documents_2.content_type"),
            F.col("documents_2.encoding"),
            F.col("documents_2.language"),
            F.col("documents_2.created_at"),
            F.col("documents_2.published_at"),
            F.col("documents_2.harvested_at"),
            F.col("similarity_document_query.id").alias("search_query_id"),
            F.col("document_similarities.score_overlap"),
            F.when((F.col("similarity_document_query.id") == F.col("document_similarities.left_document_id")), F.col("document_similarities.bm25_left_to_right")).otherwise(F.col("document_similarities.bm25_right_to_left")).alias("score_bm25"),
            F.row_number().over(Window.partitionBy(F.col("similarity_document_query.id")).orderBy(F.when((F.col("similarity_document_query.id") == F.col("document_similarities.left_document_id")), F.col("document_similarities.bm25_left_to_right")).otherwise(F.col("document_similarities.bm25_right_to_left")).desc(), F.col("document_similarities.score_overlap").desc(), F.col("documents_2.id").asc())).cast(T.LongType()).alias("rank"),
        )
        assert_schema(ranked_documents, INDEXED_SIMILAR_DOCUMENT_SCHEMA, name="IndexedSimilarDocument", mode="strict")

        # Step method: limit
        similar_documents = ranked_documents.alias("indexed_similar_document")
        similar_documents = similar_documents.where(((F.col("indexed_similar_document.rank") <= F.lit(10))))
        similar_documents = similar_documents.select(
            F.col("indexed_similar_document.id"),
            F.col("indexed_similar_document.collection_id"),
            F.col("indexed_similar_document.source"),
            F.col("indexed_similar_document.title"),
            F.col("indexed_similar_document.url"),
            F.col("indexed_similar_document.content"),
            F.col("indexed_similar_document.content_type"),
            F.col("indexed_similar_document.encoding"),
            F.col("indexed_similar_document.language"),
            F.col("indexed_similar_document.created_at"),
            F.col("indexed_similar_document.published_at"),
            F.col("indexed_similar_document.harvested_at"),
            F.col("indexed_similar_document.search_query_id"),
            F.col("indexed_similar_document.score_overlap"),
            F.col("indexed_similar_document.score_bm25"),
            F.col("indexed_similar_document.rank"),
        )

        # Step method: similar_documents
        similar_documents = similar_documents.alias("indexed_similar_document")
        assert_schema(similar_documents, INDEXED_SIMILAR_DOCUMENT_SCHEMA, name="IndexedSimilarDocument", mode="strict")
        return TransformResult({"similar_documents": similar_documents}, single=True, schema={"similar_documents": INDEXED_SIMILAR_DOCUMENT_SCHEMA})
