# Generated by Structure. Do not edit by hand.
# Source: examples.search.transforms.chunking.WordChunking.WordChunking

from __future__ import annotations
from pyspark.sql import DataFrame, SparkSession
from pyspark.sql import functions as F
from pyspark.sql import types as T
from examples.structure_generated.search.runtime.schema_assert import TransformResult, assert_schema, project_schema
from examples.structure_generated.search.pyspark.schemas.text import SENTENCE_SCHEMA, WORD_SCHEMA


class WordChunkingGenerated:

    def __init__(self, *, spark: SparkSession, ctx=None):
        self.spark = spark
        self.ctx = ctx

    def run(
        self,
        *,
        sentences: DataFrame,
    ) -> TransformResult:
        assert_schema(sentences, SENTENCE_SCHEMA, name="Sentence", mode="strict")
        _input_sentences = sentences

        # Step method: chunk
        words = sentences.alias("sentence")
        words = words.select(
            "*",
            F.posexplode(
                F.transform(
                    F.split(F.col("sentence.content"), '\\s+', -1), lambda item: F.struct(item.alias("word_token"))
                )
            ).alias("__structure_word_text_1_pos", "__structure_word_text_1_item"),
        )
        words = words.withColumn(
            "position",
            F.col("__structure_word_text_1_pos").cast(T.LongType()),
        )
        words = words.withColumn(
            "word_token",
            F.col("__structure_word_text_1_item.word_token"),
        )
        words = words.drop("__structure_word_text_1_pos", "__structure_word_text_1_item")
        words = words.where(
            ((F.lower(F.regexp_replace(F.trim(F.col("word_token")), '^[^A-Za-z0-9]+|[^A-Za-z0-9]+$', '')) != F.lit('')))
        )
        words = words.select(
            F.concat_ws('#w', F.col("sentence.id"), F.col("position").cast('string')).alias("id"),
            F.col("sentence.document_id"),
            F.col("sentence.section_id"),
            F.col("sentence.paragraph_id"),
            F.col("sentence.paragraph_ordinal"),
            F.col("sentence.id").alias("sentence_id"),
            (F.col("position") + F.lit(1)).cast('int').alias("ordinal"),
            F.lower(F.regexp_replace(F.trim(F.col("word_token")), '^[^A-Za-z0-9]+|[^A-Za-z0-9]+$', '')).alias("token"),
        )

        # Step method: words
        words = words.alias("word")
        assert_schema(words, WORD_SCHEMA, name="Word", mode="strict")
        return TransformResult({"words": words}, single=True, schema={"words": WORD_SCHEMA})
