# Generated by Structure. Do not edit by hand.
# Source: examples.security.transforms.posture.SecurityPosture

from __future__ import annotations
from pyspark.sql import DataFrame, SparkSession
from pyspark.sql import functions as F
from pyspark.sql import types as T
from examples.structure_generated.security.runtime.schema_assert import (
    TransformResult,
    assert_schema,
    project_schema,
    apply_plan_boundary,
    close_plan_boundaries,
)
from examples.structure_generated.security.pyspark.schemas.assets import (
    DEVICE_SCHEMA,
    DEVICE_TYPE_SCHEMA,
    SOFTWARE_SCHEMA,
)
from examples.structure_generated.security.pyspark.schemas.organization import (
    DEPARTMENT_SCHEMA,
    ORG_SCHEMA,
    PERSON_SCHEMA,
    TEAM_SCHEMA,
)
from examples.structure_generated.security.pyspark.schemas.reporting import (
    VULNERABILITY_EXPOSURE_SCHEMA,
    VULNERABILITY_POSTURE_CANDIDATE_SCHEMA,
)
from examples.structure_generated.security.pyspark.schemas.risk import (
    REMEDIATION_POLICY_SCHEMA,
    VULN_SCHEMA,
    VULN_TYPE_SCHEMA,
)


class SecurityPostureGenerated:

    def __init__(self, *, spark: SparkSession, ctx=None):
        self.spark = spark
        self.ctx = ctx

    def close(self) -> None:
        close_plan_boundaries(self.spark)

    def run(
        self,
        *,
        vulnerabilities: DataFrame,
        devices: DataFrame,
        device_types: DataFrame,
        software: DataFrame,
        vuln_types: DataFrame,
        remediation_policies: DataFrame,
        people: DataFrame,
        teams: DataFrame,
        departments: DataFrame,
        orgs: DataFrame,
    ) -> TransformResult:
        assert_schema(vulnerabilities, VULN_SCHEMA, name="Vuln", mode="strict")
        assert_schema(devices, DEVICE_SCHEMA, name="Device", mode="strict")
        assert_schema(device_types, DEVICE_TYPE_SCHEMA, name="DeviceType", mode="strict")
        assert_schema(software, SOFTWARE_SCHEMA, name="Software", mode="strict")
        assert_schema(vuln_types, VULN_TYPE_SCHEMA, name="VulnType", mode="strict")
        assert_schema(remediation_policies, REMEDIATION_POLICY_SCHEMA, name="RemediationPolicy", mode="strict")
        assert_schema(people, PERSON_SCHEMA, name="Person", mode="strict")
        assert_schema(teams, TEAM_SCHEMA, name="Team", mode="strict")
        assert_schema(departments, DEPARTMENT_SCHEMA, name="Department", mode="strict")
        assert_schema(orgs, ORG_SCHEMA, name="Org", mode="strict")
        _input_vulnerabilities = vulnerabilities
        _input_devices = devices
        _input_device_types = device_types
        _input_software = software
        _input_vuln_types = vuln_types
        _input_remediation_policies = remediation_policies
        _input_people = people
        _input_teams = teams
        _input_departments = departments
        _input_orgs = orgs

        # Step method: prepare_exposure
        vulnerabilities = vulnerabilities.alias("vuln")
        devices_joined = devices.alias("devices")
        vulnerabilities = vulnerabilities.join(
            devices_joined,
            (F.col("devices.id") == F.col("vuln.device_id")),
            "inner",
        )
        device_types_2_joined = device_types.alias("device_types_2")
        vulnerabilities = vulnerabilities.join(
            device_types_2_joined,
            (F.col("device_types_2.id") == F.col("devices.device_type_id")),
            "inner",
        )
        software_3_joined = software.alias("software_3")
        vulnerabilities = vulnerabilities.join(
            software_3_joined,
            (F.col("software_3.id") == F.col("vuln.software_id")),
            "inner",
        )
        vuln_types_4_joined = vuln_types.alias("vuln_types_4")
        vulnerabilities = vulnerabilities.join(
            vuln_types_4_joined,
            (F.col("vuln_types_4.id") == F.col("vuln.vuln_type_id")),
            "inner",
        )
        remediation_policies_5_joined = remediation_policies.alias("remediation_policies_5")
        vulnerabilities = vulnerabilities.join(
            remediation_policies_5_joined,
            (F.col("remediation_policies_5.severity") == F.col("vuln_types_4.severity")),
            "inner",
        )
        people_6_joined = people.alias("people_6")
        vulnerabilities = vulnerabilities.join(
            people_6_joined,
            (F.col("people_6.id") == F.col("vuln.owner_id")),
            "inner",
        )
        teams_7_joined = teams.alias("teams_7")
        vulnerabilities = vulnerabilities.join(
            teams_7_joined,
            (F.col("teams_7.id") == F.col("people_6.team_id")),
            "inner",
        )
        departments_8_joined = departments.alias("departments_8")
        vulnerabilities = vulnerabilities.join(
            departments_8_joined,
            (F.col("departments_8.id") == F.col("teams_7.department_id")),
            "inner",
        )
        orgs_9_joined = orgs.alias("orgs_9")
        vulnerabilities = vulnerabilities.join(
            orgs_9_joined,
            (F.col("orgs_9.id") == F.col("departments_8.org_id")),
            "inner",
        )
        vulnerabilities = vulnerabilities.select(
            F.col("vuln.id").alias("vuln_id"),
            F.col("vuln_types_4.type").alias("vuln_type"),
            F.col("vuln_types_4.description"),
            F.col("vuln_types_4.instructions"),
            F.col("vuln_types_4.severity"),
            F.col("vuln.date_discovered"),
            F.col("vuln.date_addressed"),
            F.date_add(F.col("vuln.date_discovered"), F.col("remediation_policies_5.target_days")).alias("target_date"),
            F.col("vuln.date_addressed").isNull().alias("is_active"),
            F.col("devices.id").alias("device_id"),
            F.col("device_types_2.platform").alias("device_platform"),
            F.col("device_types_2.model").alias("device_model"),
            F.col("software_3.id").alias("software_id"),
            F.col("software_3.name").alias("software_name"),
            F.col("software_3.version").alias("software_version"),
            F.col("people_6.id").alias("person_id"),
            F.col("people_6.name").alias("person_name"),
            F.col("teams_7.id").alias("team_id"),
            F.col("teams_7.name").alias("team_name"),
            F.col("departments_8.id").alias("department_id"),
            F.col("departments_8.name").alias("department_name"),
            F.col("orgs_9.id").alias("org_id"),
            F.col("orgs_9.name").alias("org_name"),
            F.col("devices.owner_id").alias("device_owner_id"),
            F.col("devices.os_id").alias("device_os_id"),
            F.col("devices.vuln_ids").alias("device_vuln_ids"),
            F.col("devices.apps").alias("device_apps"),
        )
        assert_schema(
            vulnerabilities, VULNERABILITY_POSTURE_CANDIDATE_SCHEMA, name="VulnerabilityPostureCandidate", mode="strict"
        )

        # Step method: expose
        vulnerabilities = vulnerabilities.alias("vulnerability_posture_candidate")
        vulnerabilities = vulnerabilities.where(
            (
                (
                    (
                        (
                            F.col("vulnerability_posture_candidate.device_owner_id")
                            == F.col("vulnerability_posture_candidate.person_id")
                        )
                        & F.array_contains(
                            F.col("vulnerability_posture_candidate.device_vuln_ids"),
                            F.col("vulnerability_posture_candidate.vuln_id"),
                        )
                    )
                    & (
                        (
                            F.col("vulnerability_posture_candidate.device_os_id")
                            == F.col("vulnerability_posture_candidate.software_id")
                        )
                        | F.exists(
                            F.col("vulnerability_posture_candidate.device_apps"),
                            lambda item: (item.getField('id') == F.col("vulnerability_posture_candidate.software_id")),
                        )
                    )
                )
            )
        )
        vulnerabilities = vulnerabilities.select(
            F.col("vulnerability_posture_candidate.vuln_id"),
            F.col("vulnerability_posture_candidate.vuln_type"),
            F.col("vulnerability_posture_candidate.description"),
            F.col("vulnerability_posture_candidate.instructions"),
            F.col("vulnerability_posture_candidate.severity"),
            F.col("vulnerability_posture_candidate.date_discovered"),
            F.col("vulnerability_posture_candidate.date_addressed"),
            F.col("vulnerability_posture_candidate.target_date"),
            F.col("vulnerability_posture_candidate.is_active"),
            F.col("vulnerability_posture_candidate.device_id"),
            F.col("vulnerability_posture_candidate.device_platform"),
            F.col("vulnerability_posture_candidate.device_model"),
            F.col("vulnerability_posture_candidate.software_id"),
            F.col("vulnerability_posture_candidate.software_name"),
            F.col("vulnerability_posture_candidate.software_version"),
            F.col("vulnerability_posture_candidate.person_id"),
            F.col("vulnerability_posture_candidate.person_name"),
            F.col("vulnerability_posture_candidate.team_id"),
            F.col("vulnerability_posture_candidate.team_name"),
            F.col("vulnerability_posture_candidate.department_id"),
            F.col("vulnerability_posture_candidate.department_name"),
            F.col("vulnerability_posture_candidate.org_id"),
            F.col("vulnerability_posture_candidate.org_name"),
        )

        # Step method: exposures
        exposures = vulnerabilities.alias("vulnerability_exposure")
        assert_schema(exposures, VULNERABILITY_EXPOSURE_SCHEMA, name="VulnerabilityExposure", mode="strict")
        return TransformResult(
            {"exposures": exposures}, single=True, schema={"exposures": VULNERABILITY_EXPOSURE_SCHEMA}
        )
