# Generated by Structure. Do not edit by hand.
# Source: examples.security.transforms.quality.SecurityInventoryQuality

from __future__ import annotations
from pyspark.sql import DataFrame, SparkSession
from pyspark.sql import functions as F
from pyspark.sql import types as T
from examples.structure_generated.security.runtime.schema_assert import (
    TransformResult,
    assert_schema,
    project_schema,
    apply_plan_boundary,
    close_plan_boundaries,
)
from examples.structure_generated.security.pyspark.schemas.assets import (
    DEVICE_SCHEMA,
    DEVICE_TYPE_SCHEMA,
    SOFTWARE_SCHEMA,
)
from examples.structure_generated.security.pyspark.schemas.organization import (
    DEPARTMENT_SCHEMA,
    ORG_SCHEMA,
    PERSON_SCHEMA,
    TEAM_SCHEMA,
)
from examples.structure_generated.security.pyspark.schemas.reporting import (
    VULNERABILITY_INVENTORY_CANDIDATE_SCHEMA,
    VULNERABILITY_INVENTORY_CHECK_SCHEMA,
    VULNERABILITY_INVENTORY_ISSUE_SCHEMA,
    VULNERABILITY_QUALITY_CHECK_SCHEMA,
    VULNERABILITY_QUALITY_ISSUE_SCHEMA,
)
from examples.structure_generated.security.pyspark.schemas.risk import VULN_SCHEMA, VULN_TYPE_SCHEMA


class SecurityInventoryQualityGenerated:

    def __init__(self, *, spark: SparkSession, ctx=None):
        self.spark = spark
        self.ctx = ctx

    def close(self) -> None:
        close_plan_boundaries(self.spark)

    def run(
        self,
        *,
        vulnerabilities: DataFrame,
        devices: DataFrame,
        device_types: DataFrame,
        software: DataFrame,
        vuln_types: DataFrame,
        people: DataFrame,
        teams: DataFrame,
        departments: DataFrame,
        orgs: DataFrame,
    ) -> TransformResult:
        assert_schema(vulnerabilities, VULN_SCHEMA, name="Vuln", mode="strict")
        assert_schema(devices, DEVICE_SCHEMA, name="Device", mode="strict")
        assert_schema(device_types, DEVICE_TYPE_SCHEMA, name="DeviceType", mode="strict")
        assert_schema(software, SOFTWARE_SCHEMA, name="Software", mode="strict")
        assert_schema(vuln_types, VULN_TYPE_SCHEMA, name="VulnType", mode="strict")
        assert_schema(people, PERSON_SCHEMA, name="Person", mode="strict")
        assert_schema(teams, TEAM_SCHEMA, name="Team", mode="strict")
        assert_schema(departments, DEPARTMENT_SCHEMA, name="Department", mode="strict")
        assert_schema(orgs, ORG_SCHEMA, name="Org", mode="strict")
        _input_vulnerabilities = vulnerabilities
        _input_devices = devices
        _input_device_types = device_types
        _input_software = software
        _input_vuln_types = vuln_types
        _input_people = people
        _input_teams = teams
        _input_departments = departments
        _input_orgs = orgs

        # Step method: check_references
        quality_lane = vulnerabilities.alias("vuln")
        devices_joined = devices.alias("devices")
        quality_lane = quality_lane.join(
            devices_joined,
            (F.col("devices.id") == F.col("vuln.device_id")),
            "left",
        )
        device_types_2_joined = device_types.alias("device_types_2")
        quality_lane = quality_lane.join(
            device_types_2_joined,
            (F.col("device_types_2.id") == F.col("devices.device_type_id")),
            "left",
        )
        software_3_joined = software.alias("software_3")
        quality_lane = quality_lane.join(
            software_3_joined,
            (F.col("software_3.id") == F.col("vuln.software_id")),
            "left",
        )
        vuln_types_4_joined = vuln_types.alias("vuln_types_4")
        quality_lane = quality_lane.join(
            vuln_types_4_joined,
            (F.col("vuln_types_4.id") == F.col("vuln.vuln_type_id")),
            "left",
        )
        people_5_joined = people.alias("people_5")
        quality_lane = quality_lane.join(
            people_5_joined,
            (F.col("people_5.id") == F.col("vuln.owner_id")),
            "left",
        )
        teams_6_joined = teams.alias("teams_6")
        quality_lane = quality_lane.join(
            teams_6_joined,
            (F.col("teams_6.id") == F.col("people_5.team_id")),
            "left",
        )
        departments_7_joined = departments.alias("departments_7")
        quality_lane = quality_lane.join(
            departments_7_joined,
            (F.col("departments_7.id") == F.col("teams_6.department_id")),
            "left",
        )
        orgs_8_joined = orgs.alias("orgs_8")
        quality_lane = quality_lane.join(
            orgs_8_joined,
            (F.col("orgs_8.id") == F.col("departments_7.org_id")),
            "left",
        )
        quality_lane = quality_lane.select(
            F.col("vuln.id").alias("vuln_id"),
            F.col("vuln.device_id"),
            F.col("vuln.owner_id"),
            F.col("vuln.software_id"),
            F.col("vuln.vuln_type_id"),
            F.array_compact(
                F.array(
                    F.when(F.col("devices.id").isNull(), F.lit('missing device')).otherwise(F.lit(None)),
                    F.when(
                        (F.col("devices.id").isNotNull() & F.col("device_types_2.id").isNull()),
                        F.lit('missing device type'),
                    ).otherwise(F.lit(None)),
                    F.when(F.col("software_3.id").isNull(), F.lit('missing software')).otherwise(F.lit(None)),
                    F.when(F.col("vuln_types_4.id").isNull(), F.lit('missing vulnerability type')).otherwise(
                        F.lit(None)
                    ),
                    F.when(F.col("people_5.id").isNull(), F.lit('missing person')).otherwise(F.lit(None)),
                    F.when(
                        (F.col("people_5.id").isNotNull() & F.col("teams_6.id").isNull()), F.lit('missing team')
                    ).otherwise(F.lit(None)),
                    F.when(
                        (F.col("teams_6.id").isNotNull() & F.col("departments_7.id").isNull()),
                        F.lit('missing department'),
                    ).otherwise(F.lit(None)),
                    F.when(
                        (F.col("departments_7.id").isNotNull() & F.col("orgs_8.id").isNull()),
                        F.lit('missing organization'),
                    ).otherwise(F.lit(None)),
                    F.when(
                        (F.col("devices.id").isNotNull() & (F.col("devices.owner_id") != F.col("vuln.owner_id"))),
                        F.lit('device owner disagrees with vulnerability owner'),
                    ).otherwise(F.lit(None)),
                    F.when(
                        (F.col("vuln.is_active") != F.col("vuln.date_addressed").isNull()),
                        F.lit('is_active disagrees with date_addressed'),
                    ).otherwise(F.lit(None)),
                )
            ).alias("issues"),
            (
                F.size(
                    F.array_compact(
                        F.array(
                            F.when(F.col("devices.id").isNull(), F.lit('missing device')).otherwise(F.lit(None)),
                            F.when(
                                (F.col("devices.id").isNotNull() & F.col("device_types_2.id").isNull()),
                                F.lit('missing device type'),
                            ).otherwise(F.lit(None)),
                            F.when(F.col("software_3.id").isNull(), F.lit('missing software')).otherwise(F.lit(None)),
                            F.when(F.col("vuln_types_4.id").isNull(), F.lit('missing vulnerability type')).otherwise(
                                F.lit(None)
                            ),
                            F.when(F.col("people_5.id").isNull(), F.lit('missing person')).otherwise(F.lit(None)),
                            F.when(
                                (F.col("people_5.id").isNotNull() & F.col("teams_6.id").isNull()), F.lit('missing team')
                            ).otherwise(F.lit(None)),
                            F.when(
                                (F.col("teams_6.id").isNotNull() & F.col("departments_7.id").isNull()),
                                F.lit('missing department'),
                            ).otherwise(F.lit(None)),
                            F.when(
                                (F.col("departments_7.id").isNotNull() & F.col("orgs_8.id").isNull()),
                                F.lit('missing organization'),
                            ).otherwise(F.lit(None)),
                            F.when(
                                (
                                    F.col("devices.id").isNotNull()
                                    & (F.col("devices.owner_id") != F.col("vuln.owner_id"))
                                ),
                                F.lit('device owner disagrees with vulnerability owner'),
                            ).otherwise(F.lit(None)),
                            F.when(
                                (F.col("vuln.is_active") != F.col("vuln.date_addressed").isNull()),
                                F.lit('is_active disagrees with date_addressed'),
                            ).otherwise(F.lit(None)),
                        )
                    )
                )
                == F.lit(0)
            ).alias("is_valid"),
        )
        assert_schema(quality_lane, VULNERABILITY_QUALITY_CHECK_SCHEMA, name="VulnerabilityQualityCheck", mode="strict")

        # Step method: publish_reference_checks
        quality_lane = quality_lane.alias("vulnerability_quality_check")
        quality_lane = quality_lane.select(
            F.col("vulnerability_quality_check.vuln_id"),
            F.col("vulnerability_quality_check.device_id"),
            F.col("vulnerability_quality_check.owner_id"),
            F.col("vulnerability_quality_check.software_id"),
            F.col("vulnerability_quality_check.vuln_type_id"),
            F.col("vulnerability_quality_check.issues"),
            F.col("vulnerability_quality_check.is_valid"),
        )
        assert_schema(quality_lane, VULNERABILITY_QUALITY_CHECK_SCHEMA, name="VulnerabilityQualityCheck", mode="strict")

        # Step method: publish_reference_issues
        reference_issues = quality_lane.alias("vulnerability_quality_check")
        reference_issues = reference_issues.where((~(F.col("vulnerability_quality_check.is_valid"))))
        reference_issues = reference_issues.select(
            F.col("vulnerability_quality_check.vuln_id"),
            F.col("vulnerability_quality_check.device_id"),
            F.col("vulnerability_quality_check.owner_id"),
            F.col("vulnerability_quality_check.software_id"),
            F.col("vulnerability_quality_check.vuln_type_id"),
            F.col("vulnerability_quality_check.issues"),
            F.col("vulnerability_quality_check.is_valid"),
        )
        assert_schema(
            reference_issues, VULNERABILITY_QUALITY_ISSUE_SCHEMA, name="VulnerabilityQualityIssue", mode="strict"
        )

        # Step method: prepare_inventory_reconciliation
        inventory_candidates = vulnerabilities.alias("vuln")
        devices_joined = devices.alias("devices")
        inventory_candidates = inventory_candidates.join(
            devices_joined,
            (F.col("devices.id") == F.col("vuln.device_id")),
            "inner",
        )
        inventory_candidates = inventory_candidates.select(
            F.col("vuln.id").alias("vuln_id"),
            F.col("vuln.device_id"),
            F.col("vuln.software_id"),
            F.array_contains(F.col("devices.vuln_ids"), F.col("vuln.id")).alias("device_lists_vulnerability"),
            F.col("devices.os_id"),
            F.col("devices.apps"),
            (
                (F.col("devices.os_id") == F.col("vuln.software_id"))
                | F.exists(F.col("devices.apps"), lambda item: (item.getField('id') == F.col("vuln.software_id")))
            ).alias("device_has_software"),
            (
                F.array_contains(F.col("devices.vuln_ids"), F.col("vuln.id"))
                & (
                    (F.col("devices.os_id") == F.col("vuln.software_id"))
                    | F.exists(F.col("devices.apps"), lambda item: (item.getField('id') == F.col("vuln.software_id")))
                )
            ).alias("is_reconciled"),
        )
        assert_schema(
            inventory_candidates,
            VULNERABILITY_INVENTORY_CANDIDATE_SCHEMA,
            name="VulnerabilityInventoryCandidate",
            mode="strict",
        )

        # Step method: publish_reconciliation
        reconciliation_lane = inventory_candidates.alias("vulnerability_inventory_candidate")
        reconciliation_lane = reconciliation_lane.select(
            F.col("vulnerability_inventory_candidate.vuln_id"),
            F.col("vulnerability_inventory_candidate.device_id"),
            F.col("vulnerability_inventory_candidate.software_id"),
            F.col("vulnerability_inventory_candidate.device_lists_vulnerability"),
            F.col("vulnerability_inventory_candidate.device_has_software"),
            F.col("vulnerability_inventory_candidate.is_reconciled"),
        )
        assert_schema(
            reconciliation_lane, VULNERABILITY_INVENTORY_CHECK_SCHEMA, name="VulnerabilityInventoryCheck", mode="strict"
        )

        # Step method: publish_reconciliation_checks
        reconciliation_lane = reconciliation_lane.alias("vulnerability_inventory_check")
        reconciliation_lane = reconciliation_lane.select(
            F.col("vulnerability_inventory_check.vuln_id"),
            F.col("vulnerability_inventory_check.device_id"),
            F.col("vulnerability_inventory_check.software_id"),
            F.col("vulnerability_inventory_check.device_lists_vulnerability"),
            F.col("vulnerability_inventory_check.device_has_software"),
            F.col("vulnerability_inventory_check.is_reconciled"),
        )
        assert_schema(
            reconciliation_lane, VULNERABILITY_INVENTORY_CHECK_SCHEMA, name="VulnerabilityInventoryCheck", mode="strict"
        )

        # Step method: publish_reconciliation_issues
        reconciliation_issues = reconciliation_lane.alias("vulnerability_inventory_check")
        reconciliation_issues = reconciliation_issues.where((~(F.col("vulnerability_inventory_check.is_reconciled"))))
        reconciliation_issues = reconciliation_issues.select(
            F.col("vulnerability_inventory_check.vuln_id"),
            F.col("vulnerability_inventory_check.device_id"),
            F.col("vulnerability_inventory_check.software_id"),
            F.col("vulnerability_inventory_check.device_lists_vulnerability"),
            F.col("vulnerability_inventory_check.device_has_software"),
            F.col("vulnerability_inventory_check.is_reconciled"),
        )

        # Step method: reference_checks
        reference_checks = quality_lane.alias("vulnerability_quality_check")
        assert_schema(
            reference_checks, VULNERABILITY_QUALITY_CHECK_SCHEMA, name="VulnerabilityQualityCheck", mode="strict"
        )

        # Step method: reference_issues
        reference_issues = reference_issues.alias("vulnerability_quality_issue")
        assert_schema(
            reference_issues, VULNERABILITY_QUALITY_ISSUE_SCHEMA, name="VulnerabilityQualityIssue", mode="strict"
        )

        # Step method: reconciliation_checks
        reconciliation_checks = reconciliation_lane.alias("vulnerability_inventory_check")
        assert_schema(
            reconciliation_checks,
            VULNERABILITY_INVENTORY_CHECK_SCHEMA,
            name="VulnerabilityInventoryCheck",
            mode="strict",
        )

        # Step method: reconciliation_issues
        reconciliation_issues = reconciliation_issues.alias("vulnerability_inventory_issue")
        assert_schema(
            reconciliation_issues,
            VULNERABILITY_INVENTORY_ISSUE_SCHEMA,
            name="VulnerabilityInventoryIssue",
            mode="strict",
        )
        return TransformResult(
            {
                "reference_checks": reference_checks,
                "reference_issues": reference_issues,
                "reconciliation_checks": reconciliation_checks,
                "reconciliation_issues": reconciliation_issues,
            },
            single=False,
            schema={
                "reference_checks": VULNERABILITY_QUALITY_CHECK_SCHEMA,
                "reference_issues": VULNERABILITY_QUALITY_ISSUE_SCHEMA,
                "reconciliation_checks": VULNERABILITY_INVENTORY_CHECK_SCHEMA,
                "reconciliation_issues": VULNERABILITY_INVENTORY_ISSUE_SCHEMA,
            },
        )
