import json

from structure.app.backend.pyspark.api import lower_pyspark_plan, render_pyspark_project
from structure.app.dsl.api import compile_transform


def _source_schema_modules():
    from testing.model.v1.orders.schemas.common import Address, AuditStamp, BusinessDate, TenantKey
    from testing.model.v1.orders.schemas.customer import Customer
    from testing.model.v1.orders.schemas.order import (
        OrderNormalized,
        OrderPublication,
        OrderPublished,
        OrderRaw,
        OrderWithCustomer,
        OrderWithProduct,
        OrderWithPromotion,
        PublicationFlags,
    )
    from testing.model.v1.orders.schemas.product import Product
    from testing.model.v1.orders.schemas.promotion import Promotion

    return {
        "testing.model.v1.orders.schemas.common": [TenantKey, AuditStamp, Address, BusinessDate],
        "testing.model.v1.orders.schemas.customer": [Customer],
        "testing.model.v1.orders.schemas.order": [
            OrderRaw,
            OrderNormalized,
            OrderWithCustomer,
            OrderWithProduct,
            OrderWithPromotion,
            OrderPublication,
            PublicationFlags,
            OrderPublished,
        ],
        "testing.model.v1.orders.schemas.product": [Product],
        "testing.model.v1.orders.schemas.promotion": [Promotion],
    }


def test_v1_project_renderer_emits_runtime_schemas_transform_and_lineage() -> None:
    from testing.model.v1.orders.transforms.order import EnrichOrders

    files = render_pyspark_project(
        lower_pyspark_plan(compile_transform(EnrichOrders)),
        source_transform="testing.model.v1.orders.transforms.order.EnrichOrders",
        generated_package="testing.model.v1.structure_generated.orders",
        source_schema_modules=_source_schema_modules(),
    )

    assert "testing/model/v1/structure_generated/orders/runtime/schema_assert.py" in files
    assert "testing/model/v1/structure_generated/orders/pyspark/schemas/order.py" in files
    assert "testing/model/v1/structure_generated/orders/pyspark/transforms/order.py" in files
    assert "testing/model/v1/structure_generated/orders/lineage/transforms/order.EnrichOrders.json" in files

    transform = files["testing/model/v1/structure_generated/orders/pyspark/transforms/order.py"]
    assert transform.startswith("# Generated by Structure. Do not edit by hand.\n")
    assert (
        "from testing.model.v1.structure_generated.orders.runtime.schema_assert import "
        "assert_schema, project_schema, HookInputs"
    ) in transform

    schema = files["testing/model/v1/structure_generated/orders/pyspark/schemas/order.py"]
    assert "# Source: testing.model.v1.orders.schemas.order" in schema
    assert (
        "ORDER_PUBLISHED_SCHEMA = T.StructType(ORDER_PUBLICATION_SCHEMA.fields + PUBLICATION_FLAGS_SCHEMA.fields)"
        in schema
    )

    lineage = json.loads(
        files["testing/model/v1/structure_generated/orders/lineage/transforms/order.EnrichOrders.json"]
    )
    assert lineage["source_transform"] == "testing.model.v1.orders.transforms.order.EnrichOrders"
    assert lineage["generated_transform_class"] == "EnrichOrdersGenerated"
    assert [step["name"] for step in lineage["steps"]] == [
        "normalize",
        "add_customer",
        "add_product",
        "add_promotion",
        "publish",
    ]
    assert lineage["steps"][1]["joins"] == [
        {"how": "left", "input": "customers", "right_alias": "customers"},
    ]
    assert lineage["steps"][3]["after_hooks"] == ["note_lookup_inputs"]


def test_v1_project_renderer_is_deterministic() -> None:
    from testing.model.v1.orders.transforms.order import EnrichOrders

    plan = lower_pyspark_plan(compile_transform(EnrichOrders))
    kwargs = {
        "source_transform": "testing.model.v1.orders.transforms.order.EnrichOrders",
        "generated_package": "testing.model.v1.structure_generated.orders",
        "source_schema_modules": _source_schema_modules(),
    }

    assert render_pyspark_project(plan, **kwargs) == render_pyspark_project(plan, **kwargs)
