import json

from structure.app.dsl.api import compile_transform
from structure.app.target.pyspark.api import PySpark


def _source_schema_modules():
    from testing.model.v1.orders.schemas.common import Address, AuditStamp, BusinessDate, TenantKey
    from testing.model.v1.orders.schemas.customer import Customer
    from testing.model.v1.orders.schemas.order import (
        OrderNormalized,
        OrderPublication,
        OrderPublished,
        OrderRaw,
        OrderWithCustomer,
        OrderWithProduct,
        OrderWithPromotion,
        PublicationFlags,
    )
    from testing.model.v1.orders.schemas.product import Product
    from testing.model.v1.orders.schemas.promotion import Promotion

    return {
        "testing.model.v1.orders.schemas.common": [TenantKey, AuditStamp, Address, BusinessDate],
        "testing.model.v1.orders.schemas.customer": [Customer],
        "testing.model.v1.orders.schemas.order": [
            OrderRaw,
            OrderNormalized,
            OrderWithCustomer,
            OrderWithProduct,
            OrderWithPromotion,
            OrderPublication,
            PublicationFlags,
            OrderPublished,
        ],
        "testing.model.v1.orders.schemas.product": [Product],
        "testing.model.v1.orders.schemas.promotion": [Promotion],
    }


def test_v1_project_renderer_emits_runtime_schemas_transform_and_traceability() -> None:
    from testing.model.v1.orders.transforms.order import EnrichOrders

    files = PySpark.render.project()(
        PySpark.plan.lower()(compile_transform(EnrichOrders)),
        source_transform="testing.model.v1.orders.transforms.order.EnrichOrders",
        generated_package="testing.model.v1.structure_generated.orders",
        source_schema_modules=_source_schema_modules(),
    )

    assert "testing/model/v1/structure_generated/orders/runtime/schema_assert.py" in files
    assert "testing/model/v1/structure_generated/orders/pyspark/schemas/order.py" in files
    assert "testing/model/v1/structure_generated/orders/pyspark/transforms/order.py" in files
    assert "testing/model/v1/structure_generated/orders/traceability/transforms/order.EnrichOrders.json" in files

    transform = files["testing/model/v1/structure_generated/orders/pyspark/transforms/order.py"]
    assert transform.startswith("# Generated by Structure. Do not edit by hand.\n")
    assert (
        "from testing.model.v1.structure_generated.orders.runtime.schema_assert import "
        "TransformResult, assert_schema, project_schema, HookInputs"
    ) in transform

    schema = files["testing/model/v1/structure_generated/orders/pyspark/schemas/order.py"]
    assert "# Source: testing.model.v1.orders.schemas.order" in schema
    assert (
        "ORDER_PUBLISHED_SCHEMA = T.StructType(ORDER_PUBLICATION_SCHEMA.fields + PUBLICATION_FLAGS_SCHEMA.fields)"
        in schema
    )

    traceability = json.loads(
        files["testing/model/v1/structure_generated/orders/traceability/transforms/order.EnrichOrders.json"]
    )
    assert traceability["source_transform"] == "testing.model.v1.orders.transforms.order.EnrichOrders"
    assert traceability["generated_transform_class"] == "EnrichOrdersGenerated"
    assert [step["name"] for step in traceability["steps"]] == [
        "normalize",
        "add_customer",
        "add_product",
        "add_promotion",
        "publish",
    ]
    assert traceability["steps"][1]["joins"] == [
        {"how": "left", "input": "customers", "right_alias": "customers"},
    ]
    assert traceability["steps"][3]["after_hooks"] == ["note_lookup_inputs"]
    assert traceability["provenance"][0] == {
        "generated": "generated:testing.model.v1.structure_generated.orders.pyspark.transforms.order.EnrichOrdersGenerated",
        "ir": "ir:EnrichOrders",
        "source": "source:testing.model.v1.orders.transforms.order.EnrichOrders",
    }
    assert any(
        dependency["target"] == "OrderWithCustomer.customer_name"
        for dependency in traceability["static_dataflow"]["dependencies"]
    )
    assert {
        "hook": "add_quality_columns",
        "phase": "after",
        "reason": "arbitrary PySpark hook body",
        "schema": "OrderPublished",
        "step": "publish",
        "target": "publish",
    } in traceability["static_dataflow"]["opaque_boundaries"]


def test_v1_project_renderer_is_deterministic() -> None:
    from testing.model.v1.orders.transforms.order import EnrichOrders

    plan = PySpark.plan.lower()(compile_transform(EnrichOrders))
    kwargs = {
        "source_transform": "testing.model.v1.orders.transforms.order.EnrichOrders",
        "generated_package": "testing.model.v1.structure_generated.orders",
        "source_schema_modules": _source_schema_modules(),
    }

    assert PySpark.render.project()(plan, **kwargs) == PySpark.render.project()(plan, **kwargs)
