# Generated by Structure. Do not edit by hand.
# Source: examples.store.transforms.fulfillment.shortages.detect.DetectShortages

from __future__ import annotations
from pyspark.sql import DataFrame, SparkSession
from pyspark.sql import Window
from pyspark.sql import functions as F
from pyspark.sql import types as T
from examples.structure_generated.store.runtime.schema_assert import TransformResult, assert_schema, project_schema
from examples.structure_generated.store.pyspark.schemas.projection import INVENTORY_PROJECTION_SCHEMA
from examples.structure_generated.store.pyspark.schemas.shortage import (
    FULFILLMENT_SHORTAGE_RANKED_SCHEMA,
    FULFILLMENT_SHORTAGE_SCHEMA,
)


class DetectShortagesGenerated:

    def __init__(self, *, spark: SparkSession, ctx=None):
        self.spark = spark
        self.ctx = ctx

    def run(
        self,
        *,
        projections: DataFrame,
    ) -> TransformResult:
        assert_schema(projections, INVENTORY_PROJECTION_SCHEMA, name="InventoryProjection", mode="strict")
        _input_projections = projections

        # Step method: identify
        ranked = projections.alias("inventory_projection")
        ranked = ranked.where(
            (
                (
                    F.col("inventory_projection.projected_available_quantity")
                    < F.col("inventory_projection.safety_stock_quantity")
                )
            )
        )
        ranked = ranked.select(
            F.col("inventory_projection.tenant"),
            F.col("inventory_projection.warehouse_id"),
            F.col("inventory_projection.product_id"),
            F.col("inventory_projection.window_start").alias("first_shortage_at"),
            (
                F.col("inventory_projection.safety_stock_quantity")
                - F.col("inventory_projection.projected_available_quantity")
            ).alias("shortage_quantity"),
            F.col("inventory_projection.projected_available_quantity"),
            F.col("inventory_projection.safety_stock_quantity"),
            F.lit('below_safety_stock').alias("reason"),
            F.row_number()
            .over(
                Window.partitionBy(
                    F.col("inventory_projection.tenant.tenant_id"),
                    F.col("inventory_projection.warehouse_id"),
                    F.col("inventory_projection.product_id"),
                ).orderBy(F.col("inventory_projection.window_start").asc())
            )
            .cast(T.LongType())
            .alias("shortage_ordinal"),
        )
        assert_schema(ranked, FULFILLMENT_SHORTAGE_RANKED_SCHEMA, name="FulfillmentShortageRanked", mode="strict")

        # Step method: select_first
        shortages = ranked.alias("fulfillment_shortage_ranked")
        shortages = shortages.where(((F.col("fulfillment_shortage_ranked.shortage_ordinal") == F.lit(1))))
        shortages = shortages.select(
            F.col("fulfillment_shortage_ranked.tenant"),
            F.col("fulfillment_shortage_ranked.warehouse_id"),
            F.col("fulfillment_shortage_ranked.product_id"),
            F.col("fulfillment_shortage_ranked.first_shortage_at"),
            F.col("fulfillment_shortage_ranked.shortage_quantity"),
            F.col("fulfillment_shortage_ranked.projected_available_quantity"),
            F.col("fulfillment_shortage_ranked.safety_stock_quantity"),
            F.col("fulfillment_shortage_ranked.reason"),
        )

        # Step method: shortages
        shortages = shortages.alias("fulfillment_shortage")
        assert_schema(shortages, FULFILLMENT_SHORTAGE_SCHEMA, name="FulfillmentShortage", mode="strict")
        return TransformResult({"shortages": shortages}, single=True, schema={"shortages": FULFILLMENT_SHORTAGE_SCHEMA})
