# Generated by Structure. Do not edit by hand.
# Source: examples.search.schemas.analytics

from pyspark.sql import types as T


DOCUMENT_FEATURES_SCHEMA = T.StructType([
    T.StructField("document_id", T.StringType(), False),
    T.StructField("collection_id", T.StringType(), False),
    T.StructField("source", T.StringType(), False),
    T.StructField("language", T.StringType(), False),
    T.StructField("title", T.StringType(), False),
    T.StructField("url", T.StringType(), True),
    T.StructField("normalized_title", T.StringType(), True),
    T.StructField("normalized_content", T.StringType(), False),
    T.StructField("title_starts_with_the", T.BooleanType(), True),
    T.StructField("title_ends_with_guide", T.BooleanType(), True),
    T.StructField("url_is_https", T.BooleanType(), True),
    T.StructField("content_contains_structure", T.BooleanType(), False),
    T.StructField("content_like_guide", T.BooleanType(), False),
    T.StructField("content_ilike_structure", T.BooleanType(), False),
    T.StructField("content_matches_sentence", T.BooleanType(), False),
    T.StructField("title_prefix", T.StringType(), False),
    T.StructField("title_words", T.ArrayType(T.StringType(), containsNull=False), False),
    T.StructField("leading_title_words", T.ArrayType(T.StringType(), containsNull=False), False),
    T.StructField("sorted_title_words", T.ArrayType(T.StringType(), containsNull=False), False),
    T.StructField("title_slug", T.StringType(), False),
    T.StructField("first_number", T.StringType(), False),
    T.StructField("content_length", T.IntegerType(), False),
    T.StructField("title_case", T.StringType(), False),
    T.StructField("reversed_title", T.StringType(), False),
    T.StructField("translated_title", T.StringType(), False),
    T.StructField("structure_position", T.IntegerType(), False),
    T.StructField("title_distance_to_guide", T.IntegerType(), False),
    T.StructField("display_name", T.StringType(), False),
    T.StructField("title_hash", T.IntegerType(), False),
    T.StructField("content_sha2", T.StringType(), False),
    T.StructField("harvest_year", T.IntegerType(), False),
    T.StructField("age_days", T.IntegerType(), True),
    T.StructField("content_length_sqrt", T.DoubleType(), False),
    T.StructField("content_length_log", T.DoubleType(), False),
    T.StructField("rounded_content_length", T.DoubleType(), False),
    T.StructField("content_length_sign", T.DoubleType(), False),
    T.StructField("source_recency_rank", T.LongType(), False),
])

SENTENCE_STATISTICS_SCHEMA = T.StructType([
    T.StructField("sentence_id", T.StringType(), False),
    T.StructField("document_id", T.StringType(), False),
    T.StructField("paragraph_id", T.StringType(), False),
    T.StructField("section_id", T.StringType(), False),
    T.StructField("ordinal", T.IntegerType(), False),
    T.StructField("word_count", T.LongType(), False),
    T.StructField("distinct_words", T.LongType(), False),
    T.StructField("average_word_length", T.DoubleType(), True),
])

PARAGRAPH_STATISTICS_SCHEMA = T.StructType([
    T.StructField("paragraph_id", T.StringType(), False),
    T.StructField("document_id", T.StringType(), False),
    T.StructField("section_id", T.StringType(), False),
    T.StructField("ordinal", T.IntegerType(), False),
    T.StructField("word_count", T.LongType(), False),
    T.StructField("sentence_count", T.LongType(), False),
    T.StructField("average_word_length", T.DoubleType(), True),
])

SECTION_STATISTICS_SCHEMA = T.StructType([
    T.StructField("section_id", T.StringType(), False),
    T.StructField("document_id", T.StringType(), False),
    T.StructField("section_ordinal", T.IntegerType(), False),
    T.StructField("heading", T.StringType(), False),
    T.StructField("paragraph_count", T.LongType(), False),
    T.StructField("sentence_count", T.LongType(), False),
    T.StructField("word_count", T.LongType(), False),
    T.StructField("average_word_length", T.DoubleType(), True),
])

DOCUMENT_STATISTICS_SCHEMA = T.StructType([
    T.StructField("document_id", T.StringType(), False),
    T.StructField("section_count", T.LongType(), False),
    T.StructField("paragraph_count", T.LongType(), False),
    T.StructField("sentence_count", T.LongType(), False),
    T.StructField("word_count", T.LongType(), False),
    T.StructField("distinct_words", T.LongType(), False),
    T.StructField("average_word_length", T.DoubleType(), True),
])

CORPUS_STATISTICS_SCHEMA = T.StructType([
    T.StructField("corpus", T.StringType(), False),
    T.StructField("document_count", T.LongType(), False),
    T.StructField("average_sections_per_document", T.DoubleType(), False),
    T.StructField("average_paragraphs_per_document", T.DoubleType(), False),
    T.StructField("average_sentences_per_document", T.DoubleType(), False),
    T.StructField("average_words_per_document", T.DoubleType(), False),
    T.StructField("average_distinct_words_per_document", T.DoubleType(), True),
    T.StructField("median_document_average_word_length", T.DoubleType(), True),
    T.StructField("document_average_word_length_skewness", T.DoubleType(), True),
    T.StructField("document_average_word_length_kurtosis", T.DoubleType(), True),
])

CORPUS_VOCABULARY_SCHEMA = T.StructType([
    T.StructField("corpus", T.StringType(), False),
    T.StructField("estimated_distinct_words", T.LongType(), False),
])

SIMILAR_DOCUMENT_SCHEMA = T.StructType([
    T.StructField("left_document_id", T.StringType(), False),
    T.StructField("right_document_id", T.StringType(), False),
    T.StructField("source", T.StringType(), False),
    T.StructField("language", T.StringType(), False),
    T.StructField("title_prefix", T.StringType(), False),
    T.StructField("title_distance", T.IntegerType(), False),
    T.StructField("content_distance", T.IntegerType(), False),
])
