# Generated by Structure. Do not edit by hand.
# Source: examples.search.schemas.evaluation.behavior

from pyspark.sql import types as T
from examples.structure_generated.search.pyspark.schemas.TimeWindow import TIME_WINDOW_SCHEMA
from examples.structure_generated.search.pyspark.schemas.params import EVALUATION_PARAMS_SCHEMA


DOCUMENT_SEARCH_REQUEST_BEHAVIOR_SCHEMA = T.StructType([
    T.StructField("window", TIME_WINDOW_SCHEMA, False),
    T.StructField("params", EVALUATION_PARAMS_SCHEMA, True),
    T.StructField("experiment_id", T.StringType(), False),
    T.StructField("search_request_id", T.StringType(), False),
    T.StructField("ranking_version", T.StringType(), False),
    T.StructField("query", T.StringType(), False),
    T.StructField("result_count", T.LongType(), False),
    T.StructField("clicked_result_count", T.LongType(), False),
    T.StructField("long_clicked_result_count", T.LongType(), False),
    T.StructField("has_click", T.BooleanType(), True),
    T.StructField("has_long_click", T.BooleanType(), True),
    T.StructField("first_click_rank", T.LongType(), True),
    T.StructField("first_long_click_rank", T.LongType(), True),
    T.StructField("reciprocal_first_long_click_rank", T.DoubleType(), False),
])

DAILY_DOCUMENT_SEARCH_BEHAVIOR_SCHEMA = T.StructType([
    T.StructField("window", TIME_WINDOW_SCHEMA, False),
    T.StructField("params", EVALUATION_PARAMS_SCHEMA, True),
    T.StructField("experiment_id", T.StringType(), False),
    T.StructField("ranking_version", T.StringType(), False),
    T.StructField("request_count", T.LongType(), False),
    T.StructField("zero_result_request_count", T.LongType(), False),
    T.StructField("clicked_request_count", T.LongType(), False),
    T.StructField("long_clicked_request_count", T.LongType(), False),
    T.StructField("no_click_request_count", T.LongType(), False),
    T.StructField("no_long_click_request_count", T.LongType(), False),
    T.StructField("raw_click_count", T.LongType(), False),
    T.StructField("raw_long_click_count", T.LongType(), False),
    T.StructField("mean_first_click_rank", T.DoubleType(), True),
    T.StructField("mean_first_long_click_rank", T.DoubleType(), True),
    T.StructField("mean_reciprocal_first_long_click_rank", T.DoubleType(), False),
    T.StructField("ips_long_click_rate", T.DoubleType(), True),
    T.StructField("ips_dwell_credit_per_impression", T.DoubleType(), True),
])

BEHAVIOR_REQUEST_SCHEMA = T.StructType([
    T.StructField("window", TIME_WINDOW_SCHEMA, False),
    T.StructField("params", EVALUATION_PARAMS_SCHEMA, True),
    T.StructField("experiment_id", T.StringType(), False),
    T.StructField("search_request_id", T.StringType(), False),
    T.StructField("ranking_version", T.StringType(), False),
    T.StructField("query", T.StringType(), False),
])

BEHAVIOR_IMPRESSION_SCHEMA = T.StructType(BEHAVIOR_REQUEST_SCHEMA.fields + [
    T.StructField("impression_id", T.StringType(), False),
    T.StructField("shown_at", T.TimestampType(), False),
    T.StructField("document_id", T.StringType(), False),
    T.StructField("position", T.LongType(), False),
    T.StructField("examination_propensity", T.DoubleType(), False),
    T.StructField("click_count", T.LongType(), False),
    T.StructField("long_click_count", T.LongType(), False),
    T.StructField("dwell_credit", T.DoubleType(), False),
])

BEHAVIOR_EXPOSURE_SCHEMA = T.StructType([
    T.StructField("window", TIME_WINDOW_SCHEMA, False),
    T.StructField("params", EVALUATION_PARAMS_SCHEMA, True),
    T.StructField("experiment_id", T.StringType(), False),
    T.StructField("ranking_version", T.StringType(), False),
    T.StructField("ips_impression_weight", T.DoubleType(), False),
    T.StructField("ips_long_click_weight", T.DoubleType(), False),
    T.StructField("ips_dwell_credit", T.DoubleType(), False),
])

BEHAVIOR_REQUEST_METRICS_SCHEMA = T.StructType(DOCUMENT_SEARCH_REQUEST_BEHAVIOR_SCHEMA.fields + [
    T.StructField("raw_click_count", T.LongType(), False),
    T.StructField("raw_long_click_count", T.LongType(), False),
])

BEHAVIOR_REQUEST_TOTALS_SCHEMA = T.StructType(BEHAVIOR_REQUEST_METRICS_SCHEMA.fields)

BEHAVIOR_DAILY_COUNTS_SCHEMA = T.StructType(DAILY_DOCUMENT_SEARCH_BEHAVIOR_SCHEMA.fields)
