# Generated by Structure. Do not edit by hand.
# Source: examples.search.schemas.scoring.bm25

from pyspark.sql import types as T
from examples.structure_generated.search.pyspark.schemas.search import DOCUMENT_SEARCH_TARGET_SCHEMA, PARAGRAPH_SEARCH_TARGET_SCHEMA, SECTION_SEARCH_TARGET_SCHEMA, SENTENCE_SEARCH_TARGET_SCHEMA


DOCUMENT_BM25_SCORE_SCHEMA = T.StructType(DOCUMENT_SEARCH_TARGET_SCHEMA.fields + [
    T.StructField("score_bm25", T.DoubleType(), False),
])

SECTION_BM25_SCORE_SCHEMA = T.StructType(SECTION_SEARCH_TARGET_SCHEMA.fields + [
    T.StructField("score_bm25", T.DoubleType(), False),
])

PARAGRAPH_BM25_SCORE_SCHEMA = T.StructType(PARAGRAPH_SEARCH_TARGET_SCHEMA.fields + [
    T.StructField("score_bm25", T.DoubleType(), False),
])

SENTENCE_BM25_SCORE_SCHEMA = T.StructType(SENTENCE_SEARCH_TARGET_SCHEMA.fields + [
    T.StructField("score_bm25", T.DoubleType(), False),
])
