# Generated by Structure. Do not edit by hand.
# Source: examples.search.schemas.chunking.intermediate

from pyspark.sql import types as T


DOCUMENT_LINE_SCHEMA = T.StructType([
    T.StructField("line", T.StringType(), False),
    T.StructField("span_start", T.LongType(), False),
    T.StructField("span_end", T.LongType(), False),
    T.StructField("heading", T.StringType(), True),
    T.StructField("heading_span_start", T.LongType(), True),
    T.StructField("heading_span_end", T.LongType(), True),
    T.StructField("is_blank", T.BooleanType(), False),
])

EXPANDED_DOCUMENT_LINE_SCHEMA = T.StructType([
    T.StructField("ordinal", T.LongType(), False),
    T.StructField("line", T.StringType(), False),
    T.StructField("span_start", T.LongType(), False),
    T.StructField("span_end", T.LongType(), False),
    T.StructField("heading", T.StringType(), True),
    T.StructField("heading_span_start", T.LongType(), True),
    T.StructField("heading_span_end", T.LongType(), True),
    T.StructField("is_blank", T.BooleanType(), False),
])

MARKED_DOCUMENT_LINE_SCHEMA = T.StructType([
    T.StructField("document_id", T.StringType(), False),
    T.StructField("line_ordinal", T.LongType(), False),
    T.StructField("line", T.StringType(), False),
    T.StructField("span_start", T.LongType(), False),
    T.StructField("span_end", T.LongType(), False),
    T.StructField("heading", T.StringType(), True),
    T.StructField("heading_span_start", T.LongType(), True),
    T.StructField("heading_span_end", T.LongType(), True),
    T.StructField("is_blank", T.BooleanType(), False),
    T.StructField("section_ordinal", T.LongType(), False),
    T.StructField("paragraph_group", T.LongType(), False),
])

PARAGRAPH_LINE_SCHEMA = T.StructType([
    T.StructField("document_id", T.StringType(), False),
    T.StructField("section_ordinal", T.LongType(), False),
    T.StructField("paragraph_group", T.LongType(), False),
    T.StructField("line_ordinal", T.LongType(), False),
    T.StructField("line", T.StringType(), False),
    T.StructField("span_start", T.LongType(), False),
    T.StructField("span_end", T.LongType(), False),
])

SECTION_HEADING_SCHEMA = T.StructType([
    T.StructField("document_id", T.StringType(), False),
    T.StructField("section_ordinal", T.LongType(), False),
    T.StructField("heading", T.StringType(), False),
    T.StructField("heading_span_start", T.LongType(), True),
    T.StructField("heading_span_end", T.LongType(), True),
])

PARAGRAPH_LINE_GROUP_SCHEMA = T.StructType([
    T.StructField("id", T.StringType(), False),
    T.StructField("document_id", T.StringType(), False),
    T.StructField("section_id", T.StringType(), False),
    T.StructField("section_ordinal", T.LongType(), False),
    T.StructField("paragraph_group", T.LongType(), False),
    T.StructField("span_start", T.LongType(), False),
    T.StructField("span_end", T.LongType(), False),
])

PARAGRAPH_CONTENT_SCHEMA = T.StructType([
    T.StructField("id", T.StringType(), False),
    T.StructField("document_id", T.StringType(), False),
    T.StructField("section_id", T.StringType(), False),
    T.StructField("section_ordinal", T.LongType(), False),
    T.StructField("paragraph_group", T.LongType(), False),
    T.StructField("span_start", T.LongType(), False),
    T.StructField("span_end", T.LongType(), False),
])

PARAGRAPH_DRAFT_SCHEMA = T.StructType([
    T.StructField("id", T.StringType(), False),
    T.StructField("document_id", T.StringType(), False),
    T.StructField("section_id", T.StringType(), False),
    T.StructField("section_ordinal", T.LongType(), False),
    T.StructField("ordinal", T.IntegerType(), False),
    T.StructField("span_start", T.LongType(), False),
    T.StructField("span_end", T.LongType(), False),
])

SECTION_KEY_SCHEMA = T.StructType([
    T.StructField("id", T.StringType(), False),
    T.StructField("document_id", T.StringType(), False),
    T.StructField("section_ordinal", T.LongType(), False),
    T.StructField("ordinal", T.IntegerType(), False),
    T.StructField("span_start", T.LongType(), False),
    T.StructField("span_end", T.LongType(), False),
])

SENTENCE_TEXT_SCHEMA = T.StructType([
    T.StructField("local_start", T.LongType(), False),
    T.StructField("local_end", T.LongType(), False),
    T.StructField("sentence_content", T.StringType(), False),
])

MATERIALIZED_PARAGRAPH_SCHEMA = T.StructType([
    T.StructField("id", T.StringType(), False),
    T.StructField("document_id", T.StringType(), False),
    T.StructField("section_id", T.StringType(), False),
    T.StructField("ordinal", T.IntegerType(), False),
    T.StructField("span_start", T.LongType(), False),
    T.StructField("span_end", T.LongType(), False),
    T.StructField("content", T.StringType(), False),
])

MATERIALIZED_SECTION_SCHEMA = T.StructType([
    T.StructField("id", T.StringType(), False),
    T.StructField("document_id", T.StringType(), False),
    T.StructField("ordinal", T.IntegerType(), False),
    T.StructField("span_start", T.LongType(), False),
    T.StructField("span_end", T.LongType(), False),
    T.StructField("heading_span_start", T.LongType(), True),
    T.StructField("heading_span_end", T.LongType(), True),
    T.StructField("heading", T.StringType(), False),
])

MATERIALIZED_SENTENCE_SCHEMA = T.StructType([
    T.StructField("id", T.StringType(), False),
    T.StructField("document_id", T.StringType(), False),
    T.StructField("section_id", T.StringType(), False),
    T.StructField("paragraph_id", T.StringType(), False),
    T.StructField("paragraph_ordinal", T.IntegerType(), False),
    T.StructField("ordinal", T.IntegerType(), False),
    T.StructField("span_start", T.LongType(), False),
    T.StructField("span_end", T.LongType(), False),
    T.StructField("content", T.StringType(), False),
])

EXPANDED_SENTENCE_TEXT_SCHEMA = T.StructType([
    T.StructField("position", T.LongType(), False),
    T.StructField("local_start", T.LongType(), False),
    T.StructField("local_end", T.LongType(), False),
    T.StructField("sentence_content", T.StringType(), False),
])
