# Generated by Structure. Do not edit by hand.
# Source: examples.search.schemas.chunking.chunk

from pyspark.sql import types as T


DOCUMENT_LINE_SCHEMA = T.StructType([
    T.StructField("line", T.StringType(), False),
])

EXPANDED_DOCUMENT_LINE_SCHEMA = T.StructType([
    T.StructField("ordinal", T.LongType(), False),
    T.StructField("line", T.StringType(), False),
])

MARKED_DOCUMENT_LINE_SCHEMA = T.StructType([
    T.StructField("document_id", T.StringType(), False),
    T.StructField("line_ordinal", T.LongType(), False),
    T.StructField("line", T.StringType(), False),
    T.StructField("heading", T.StringType(), True),
    T.StructField("is_blank", T.BooleanType(), False),
    T.StructField("section_ordinal", T.LongType(), False),
    T.StructField("paragraph_group", T.LongType(), False),
])

PARAGRAPH_LINE_SCHEMA = T.StructType([
    T.StructField("document_id", T.StringType(), False),
    T.StructField("section_ordinal", T.LongType(), False),
    T.StructField("paragraph_group", T.LongType(), False),
    T.StructField("line_ordinal", T.LongType(), False),
    T.StructField("line", T.StringType(), False),
])

SECTION_HEADING_SCHEMA = T.StructType([
    T.StructField("document_id", T.StringType(), False),
    T.StructField("section_ordinal", T.LongType(), False),
    T.StructField("heading", T.StringType(), False),
])

PARAGRAPH_LINE_GROUP_SCHEMA = T.StructType([
    T.StructField("id", T.StringType(), False),
    T.StructField("document_id", T.StringType(), False),
    T.StructField("section_id", T.StringType(), False),
    T.StructField("section_ordinal", T.LongType(), False),
    T.StructField("paragraph_group", T.LongType(), False),
    T.StructField("lines", T.ArrayType(T.StringType(), containsNull=False), False),
])

PARAGRAPH_CONTENT_SCHEMA = T.StructType([
    T.StructField("id", T.StringType(), False),
    T.StructField("document_id", T.StringType(), False),
    T.StructField("section_id", T.StringType(), False),
    T.StructField("section_ordinal", T.LongType(), False),
    T.StructField("paragraph_group", T.LongType(), False),
    T.StructField("content", T.StringType(), False),
])

PARAGRAPH_DRAFT_SCHEMA = T.StructType([
    T.StructField("id", T.StringType(), False),
    T.StructField("document_id", T.StringType(), False),
    T.StructField("section_id", T.StringType(), False),
    T.StructField("section_ordinal", T.LongType(), False),
    T.StructField("ordinal", T.IntegerType(), False),
    T.StructField("content", T.StringType(), False),
    T.StructField("search_query_id", T.StringType(), True),
    T.StructField("score_overlap", T.DoubleType(), True),
    T.StructField("score_bm25", T.DoubleType(), True),
])

SECTION_KEY_SCHEMA = T.StructType([
    T.StructField("id", T.StringType(), False),
    T.StructField("document_id", T.StringType(), False),
    T.StructField("section_ordinal", T.LongType(), False),
    T.StructField("ordinal", T.IntegerType(), False),
])

SENTENCE_TEXT_SCHEMA = T.StructType([
    T.StructField("sentence_content", T.StringType(), False),
])

EXPANDED_SENTENCE_TEXT_SCHEMA = T.StructType([
    T.StructField("position", T.LongType(), False),
    T.StructField("sentence_content", T.StringType(), False),
])

WORD_TEXT_SCHEMA = T.StructType([
    T.StructField("word_token", T.StringType(), False),
])

EXPANDED_WORD_TEXT_SCHEMA = T.StructType([
    T.StructField("position", T.LongType(), False),
    T.StructField("word_token", T.StringType(), False),
])
