# Generated by Structure. Do not edit by hand.
# Source: examples.search.schemas.clicks

from pyspark.sql import types as T
from examples.structure_generated.search.pyspark.schemas.TimeWindow import TIME_WINDOW_SCHEMA


SEARCH_REQUEST_SCHEMA = T.StructType([
    T.StructField("id", T.StringType(), False),
    T.StructField("query_id", T.StringType(), False),
    T.StructField("requested_at", T.TimestampType(), False),
    T.StructField("query", T.StringType(), False),
    T.StructField("experiment_id", T.StringType(), False),
    T.StructField("ranking_version", T.StringType(), False),
    T.StructField("user_id", T.StringType(), True),
])

IMPRESSION_SCHEMA = T.StructType([
    T.StructField("id", T.StringType(), False),
    T.StructField("search_request_id", T.StringType(), False),
    T.StructField("shown_at", T.TimestampType(), False),
    T.StructField("query", T.StringType(), False),
    T.StructField("document_id", T.StringType(), False),
    T.StructField("position", T.LongType(), False),
    T.StructField("examination_propensity", T.DoubleType(), False),
    T.StructField("user_id", T.StringType(), True),
])

CLICK_SCHEMA = T.StructType([
    T.StructField("id", T.StringType(), False),
    T.StructField("occurred_at", T.TimestampType(), False),
    T.StructField("impression_id", T.StringType(), False),
    T.StructField("dwell_seconds", T.DoubleType(), False),
    T.StructField("user_id", T.StringType(), True),
])

DAILY_IMPRESSIONS_SCHEMA = T.StructType([
    T.StructField("window", TIME_WINDOW_SCHEMA, False),
    T.StructField("query", T.StringType(), False),
    T.StructField("document_id", T.StringType(), False),
    T.StructField("position", T.LongType(), False),
    T.StructField("examination_propensity", T.DoubleType(), False),
    T.StructField("user_id", T.StringType(), True),
    T.StructField("band_id", T.StringType(), True),
    T.StructField("impression_count", T.LongType(), False),
])

DAILY_CLICKS_SCHEMA = T.StructType([
    T.StructField("window", TIME_WINDOW_SCHEMA, False),
    T.StructField("query", T.StringType(), False),
    T.StructField("document_id", T.StringType(), False),
    T.StructField("position", T.LongType(), False),
    T.StructField("examination_propensity", T.DoubleType(), False),
    T.StructField("user_id", T.StringType(), True),
    T.StructField("band_id", T.StringType(), True),
    T.StructField("click_count", T.LongType(), False),
    T.StructField("clicked_impression_count", T.LongType(), False),
    T.StructField("dwell_seconds", T.DoubleType(), False),
    T.StructField("dwell_credit", T.DoubleType(), False),
    T.StructField("long_click_count", T.LongType(), False),
])
