# Generated by Structure. Do not edit by hand.
# Source: examples.search.schemas.training.data

from pyspark.sql import types as T


DOCUMENT_TRAINING_DATA_SCHEMA = T.StructType([
    T.StructField("search_query_id", T.StringType(), False),
    T.StructField("document_id", T.StringType(), False),
    T.StructField("relevance_grade", T.LongType(), False),
    T.StructField("lexical_score", T.DoubleType(), False),
    T.StructField("query_token_count", T.LongType(), False),
    T.StructField("query_distinct_token_count", T.LongType(), False),
    T.StructField("document_content_length", T.IntegerType(), False),
    T.StructField("document_url_is_https", T.BooleanType(), True),
])
