# Generated by Structure. Do not edit by hand.
# Source: examples.search.schemas.inference

from pyspark.sql import types as T


INFERENCE_POLICY_SCHEMA = T.StructType([
    T.StructField("provider_id", T.StringType(), False),
    T.StructField("model_id", T.StringType(), False),
    T.StructField("model_version", T.StringType(), False),
    T.StructField("content_revision", T.StringType(), False),
    T.StructField("dimension", T.LongType(), False),
    T.StructField("experiment_id", T.StringType(), False),
    T.StructField("inferred_at", T.TimestampType(), False),
])

QUERY_INFERENCE_RESULT_SCHEMA = T.StructType([
    T.StructField("query_id", T.StringType(), False),
    T.StructField("vector", T.ArrayType(T.DoubleType(), containsNull=False), True),
    T.StructField("status", T.StringType(), False),
    T.StructField("error_code", T.StringType(), True),
    T.StructField("diagnostic", T.StringType(), True),
])

DOCUMENT_INFERENCE_RESULT_SCHEMA = T.StructType([
    T.StructField("document_id", T.StringType(), False),
    T.StructField("vector", T.ArrayType(T.DoubleType(), containsNull=False), True),
    T.StructField("status", T.StringType(), False),
    T.StructField("error_code", T.StringType(), True),
    T.StructField("diagnostic", T.StringType(), True),
])

QUERY_INFERENCE_STATUS_SCHEMA = T.StructType([
    T.StructField("query_id", T.StringType(), False),
    T.StructField("provider_id", T.StringType(), False),
    T.StructField("model_id", T.StringType(), False),
    T.StructField("model_version", T.StringType(), False),
    T.StructField("status", T.StringType(), False),
    T.StructField("error_code", T.StringType(), True),
    T.StructField("diagnostic", T.StringType(), True),
    T.StructField("inferred_at", T.TimestampType(), False),
])

DOCUMENT_INFERENCE_STATUS_SCHEMA = T.StructType([
    T.StructField("document_id", T.StringType(), False),
    T.StructField("provider_id", T.StringType(), False),
    T.StructField("model_id", T.StringType(), False),
    T.StructField("model_version", T.StringType(), False),
    T.StructField("status", T.StringType(), False),
    T.StructField("error_code", T.StringType(), True),
    T.StructField("diagnostic", T.StringType(), True),
    T.StructField("inferred_at", T.TimestampType(), False),
])
