# Generated by Structure. Do not edit by hand.
# Source: examples.search.schemas.similarities.query

from pyspark.sql import types as T
from examples.structure_generated.search.pyspark.schemas.similarity import DOCUMENT_SIMILARITY_QUERY_SCHEMA, PARAGRAPH_SIMILARITY_QUERY_SCHEMA, SECTION_SIMILARITY_QUERY_SCHEMA, SENTENCE_SIMILARITY_QUERY_SCHEMA


DOCUMENT_SIMILARITY_QUERY_TEXT_SCHEMA = T.StructType(DOCUMENT_SIMILARITY_QUERY_SCHEMA.fields + [
    T.StructField("content_tokens", T.ArrayType(T.StringType(), containsNull=False), False),
])

SECTION_SIMILARITY_QUERY_TEXT_SCHEMA = T.StructType(SECTION_SIMILARITY_QUERY_SCHEMA.fields + [
    T.StructField("content_tokens", T.ArrayType(T.StringType(), containsNull=False), False),
])

PARAGRAPH_SIMILARITY_QUERY_TEXT_SCHEMA = T.StructType(PARAGRAPH_SIMILARITY_QUERY_SCHEMA.fields + [
    T.StructField("content_tokens", T.ArrayType(T.StringType(), containsNull=False), False),
])

SENTENCE_SIMILARITY_QUERY_TEXT_SCHEMA = T.StructType(SENTENCE_SIMILARITY_QUERY_SCHEMA.fields + [
    T.StructField("content_tokens", T.ArrayType(T.StringType(), containsNull=False), False),
])
