# Generated by Structure. Do not edit by hand.
# Source: examples.search.schemas.search

from pyspark.sql import types as T


SEARCH_QUERY_SCHEMA = T.StructType([
    T.StructField("id", T.StringType(), False),
    T.StructField("queryset", T.StringType(), False),
    T.StructField("content", T.StringType(), False),
    T.StructField("requested_at", T.TimestampType(), False),
    T.StructField("labels", T.MapType(T.StringType(), T.LongType(), valueContainsNull=False), False),
    T.StructField("is_question", T.BooleanType(), False),
    T.StructField("is_time_sensitive", T.BooleanType(), False),
    T.StructField("language", T.StringType(), True),
])

SENTENCE_SEARCH_RESULT_SCHEMA = T.StructType([
    T.StructField("search_query_id", T.StringType(), False),
    T.StructField("experiment_id", T.StringType(), True),
    T.StructField("rank", T.LongType(), False),
    T.StructField("document_id", T.StringType(), False),
    T.StructField("section_id", T.StringType(), False),
    T.StructField("paragraph_id", T.StringType(), False),
    T.StructField("sentence_id", T.StringType(), False),
    T.StructField("content", T.StringType(), False),
    T.StructField("score", T.DoubleType(), False),
])

DOCUMENT_SEARCH_TARGET_SCHEMA = T.StructType([
    T.StructField("query_id", T.StringType(), False),
    T.StructField("document_id", T.StringType(), False),
])

SECTION_SEARCH_TARGET_SCHEMA = T.StructType(DOCUMENT_SEARCH_TARGET_SCHEMA.fields + [
    T.StructField("section_id", T.StringType(), False),
])

PARAGRAPH_SEARCH_TARGET_SCHEMA = T.StructType(SECTION_SEARCH_TARGET_SCHEMA.fields + [
    T.StructField("paragraph_id", T.StringType(), False),
])

SENTENCE_SEARCH_TARGET_SCHEMA = T.StructType(PARAGRAPH_SEARCH_TARGET_SCHEMA.fields + [
    T.StructField("sentence_id", T.StringType(), False),
])

SCORE_POLICY_SCHEMA = T.StructType([
    T.StructField("maximum_age_days", T.LongType(), False),
    T.StructField("scored_at", T.TimestampType(), False),
    T.StructField("effective_at", T.TimestampType(), False),
    T.StructField("document_bm25_weight", T.DoubleType(), False),
    T.StructField("document_overlap_weight", T.DoubleType(), False),
    T.StructField("section_bm25_weight", T.DoubleType(), False),
    T.StructField("section_overlap_weight", T.DoubleType(), False),
    T.StructField("paragraph_bm25_weight", T.DoubleType(), False),
    T.StructField("paragraph_overlap_weight", T.DoubleType(), False),
    T.StructField("sentence_bm25_weight", T.DoubleType(), False),
    T.StructField("sentence_overlap_weight", T.DoubleType(), False),
])

QUERY_POPULARITY_SCHEMA = T.StructType([
    T.StructField("query", T.StringType(), False),
    T.StructField("impression_count", T.LongType(), False),
])

DOCUMENT_SCORE_SCHEMA = T.StructType(DOCUMENT_SEARCH_TARGET_SCHEMA.fields + [
    T.StructField("experiment_id", T.StringType(), True),
    T.StructField("scored_at", T.TimestampType(), False),
    T.StructField("score", T.DoubleType(), False),
])

SECTION_SCORE_SCHEMA = T.StructType(SECTION_SEARCH_TARGET_SCHEMA.fields + [
    T.StructField("experiment_id", T.StringType(), True),
    T.StructField("scored_at", T.TimestampType(), False),
    T.StructField("score", T.DoubleType(), False),
])

PARAGRAPH_SCORE_SCHEMA = T.StructType(PARAGRAPH_SEARCH_TARGET_SCHEMA.fields + [
    T.StructField("experiment_id", T.StringType(), True),
    T.StructField("scored_at", T.TimestampType(), False),
    T.StructField("score", T.DoubleType(), False),
])

SENTENCE_SCORE_SCHEMA = T.StructType(SENTENCE_SEARCH_TARGET_SCHEMA.fields + [
    T.StructField("experiment_id", T.StringType(), True),
    T.StructField("scored_at", T.TimestampType(), False),
    T.StructField("score", T.DoubleType(), False),
])

DOCUMENT_FEEDBACK_OPTION_SCHEMA = T.StructType(DOCUMENT_SEARCH_CANDIDATE_SCHEMA.fields + [
    T.StructField("feedback_band_id", T.StringType(), True),
    T.StructField("fallback_ordinal", T.LongType(), False),
    T.StructField("minimum_band_impressions", T.LongType(), False),
])

QUERY_DOCUMENT_FEEDBACK_SCHEMA = T.StructType([
    T.StructField("search_query_id", T.StringType(), False),
    T.StructField("experiment_id", T.StringType(), True),
    T.StructField("user_band_id", T.StringType(), True),
    T.StructField("candidate_rank", T.LongType(), False),
    T.StructField("document_id", T.StringType(), False),
    T.StructField("query_feedback", T.DoubleType(), True),
])

POPULARITY_FEEDBACK_SCHEMA = T.StructType([
    T.StructField("search_query_id", T.StringType(), False),
    T.StructField("experiment_id", T.StringType(), True),
    T.StructField("user_band_id", T.StringType(), True),
    T.StructField("candidate_rank", T.LongType(), False),
    T.StructField("document_id", T.StringType(), False),
    T.StructField("popularity_feedback", T.DoubleType(), True),
])

DOCUMENT_SEARCH_CANDIDATE_SCHEMA = T.StructType([
    T.StructField("search_query_id", T.StringType(), False),
    T.StructField("experiment_id", T.StringType(), True),
    T.StructField("user_band_id", T.StringType(), True),
    T.StructField("band_id", T.StringType(), True),
    T.StructField("query", T.StringType(), False),
    T.StructField("candidate_rank", T.LongType(), False),
    T.StructField("document_id", T.StringType(), False),
    T.StructField("title", T.StringType(), False),
    T.StructField("url", T.StringType(), True),
    T.StructField("score", T.DoubleType(), False),
    T.StructField("retrieval_score", T.DoubleType(), False),
    T.StructField("score_feedback", T.DoubleType(), False),
    T.StructField("score_rank", T.DoubleType(), False),
    T.StructField("score_weight", T.DoubleType(), False),
    T.StructField("feedback_weight", T.DoubleType(), False),
    T.StructField("lexical_rank", T.LongType(), True),
    T.StructField("vector_rank", T.LongType(), True),
    T.StructField("vector_similarity", T.DoubleType(), True),
    T.StructField("rrf_score", T.DoubleType(), False),
    T.StructField("rrf_k", T.LongType(), False),
    T.StructField("vector_backend", T.StringType(), True),
])

DOCUMENT_SEARCH_RESULT_SCHEMA = T.StructType([
    T.StructField("search_query_id", T.StringType(), False),
    T.StructField("experiment_id", T.StringType(), True),
    T.StructField("user_band_id", T.StringType(), True),
    T.StructField("band_id", T.StringType(), True),
    T.StructField("rank", T.LongType(), False),
    T.StructField("candidate_rank", T.LongType(), False),
    T.StructField("document_id", T.StringType(), False),
    T.StructField("title", T.StringType(), False),
    T.StructField("url", T.StringType(), True),
    T.StructField("score", T.DoubleType(), False),
    T.StructField("retrieval_score", T.DoubleType(), False),
    T.StructField("score_feedback", T.DoubleType(), False),
    T.StructField("score_rank", T.DoubleType(), False),
    T.StructField("lexical_rank", T.LongType(), True),
    T.StructField("vector_rank", T.LongType(), True),
    T.StructField("vector_similarity", T.DoubleType(), True),
    T.StructField("rrf_score", T.DoubleType(), False),
    T.StructField("rrf_k", T.LongType(), False),
    T.StructField("vector_backend", T.StringType(), True),
])
