# Generated by Structure. Do not edit by hand.
# Source: examples.search.schemas.user

from pyspark.sql import types as T


USER_SCHEMA = T.StructType([
    T.StructField("id", T.StringType(), False),
    T.StructField("age", T.LongType(), True),
    T.StructField("gender", T.StringType(), True),
    T.StructField("locale", T.StringType(), True),
    T.StructField("country", T.StringType(), True),
    T.StructField("geo_tag", T.StringType(), True),
    T.StructField("device_type", T.StringType(), True),
    T.StructField("time_zone", T.StringType(), True),
])

BAND_SCHEMA = T.StructType([
    T.StructField("id", T.StringType(), False),
    T.StructField("name", T.StringType(), True),
    T.StructField("priority", T.LongType(), False),
    T.StructField("parent_band_id", T.StringType(), True),
    T.StructField("age_start", T.LongType(), True),
    T.StructField("age_end", T.LongType(), True),
    T.StructField("genders", T.ArrayType(T.StringType(), containsNull=False), False),
    T.StructField("locales", T.ArrayType(T.StringType(), containsNull=False), False),
    T.StructField("countries", T.ArrayType(T.StringType(), containsNull=False), False),
    T.StructField("geo_tags", T.ArrayType(T.StringType(), containsNull=False), False),
    T.StructField("device_types", T.ArrayType(T.StringType(), containsNull=False), False),
    T.StructField("time_zones", T.ArrayType(T.StringType(), containsNull=False), False),
])

BAND_MEMBERSHIP_SCHEMA = T.StructType([
    T.StructField("user_id", T.StringType(), False),
    T.StructField("band_id", T.StringType(), True),
    T.StructField("user_band_id", T.StringType(), False),
])

BAND_FALLBACK_SCHEMA = T.StructType([
    T.StructField("user_band_id", T.StringType(), False),
    T.StructField("ordinal", T.LongType(), False),
    T.StructField("user_band_fallback_id", T.StringType(), True),
])

USER_BAND_SCHEMA = T.StructType([
    T.StructField("user_band_id", T.StringType(), False),
    T.StructField("band_ids", T.ArrayType(T.StringType(), containsNull=False), False),
])

USER_BAND_MEMBERSHIP_SCHEMA = T.StructType([
    T.StructField("user_id", T.StringType(), False),
    T.StructField("user_band_id", T.StringType(), True),
])
