# Generated by Structure. Do not edit by hand.
# Source: examples.texts.transforms.index.CreateIndex

from pyspark.sql import DataFrame, SparkSession
from pyspark.sql import functions as F
from pyspark.sql import types as T
from examples.texts.transforms.index import CreateIndex
from examples.texts.transforms.indexing.Index import Index
from examples.structure_generated.texts.runtime.schema_assert import TransformResult, assert_schema, project_schema
from examples.structure_generated.texts.pyspark.schemas.search import DOCUMENT_INDEX_SUMMARY_SCHEMA, DOCUMENT_INDEX_TERM_SCHEMA, PARAGRAPH_INDEX_SUMMARY_SCHEMA, PARAGRAPH_INDEX_TERM_SCHEMA, SECTION_INDEX_SUMMARY_SCHEMA, SECTION_INDEX_TERM_SCHEMA, SENTENCE_INDEX_SUMMARY_SCHEMA, SENTENCE_INDEX_TERM_SCHEMA
from examples.structure_generated.texts.pyspark.schemas.text import WORD_SCHEMA


class IndexGenerated:
    def _step_declare_index_0(self, frames):
        # Step method: declare_index
        declare_index_base = frames["words"].alias("word")
        document_terms = declare_index_base.select(
            F.col("word.document_id"),
            F.col("word.token"),
            F.lit(0).cast(T.LongType()).alias("term_frequency"),
            F.lit(0).cast(T.LongType()).alias("target_word_count"),
            F.lit(0).cast(T.LongType()).alias("target_distinct_terms"),
            F.lit(0).cast(T.LongType()).alias("document_frequency"),
        )
        document_summary = declare_index_base.select(
            F.lit(0).cast(T.LongType()).alias("target_count"),
            F.lit(0.0).alias("average_target_length"),
        )
        section_terms = declare_index_base.select(
            F.col("word.document_id"),
            F.col("word.section_id"),
            F.col("word.token"),
            F.lit(0).cast(T.LongType()).alias("term_frequency"),
            F.lit(0).cast(T.LongType()).alias("target_word_count"),
            F.lit(0).cast(T.LongType()).alias("target_distinct_terms"),
            F.lit(0).cast(T.LongType()).alias("document_frequency"),
        )
        section_summary = declare_index_base.select(
            F.lit(0).cast(T.LongType()).alias("target_count"),
            F.lit(0.0).alias("average_target_length"),
        )
        paragraph_terms = declare_index_base.select(
            F.col("word.document_id"),
            F.col("word.section_id"),
            F.col("word.paragraph_id"),
            F.col("word.token"),
            F.lit(0).cast(T.LongType()).alias("term_frequency"),
            F.lit(0).cast(T.LongType()).alias("target_word_count"),
            F.lit(0).cast(T.LongType()).alias("target_distinct_terms"),
            F.lit(0).cast(T.LongType()).alias("document_frequency"),
        )
        paragraph_summary = declare_index_base.select(
            F.lit(0).cast(T.LongType()).alias("target_count"),
            F.lit(0.0).alias("average_target_length"),
        )
        sentence_terms = declare_index_base.select(
            F.col("word.document_id"),
            F.col("word.section_id"),
            F.col("word.paragraph_id"),
            F.col("word.sentence_id"),
            F.col("word.token"),
            F.lit(0).cast(T.LongType()).alias("term_frequency"),
            F.lit(0).cast(T.LongType()).alias("target_word_count"),
            F.lit(0).cast(T.LongType()).alias("target_distinct_terms"),
            F.lit(0).cast(T.LongType()).alias("document_frequency"),
        )
        sentence_summary = declare_index_base.select(
            F.lit(0).cast(T.LongType()).alias("target_count"),
            F.lit(0.0).alias("average_target_length"),
        )
        document_terms, document_summary, section_terms, section_summary, paragraph_terms, paragraph_summary, sentence_terms, sentence_summary = Index.build(self._impl, words=frames["input:words"], document_terms=document_terms, document_summary=document_summary, section_terms=section_terms, section_summary=section_summary, paragraph_terms=paragraph_terms, paragraph_summary=paragraph_summary, sentence_terms=sentence_terms, sentence_summary=sentence_summary, spark=self.spark, ctx=self.ctx)
        assert_schema(document_terms, DOCUMENT_INDEX_TERM_SCHEMA, name="DocumentIndexTerm", mode="strict")
        return {
            "document_terms": document_terms,
            "document_summary": document_summary,
            "section_terms": section_terms,
            "section_summary": section_summary,
            "paragraph_terms": paragraph_terms,
            "paragraph_summary": paragraph_summary,
            "sentence_terms": sentence_terms,
            "sentence_summary": sentence_summary,
        }


class CreateIndexGenerated(IndexGenerated):

    def __init__(self, *, spark: SparkSession, ctx=None):
        self.spark = spark
        self.ctx = ctx
        self._impl = CreateIndex()

    def run(
        self,
        *,
        words: DataFrame,
    ) -> TransformResult:
        assert_schema(words, WORD_SCHEMA, name="Word", mode="strict")
        _input_words = words
        frames = {
            "words": words,
            "input:words": _input_words,
        }
        frames.update(self._step_declare_index_0(frames))

        # Step method: document_terms
        document_terms = frames["document_terms"].alias("document_index_term")
        assert_schema(document_terms, DOCUMENT_INDEX_TERM_SCHEMA, name="DocumentIndexTerm", mode="strict")

        # Step method: document_summary
        document_summary = frames["document_summary"].alias("document_index_summary")
        assert_schema(document_summary, DOCUMENT_INDEX_SUMMARY_SCHEMA, name="DocumentIndexSummary", mode="strict")

        # Step method: section_terms
        section_terms = frames["section_terms"].alias("section_index_term")
        assert_schema(section_terms, SECTION_INDEX_TERM_SCHEMA, name="SectionIndexTerm", mode="strict")

        # Step method: section_summary
        section_summary = frames["section_summary"].alias("section_index_summary")
        assert_schema(section_summary, SECTION_INDEX_SUMMARY_SCHEMA, name="SectionIndexSummary", mode="strict")

        # Step method: paragraph_terms
        paragraph_terms = frames["paragraph_terms"].alias("paragraph_index_term")
        assert_schema(paragraph_terms, PARAGRAPH_INDEX_TERM_SCHEMA, name="ParagraphIndexTerm", mode="strict")

        # Step method: paragraph_summary
        paragraph_summary = frames["paragraph_summary"].alias("paragraph_index_summary")
        assert_schema(paragraph_summary, PARAGRAPH_INDEX_SUMMARY_SCHEMA, name="ParagraphIndexSummary", mode="strict")

        # Step method: sentence_terms
        sentence_terms = frames["sentence_terms"].alias("sentence_index_term")
        assert_schema(sentence_terms, SENTENCE_INDEX_TERM_SCHEMA, name="SentenceIndexTerm", mode="strict")

        # Step method: sentence_summary
        sentence_summary = frames["sentence_summary"].alias("sentence_index_summary")
        assert_schema(sentence_summary, SENTENCE_INDEX_SUMMARY_SCHEMA, name="SentenceIndexSummary", mode="strict")
        return TransformResult({"document_terms": document_terms, "document_summary": document_summary, "section_terms": section_terms, "section_summary": section_summary, "paragraph_terms": paragraph_terms, "paragraph_summary": paragraph_summary, "sentence_terms": sentence_terms, "sentence_summary": sentence_summary}, single=False, schema={"document_terms": DOCUMENT_INDEX_TERM_SCHEMA, "document_summary": DOCUMENT_INDEX_SUMMARY_SCHEMA, "section_terms": SECTION_INDEX_TERM_SCHEMA, "section_summary": SECTION_INDEX_SUMMARY_SCHEMA, "paragraph_terms": PARAGRAPH_INDEX_TERM_SCHEMA, "paragraph_summary": PARAGRAPH_INDEX_SUMMARY_SCHEMA, "sentence_terms": SENTENCE_INDEX_TERM_SCHEMA, "sentence_summary": SENTENCE_INDEX_SUMMARY_SCHEMA})
