# Generated by Structure. Do not edit by hand.
# Source: examples.texts.transforms.search.ScoreCorpus.ScoreCorpus

from pyspark.sql import DataFrame, SparkSession
from pyspark.sql import functions as F
from pyspark.sql import types as T
from examples.texts.transforms.search.ScoreBm25 import ScoreBm25
from examples.texts.transforms.search.ScoreCorpus import ScoreCorpus
from examples.texts.transforms.search.ScoreOverlap import ScoreOverlap
from examples.structure_generated.texts.runtime.schema_assert import TransformResult, assert_schema, project_schema
from examples.structure_generated.texts.pyspark.schemas.search import DOCUMENT_BM25_SCORE_SCHEMA, DOCUMENT_OVERLAP_SCORE_SCHEMA, PARAGRAPH_BM25_SCORE_SCHEMA, PARAGRAPH_OVERLAP_SCORE_SCHEMA, SEARCH_QUERY_SCHEMA, SECTION_BM25_SCORE_SCHEMA, SECTION_OVERLAP_SCORE_SCHEMA, SENTENCE_BM25_SCORE_SCHEMA, SENTENCE_OVERLAP_SCORE_SCHEMA
from examples.structure_generated.texts.pyspark.schemas.text import WORD_SCHEMA


class ScoreOverlapGenerated:
    def _step_declare_overlap_scores_0(self, frames):
        # Step method: declare_overlap_scores
        declare_overlap_scores_base = frames["queries"].alias("search_query")
        document_overlap_scores = declare_overlap_scores_base.select(
            F.col("search_query.id").alias("query_id"),
            F.lit('').alias("document_id"),
            F.lit(0.0).alias("score_overlap"),
        )
        section_overlap_scores = declare_overlap_scores_base.select(
            F.col("search_query.id").alias("query_id"),
            F.lit('').alias("document_id"),
            F.lit('').alias("section_id"),
            F.lit(0.0).alias("score_overlap"),
        )
        paragraph_overlap_scores = declare_overlap_scores_base.select(
            F.col("search_query.id").alias("query_id"),
            F.lit('').alias("document_id"),
            F.lit('').alias("section_id"),
            F.lit('').alias("paragraph_id"),
            F.lit(0.0).alias("score_overlap"),
        )
        sentence_overlap_scores = declare_overlap_scores_base.select(
            F.col("search_query.id").alias("query_id"),
            F.lit('').alias("document_id"),
            F.lit('').alias("section_id"),
            F.lit('').alias("paragraph_id"),
            F.lit('').alias("sentence_id"),
            F.lit(0.0).alias("score_overlap"),
        )
        document_overlap_scores, section_overlap_scores, paragraph_overlap_scores, sentence_overlap_scores = ScoreOverlap.score_overlap(self._impl, queries=frames["input:queries"], words=frames["input:words"], document_overlap_scores=document_overlap_scores, section_overlap_scores=section_overlap_scores, paragraph_overlap_scores=paragraph_overlap_scores, sentence_overlap_scores=sentence_overlap_scores, spark=self.spark, ctx=self.ctx)
        assert_schema(document_overlap_scores, DOCUMENT_OVERLAP_SCORE_SCHEMA, name="DocumentOverlapScore", mode="strict")
        assert_schema(document_overlap_scores, DOCUMENT_OVERLAP_SCORE_SCHEMA, name="DocumentOverlapScore", mode="strict")
        assert_schema(section_overlap_scores, SECTION_OVERLAP_SCORE_SCHEMA, name="SectionOverlapScore", mode="strict")
        assert_schema(paragraph_overlap_scores, PARAGRAPH_OVERLAP_SCORE_SCHEMA, name="ParagraphOverlapScore", mode="strict")
        assert_schema(sentence_overlap_scores, SENTENCE_OVERLAP_SCORE_SCHEMA, name="SentenceOverlapScore", mode="strict")
        return {
            "document_overlap_scores": document_overlap_scores,
            "section_overlap_scores": section_overlap_scores,
            "paragraph_overlap_scores": paragraph_overlap_scores,
            "sentence_overlap_scores": sentence_overlap_scores,
        }


class ScoreBm25Generated:
    def _step_declare_bm25_scores_1(self, frames):
        # Step method: declare_bm25_scores
        declare_bm25_scores_base = frames["queries"].alias("search_query")
        document_bm25_scores = declare_bm25_scores_base.select(
            F.col("search_query.id").alias("query_id"),
            F.lit('').alias("document_id"),
            F.lit(0.0).alias("score_bm25"),
        )
        section_bm25_scores = declare_bm25_scores_base.select(
            F.col("search_query.id").alias("query_id"),
            F.lit('').alias("document_id"),
            F.lit('').alias("section_id"),
            F.lit(0.0).alias("score_bm25"),
        )
        paragraph_bm25_scores = declare_bm25_scores_base.select(
            F.col("search_query.id").alias("query_id"),
            F.lit('').alias("document_id"),
            F.lit('').alias("section_id"),
            F.lit('').alias("paragraph_id"),
            F.lit(0.0).alias("score_bm25"),
        )
        sentence_bm25_scores = declare_bm25_scores_base.select(
            F.col("search_query.id").alias("query_id"),
            F.lit('').alias("document_id"),
            F.lit('').alias("section_id"),
            F.lit('').alias("paragraph_id"),
            F.lit('').alias("sentence_id"),
            F.lit(0.0).alias("score_bm25"),
        )
        document_bm25_scores, section_bm25_scores, paragraph_bm25_scores, sentence_bm25_scores = ScoreBm25.score_bm25(self._impl, queries=frames["input:queries"], words=frames["input:words"], document_bm25_scores=document_bm25_scores, section_bm25_scores=section_bm25_scores, paragraph_bm25_scores=paragraph_bm25_scores, sentence_bm25_scores=sentence_bm25_scores, spark=self.spark, ctx=self.ctx)
        assert_schema(document_bm25_scores, DOCUMENT_BM25_SCORE_SCHEMA, name="DocumentBm25Score", mode="strict")
        return {
            "document_bm25_scores": document_bm25_scores,
            "section_bm25_scores": section_bm25_scores,
            "paragraph_bm25_scores": paragraph_bm25_scores,
            "sentence_bm25_scores": sentence_bm25_scores,
        }


class ScoreCorpusGenerated(ScoreOverlapGenerated, ScoreBm25Generated):

    def __init__(self, *, spark: SparkSession, ctx=None):
        self.spark = spark
        self.ctx = ctx
        self._impl = ScoreCorpus()

    def run(
        self,
        *,
        queries: DataFrame,
        words: DataFrame,
    ) -> TransformResult:
        assert_schema(queries, SEARCH_QUERY_SCHEMA, name="SearchQuery", mode="strict")
        assert_schema(words, WORD_SCHEMA, name="Word", mode="strict")
        _input_queries = queries
        _input_words = words
        frames = {
            "queries": queries,
            "words": words,
            "input:queries": _input_queries,
            "input:words": _input_words,
        }
        frames.update(self._step_declare_overlap_scores_0(frames))
        frames.update(self._step_declare_bm25_scores_1(frames))

        # Step method: document_overlap_scores
        document_overlap_scores = frames["document_overlap_scores"].alias("document_overlap_score")
        assert_schema(document_overlap_scores, DOCUMENT_OVERLAP_SCORE_SCHEMA, name="DocumentOverlapScore", mode="strict")

        # Step method: section_overlap_scores
        section_overlap_scores = frames["section_overlap_scores"].alias("section_overlap_score")
        assert_schema(section_overlap_scores, SECTION_OVERLAP_SCORE_SCHEMA, name="SectionOverlapScore", mode="strict")

        # Step method: paragraph_overlap_scores
        paragraph_overlap_scores = frames["paragraph_overlap_scores"].alias("paragraph_overlap_score")
        assert_schema(paragraph_overlap_scores, PARAGRAPH_OVERLAP_SCORE_SCHEMA, name="ParagraphOverlapScore", mode="strict")

        # Step method: sentence_overlap_scores
        sentence_overlap_scores = frames["sentence_overlap_scores"].alias("sentence_overlap_score")
        assert_schema(sentence_overlap_scores, SENTENCE_OVERLAP_SCORE_SCHEMA, name="SentenceOverlapScore", mode="strict")

        # Step method: document_bm25_scores
        document_bm25_scores = frames["document_bm25_scores"].alias("document_bm25_score")
        assert_schema(document_bm25_scores, DOCUMENT_BM25_SCORE_SCHEMA, name="DocumentBm25Score", mode="strict")

        # Step method: section_bm25_scores
        section_bm25_scores = frames["section_bm25_scores"].alias("section_bm25_score")
        assert_schema(section_bm25_scores, SECTION_BM25_SCORE_SCHEMA, name="SectionBm25Score", mode="strict")

        # Step method: paragraph_bm25_scores
        paragraph_bm25_scores = frames["paragraph_bm25_scores"].alias("paragraph_bm25_score")
        assert_schema(paragraph_bm25_scores, PARAGRAPH_BM25_SCORE_SCHEMA, name="ParagraphBm25Score", mode="strict")

        # Step method: sentence_bm25_scores
        sentence_bm25_scores = frames["sentence_bm25_scores"].alias("sentence_bm25_score")
        assert_schema(sentence_bm25_scores, SENTENCE_BM25_SCORE_SCHEMA, name="SentenceBm25Score", mode="strict")
        return TransformResult({"document_overlap_scores": document_overlap_scores, "section_overlap_scores": section_overlap_scores, "paragraph_overlap_scores": paragraph_overlap_scores, "sentence_overlap_scores": sentence_overlap_scores, "document_bm25_scores": document_bm25_scores, "section_bm25_scores": section_bm25_scores, "paragraph_bm25_scores": paragraph_bm25_scores, "sentence_bm25_scores": sentence_bm25_scores}, single=False, schema={"document_overlap_scores": DOCUMENT_OVERLAP_SCORE_SCHEMA, "section_overlap_scores": SECTION_OVERLAP_SCORE_SCHEMA, "paragraph_overlap_scores": PARAGRAPH_OVERLAP_SCORE_SCHEMA, "sentence_overlap_scores": SENTENCE_OVERLAP_SCORE_SCHEMA, "document_bm25_scores": DOCUMENT_BM25_SCORE_SCHEMA, "section_bm25_scores": SECTION_BM25_SCORE_SCHEMA, "paragraph_bm25_scores": PARAGRAPH_BM25_SCORE_SCHEMA, "sentence_bm25_scores": SENTENCE_BM25_SCORE_SCHEMA})
