# Generated by Structure. Do not edit by hand.
# Source: examples.store.transforms.recommender.candidates.filter.FilterRecommendationCandidates

from __future__ import annotations
from pyspark.sql import DataFrame, SparkSession
from pyspark.sql import functions as F
from pyspark.sql import types as T
from examples.structure_generated.store.runtime.schema_assert import TransformResult, assert_schema, project_schema
from examples.structure_generated.store.pyspark.schemas.policy import MERCHANDISING_SUPPRESSION_SCHEMA
from examples.structure_generated.store.pyspark.schemas.recommendation import (
    RECOMMENDATION_CANDIDATE_DECISION_SCHEMA,
    RECOMMENDATION_CANDIDATE_SCHEMA,
)
from examples.structure_generated.store.pyspark.schemas.session import SESSION_FEATURE_SCHEMA


class FilterRecommendationCandidatesGenerated:

    def __init__(self, *, spark: SparkSession, ctx=None):
        self.spark = spark
        self.ctx = ctx

    def run(
        self,
        *,
        candidates: DataFrame,
        suppressions: DataFrame,
        session_features: DataFrame,
    ) -> TransformResult:
        assert_schema(candidates, RECOMMENDATION_CANDIDATE_SCHEMA, name="RecommendationCandidate", mode="strict")
        assert_schema(suppressions, MERCHANDISING_SUPPRESSION_SCHEMA, name="MerchandisingSuppression", mode="strict")
        assert_schema(session_features, SESSION_FEATURE_SCHEMA, name="SessionFeature", mode="strict")
        _input_candidates = candidates
        _input_suppressions = suppressions
        _input_session_features = session_features

        # Step method: evaluate
        evaluated = candidates.alias("recommendation_candidate")
        suppressions_joined = suppressions.alias("suppressions")
        evaluated = evaluated.join(
            suppressions_joined,
            (
                (
                    (
                        (F.col("suppressions.tenant.tenant_id") == F.col("recommendation_candidate.tenant.tenant_id"))
                        & (F.col("suppressions.policy_version") == F.col("recommendation_candidate.policy_version"))
                    )
                    & F.col("suppressions.active")
                )
                & (
                    F.col("suppressions.product_id").eqNullSafe(F.col("recommendation_candidate.product_id"))
                    | F.col("suppressions.category").eqNullSafe(F.col("recommendation_candidate.category"))
                )
            ),
            "left",
        )
        session_features_2_joined = session_features.alias("session_features_2")
        evaluated = evaluated.join(
            session_features_2_joined,
            (
                (
                    (
                        (
                            F.col("session_features_2.tenant.tenant_id")
                            == F.col("recommendation_candidate.tenant.tenant_id")
                        )
                        & F.col("session_features_2.customer_id").eqNullSafe(
                            F.col("recommendation_candidate.customer_id")
                        )
                    )
                    & F.col("session_features_2.product_id").eqNullSafe(F.col("recommendation_candidate.product_id"))
                )
                & (F.col("session_features_2.add_to_cart_count") > F.lit(0))
            ),
            "left",
        )
        evaluated = evaluated.select(
            F.col("recommendation_candidate.tenant"),
            F.col("recommendation_candidate.request_id"),
            F.col("recommendation_candidate.product_id"),
            F.lit('filter').alias("stage"),
            (
                ~(F.coalesce(F.col("suppressions.exclude"), F.lit(False)))
                & ~(F.col("session_features_2.product_id").isNotNull())
            ).alias("eligible"),
            F.when(
                F.coalesce(F.col("suppressions.exclude"), F.lit(False)),
                F.coalesce(F.col("suppressions.reason"), F.lit('hard_suppression')),
            )
            .otherwise(
                F.when(F.col("session_features_2.product_id").isNotNull(), F.lit('session_already_added')).otherwise(
                    F.lit(None)
                )
            )
            .alias("exclusion_reason"),
            F.col("recommendation_candidate.candidate_source"),
            F.col("recommendation_candidate.taxonomy_branch"),
        )
        assert_schema(
            evaluated, RECOMMENDATION_CANDIDATE_DECISION_SCHEMA, name="RecommendationCandidateDecision", mode="strict"
        )

        # Step method: publish
        filtered = candidates.alias("recommendation_candidate")
        evaluated_joined = evaluated.alias("evaluated")
        filtered = filtered.join(
            evaluated_joined,
            (
                (
                    (F.col("evaluated.tenant.tenant_id") == F.col("recommendation_candidate.tenant.tenant_id"))
                    & (F.col("evaluated.request_id") == F.col("recommendation_candidate.request_id"))
                )
                & (F.col("evaluated.product_id") == F.col("recommendation_candidate.product_id"))
            ),
            "left",
        )
        filtered = filtered.where((F.col("evaluated.eligible")))
        filtered = filtered.select(
            F.col("recommendation_candidate.tenant"),
            F.col("recommendation_candidate.request_id"),
            F.col("recommendation_candidate.requested_at"),
            F.col("recommendation_candidate.customer_id"),
            F.col("recommendation_candidate.session_id"),
            F.col("recommendation_candidate.strategy_id"),
            F.col("recommendation_candidate.policy_version"),
            F.col("recommendation_candidate.experiment_id"),
            F.col("recommendation_candidate.experiment_version"),
            F.col("recommendation_candidate.variant_id"),
            F.col("recommendation_candidate.category_filter"),
            F.col("recommendation_candidate.collection_id"),
            F.col("recommendation_candidate.product_id"),
            F.col("recommendation_candidate.product_name"),
            F.col("recommendation_candidate.category"),
            F.col("recommendation_candidate.has_promotion"),
            F.col("recommendation_candidate.promotion_code"),
            F.col("recommendation_candidate.base_score"),
            F.col("recommendation_candidate.promotion_score"),
            F.col("recommendation_candidate.inventory_boost"),
            F.col("recommendation_candidate.candidate_source"),
            F.col("recommendation_candidate.taxonomy_id"),
            F.col("recommendation_candidate.taxonomy_branch"),
            F.col("recommendation_candidate.session_match"),
            F.col("recommendation_candidate.purchase_signal"),
            F.lit('eligible').alias("eligibility_status"),
        )

        # Step method: decisions
        decisions = evaluated.alias("recommendation_candidate_decision")
        assert_schema(
            decisions, RECOMMENDATION_CANDIDATE_DECISION_SCHEMA, name="RecommendationCandidateDecision", mode="strict"
        )

        # Step method: filtered
        filtered = filtered.alias("recommendation_candidate")
        assert_schema(filtered, RECOMMENDATION_CANDIDATE_SCHEMA, name="RecommendationCandidate", mode="strict")
        return TransformResult(
            {"decisions": decisions, "filtered": filtered},
            single=False,
            schema={"decisions": RECOMMENDATION_CANDIDATE_DECISION_SCHEMA, "filtered": RECOMMENDATION_CANDIDATE_SCHEMA},
        )
