from typing import Protocol

from structure.plugin.api.v1.model import SchemaInspectionRequest, SchemaValidationRequest, TransformSchemaRequest


class SchemaAPI(Protocol):
    def validate(self, request: SchemaValidationRequest) -> None: ...

    def materialize(self, schema: object) -> object: ...

    def build(self, request: TransformSchemaRequest) -> object: ...

    def read(self, request: SchemaInspectionRequest) -> object: ...

    def source(self, schema: object, *, to: str) -> object: ...
