from __future__ import annotations

from collections.abc import Mapping, Sequence


class RenderStructureDocsMarkdown:

    def index(self, data: Mapping[str, object]) -> str:
        schemas = self._sequence(data["schemas"])
        transforms = self._sequence(data["transforms"])
        lines = [
            self._header(),
            "# Structure Generated Reference",
            "",
            "## Schemas",
            "",
            *(f"- [{schema['name']}](schemas/{schema['name']}.md)" for schema in schemas),
            "",
            "## Transforms",
            "",
            *(f"- [{transform['name']}](transforms/{transform['source']}.md)" for transform in transforms),
            "",
        ]
        return "\n".join(lines)

    def schema(self, schema: Mapping[str, object]) -> str:
        fields = self._sequence(schema["fields"])
        lines = [
            self._header(),
            f"# {schema['name']}",
            "",
            f"Module: `{schema['module']}`",
            "",
            "| Field | Column | Type | Nullable | Primary key |",
            "| --- | --- | --- | --- | --- |",
        ]
        lines.extend(
            f"| `{field['name']}` | `{field['column']}` | `{field['type']}` | "
            f"{self._yes(field['nullable'])} | {self._yes(field['primary_key'])} |"
            for field in fields
        )
        lines.append("")
        return "\n".join(lines)

    def transform(self, transform: Mapping[str, object]) -> str:
        lines = [
            self._header(),
            f"# {transform['name']}",
            "",
            f"Source: `{transform['source']}`",
            "",
            "## Inputs",
            "",
            *self._named_schema_lines(transform["inputs"]),
            "",
            "## Outputs",
            "",
            *self._named_schema_lines(transform["outputs"]),
            "",
            "## Subtransforms",
            "",
        ]
        for step in self._sequence(transform["subtransforms"]):
            lines.append(f"- `{step['name']}`: `{step['input_schema']}` -> `{step['output_schema']}`")
        lines.extend(["", "## Dependencies", ""])
        dependencies = self._sequence(transform["dependencies"])
        lines.extend((f"- `{dependency}`" for dependency in dependencies) if dependencies else ["- None"])
        lines.extend(["", "## Target Artifacts", ""])
        artifacts = self._mapping(transform["target_artifacts"])
        for name, path in artifacts.items():
            lines.append(f"- `{name}`: `{path}`")
        lines.append("")
        return "\n".join(lines)

    def _named_schema_lines(self, items: object) -> list[str]:
        return [f"- `{item['name']}`: `{item['schema']}`" for item in self._sequence(items)]

    def _header(self) -> str:
        return "# Generated by Structure. Do not edit by hand.\n"

    def _yes(self, value: object) -> str:
        return "yes" if value else "no"

    def _sequence(self, value: object) -> Sequence[Mapping[str, object]]:
        return value  # type: ignore[return-value]

    def _mapping(self, value: object) -> Mapping[str, object]:
        return value  # type: ignore[return-value]
