# Generated by Structure. Do not edit by hand.
# Source: examples.store.schemas.evaluation.batch

from pyspark.sql import types as T


EVALUATION_BATCH_SCHEMA = T.StructType([
    T.StructField("window", TIME_WINDOW_SCHEMA, False),
    T.StructField("batch_id", T.StringType(), False),
])
