# Generated by Structure. Do not edit by hand.
# Source: examples.store.schemas.fulfillment.demand.demand

from pyspark.sql import types as T
from examples.structure_generated.store.pyspark.schemas.common import BUSINESS_DATE_SCHEMA, TENANT_KEY_SCHEMA


ORDER_DEMAND_SCHEMA = T.StructType([
    T.StructField("tenant", TENANT_KEY_SCHEMA, False),
    T.StructField("business", BUSINESS_DATE_SCHEMA, False),
    T.StructField("order_id", T.StringType(), False),
    T.StructField("customer_id", T.StringType(), False),
    T.StructField("customer_name", T.StringType(), True),
    T.StructField("customer_tier", T.StringType(), True),
    T.StructField("customer_region", T.StringType(), True),
    T.StructField("product_id", T.StringType(), False),
    T.StructField("product_name", T.StringType(), True),
    T.StructField("product_category", T.StringType(), True),
    T.StructField("promotion_code", T.StringType(), True),
    T.StructField("promotion_name", T.StringType(), True),
    T.StructField("promotion_discount", T.DecimalType(12, 2), True),
    T.StructField("total", T.DecimalType(12, 2), False),
    T.StructField("discount", T.DecimalType(12, 2), False),
    T.StructField("net_total", T.DecimalType(12, 2), False),
    T.StructField("requested_quantity", T.LongType(), False),
    T.StructField("is_large", T.BooleanType(), False),
])
