# Generated by Structure. Do not edit by hand.
# Source: examples.store.schemas.fulfillment.reconciliation.reconciliation

from pyspark.sql import types as T
from examples.structure_generated.store.pyspark.schemas.common import BUSINESS_DATE_SCHEMA, TENANT_KEY_SCHEMA


FULFILLMENT_RECONCILIATION_SCHEMA = T.StructType([
    T.StructField("tenant", TENANT_KEY_SCHEMA, False),
    T.StructField("business", BUSINESS_DATE_SCHEMA, False),
    T.StructField("order_id", T.StringType(), False),
    T.StructField("product_id", T.StringType(), False),
    T.StructField("planned_status", T.StringType(), False),
    T.StructField("planned_allocated_quantity", T.LongType(), False),
    T.StructField("planned_backordered_quantity", T.LongType(), False),
    T.StructField("shipped_quantity", T.LongType(), False),
    T.StructField("shipped", T.BooleanType(), False),
    T.StructField("reconciliation_status", T.StringType(), False),
])
