from __future__ import annotations

import json
from collections import OrderedDict
from collections.abc import Mapping, Sequence

from structure.app.backend.pyspark.logic.actions.RenderPySparkRuntimeModule import render_pyspark_runtime_module
from structure.app.backend.pyspark.logic.actions.RenderPySparkSchema import render_pyspark_schema
from structure.app.backend.pyspark.logic.actions.RenderPySparkSchemaModule import render_pyspark_schema_module
from structure.app.backend.pyspark.logic.actions.RenderPySparkTransformModule import render_pyspark_transform_module
from structure.app.backend.pyspark.logic.model.PySparkExecutionPlan import PySparkExecutionPlan
from structure.app.backend.pyspark.logic.model.PySparkStepRecipe import PySparkStepRecipe
from structure.app.dsl.logic.model.schemas.Structure import Structure


class RenderPySparkProject:

    def __call__(
        self,
        plan: PySparkExecutionPlan,
        *,
        source_transform: str,
        source_schema_modules: Mapping[str, Sequence[type[Structure]]],
        generated_package: str,
    ) -> dict[str, str]:
        schema_modules = self._schema_modules(source_schema_modules, generated_package=generated_package)
        runtime_module = f"{generated_package}.runtime.schema_assert"
        transform_module = self._transform_module(source_transform, generated_package=generated_package)

        files: OrderedDict[str, str] = OrderedDict()
        for package in self._packages(generated_package):
            files[self._module_path(package, package=True)] = self._header("Structure generated package")

        files[self._module_path(runtime_module)] = (
            self._header("Structure generated runtime") + render_pyspark_runtime_module()
        )

        for source_module in sorted(source_schema_modules):
            module = self._schema_module(source_module, generated_package=generated_package)
            schemas = source_schema_modules[source_module]
            files[self._module_path(module)] = self._header(source_module) + render_pyspark_schema_module(
                schemas,
                dependency_modules=schema_modules,
            )

        files[self._module_path(transform_module)] = self._header(source_transform) + render_pyspark_transform_module(
            plan,
            source_transform=source_transform,
            schema_modules=schema_modules,
            runtime_module=runtime_module,
        )

        files[self._lineage_path(generated_package, source_transform, plan)] = self._lineage(
            plan,
            source_transform=source_transform,
            transform_module=transform_module,
            schema_modules=schema_modules,
        )
        return dict(files)

    def _schema_modules(
        self,
        source_schema_modules: Mapping[str, Sequence[type[Structure]]],
        *,
        generated_package: str,
    ) -> dict[type[Structure], str]:
        modules: dict[type[Structure], str] = {}
        for source_module, schemas in source_schema_modules.items():
            module = self._schema_module(source_module, generated_package=generated_package)
            for schema in schemas:
                modules[schema] = module
        return modules

    def _schema_module(self, source_module: str, *, generated_package: str) -> str:
        name = source_module.rsplit(".", 1)[1]
        return f"{generated_package}.pyspark.schemas.{name}"

    def _transform_module(self, source_transform: str, *, generated_package: str) -> str:
        name = source_transform.rsplit(".", 2)[1]
        return f"{generated_package}.pyspark.transforms.{name}"

    def _packages(self, generated_package: str) -> tuple[str, ...]:
        return (
            generated_package,
            f"{generated_package}.pyspark",
            f"{generated_package}.pyspark.schemas",
            f"{generated_package}.pyspark.transforms",
            f"{generated_package}.runtime",
        )

    def _module_path(self, module: str, *, package: bool = False) -> str:
        suffix = "/__init__.py" if package else ".py"
        return module.replace(".", "/") + suffix

    def _lineage_path(self, generated_package: str, source_transform: str, plan: PySparkExecutionPlan) -> str:
        root = generated_package.replace(".", "/")
        return f"{root}/lineage/transforms/{source_transform.rsplit('.', 2)[1]}.{plan.transform}.json"

    def _header(self, source: str) -> str:
        return f"# Generated by Structure. Do not edit by hand.\n# Source: {source}\n\n"

    def _lineage(
        self,
        plan: PySparkExecutionPlan,
        *,
        source_transform: str,
        transform_module: str,
        schema_modules: Mapping[type[Structure], str],
    ) -> str:
        data = {
            "backend": {"name": plan.backend.name, "target": plan.backend.target},
            "generated_transform_class": f"{plan.transform}Generated",
            "inputs": [
                {"name": item.name, "ordinal": item.ordinal, "schema": item.schema.__name__} for item in plan.inputs
            ],
            "schema_constants": {
                schema.__name__: {
                    "constant": render_pyspark_schema.constant_name(schema),
                    "module": module,
                }
                for schema, module in sorted(schema_modules.items(), key=lambda item: item[0].__name__)
            },
            "source_transform": source_transform,
            "steps": [self._step(step) for step in plan.steps],
            "target_module": transform_module,
            "validation": {
                "final": {
                    "mode": plan.final_validation.mode.value,
                    "schema": plan.final_validation.schema.__name__,
                }
            },
        }
        return json.dumps(data, indent=2, sort_keys=True) + "\n"

    def _step(self, step: PySparkStepRecipe) -> dict[str, object]:
        return {
            "after_hooks": [hook.name for hook in step.after_hooks],
            "before_hooks": [hook.name for hook in step.before_hooks],
            "input_alias": step.input_alias,
            "joins": [
                {
                    "how": join.how.value,
                    "input": join.input_name,
                    "right_alias": join.right_alias,
                }
                for join in step.joins
            ],
            "name": step.name,
            "output_alias": step.output_alias,
            "output_schema": step.output_schema.__name__,
            "validation": [
                {
                    "mode": validation.mode.value,
                    "project": validation.project,
                    "reason": validation.reason,
                    "schema": validation.schema.__name__,
                }
                for validation in step.validations
            ],
        }


render_pyspark_project = RenderPySparkProject()
