# Generated by Structure. Do not edit by hand.
# Source: examples.search.transforms.searching.search_similarity.SearchSimilarityParagraphs.SearchSimilarityParagraphs

from __future__ import annotations
from pyspark.sql import DataFrame, SparkSession
from pyspark.sql import Window
from pyspark.sql import functions as F
from pyspark.sql import types as T
from examples.structure_generated.search.runtime.schema_assert import (
    TransformResult,
    assert_schema,
    project_schema,
    apply_plan_boundary,
    close_plan_boundaries,
)
from examples.structure_generated.search.pyspark.schemas.indexing_vector import PARAGRAPH_VECTOR_CANDIDATE_SCHEMA
from examples.structure_generated.search.pyspark.schemas.similarities_vector import (
    PARAGRAPH_FUSED_SIMILARITY_CANDIDATE_SCHEMA,
)
from examples.structure_generated.search.pyspark.schemas.similarity import (
    HYBRID_INDEXED_SIMILAR_PARAGRAPH_SCHEMA,
    PARAGRAPH_SIMILARITY_SCHEMA,
    SIMILARITY_FUSION_POLICY_SCHEMA,
)
from examples.structure_generated.search.pyspark.schemas.text import PARAGRAPH_SCHEMA


class AdoptLexicalParagraphsGenerated:
    def _step_lexical_adopt_paragraphs_0(self, frames):
        # Step method: lexical.adopt_paragraphs
        lexical__paragraph_candidates = frames["paragraph_similarities"].alias("paragraph_similarity")
        lexical__paragraph_candidates_require_unique_0_duplicates = lexical__paragraph_candidates.groupBy(
            F.col("paragraph_similarity.left_document_id"),
            F.col("paragraph_similarity.left_section_id"),
            F.col("paragraph_similarity.left_paragraph_id"),
            F.col("paragraph_similarity.right_document_id"),
            F.col("paragraph_similarity.right_section_id"),
            F.col("paragraph_similarity.right_paragraph_id"),
        ).agg(F.count(F.lit(1)).alias("__structure_count"))
        lexical__paragraph_candidates_require_unique_0_duplicates = (
            lexical__paragraph_candidates_require_unique_0_duplicates.where(F.col("__structure_count") > F.lit(1))
        )
        lexical__paragraph_candidates_require_unique_0_violations = (
            lexical__paragraph_candidates_require_unique_0_duplicates.agg(
                F.count(F.lit(1)).alias("__structure_violations")
            )
        )
        lexical__paragraph_candidates_require_unique_0_assertion = (
            lexical__paragraph_candidates_require_unique_0_violations.select(
                F.assert_true(
                    F.col("__structure_violations") == F.lit(0),
                    'REL-E0702: require_unique(...) found duplicate keys; see docs/Diagnostics.md#rel-e0702',
                ).alias("__structure_require_unique")
            )
        )
        lexical__paragraph_candidates = lexical__paragraph_candidates_require_unique_0_assertion.crossJoin(
            lexical__paragraph_candidates
        ).drop("__structure_require_unique")
        lexical__paragraph_candidates = lexical__paragraph_candidates.select(
            F.col("paragraph_similarity.left_document_id"),
            F.col("paragraph_similarity.left_section_id"),
            F.col("paragraph_similarity.left_paragraph_id"),
            F.col("paragraph_similarity.right_document_id"),
            F.col("paragraph_similarity.right_section_id"),
            F.col("paragraph_similarity.right_paragraph_id"),
            F.col("paragraph_similarity.rank").alias("lexical_rank"),
            F.lit(None).cast(T.LongType()).alias("vector_rank"),
            F.col("paragraph_similarity.score_overlap"),
            F.col("paragraph_similarity.bm25_left_to_right"),
            F.col("paragraph_similarity.bm25_right_to_left"),
            F.col("paragraph_similarity.bm25_mean"),
            F.lit(None).cast(T.DoubleType()).alias("vector_similarity"),
            F.lit(None).cast(T.StringType()).alias("vector_backend"),
            F.lit(None).cast(T.StringType()).alias("vector_model_id"),
            F.lit(None).cast(T.LongType()).alias("vector_dimension"),
            F.lit(None).cast(T.StringType()).alias("vector_content_revision"),
            F.lit(0.0).alias("rrf_score"),
            F.lit(0).cast(T.LongType()).alias("rrf_k"),
            F.lit('').alias("experiment_id"),
        )
        assert_schema(
            lexical__paragraph_candidates,
            PARAGRAPH_FUSED_SIMILARITY_CANDIDATE_SCHEMA,
            name="ParagraphFusedSimilarityCandidate",
            mode="strict",
        )
        return {
            "lexical__paragraph_candidates": lexical__paragraph_candidates,
        }


class AdoptVectorParagraphsGenerated:
    def _step_vector_adopt_paragraphs_1(self, frames):
        # Step method: vector.adopt_paragraphs
        vector__adopted_paragraph_candidates = frames["paragraph_vector_candidates"].alias("paragraph_vector_candidate")
        vector__adopted_paragraph_candidates_require_unique_0_duplicates = vector__adopted_paragraph_candidates.groupBy(
            F.col("paragraph_vector_candidate.query_document_id"),
            F.col("paragraph_vector_candidate.query_section_id"),
            F.col("paragraph_vector_candidate.query_paragraph_id"),
            F.col("paragraph_vector_candidate.document_id"),
            F.col("paragraph_vector_candidate.section_id"),
            F.col("paragraph_vector_candidate.paragraph_id"),
        ).agg(F.count(F.lit(1)).alias("__structure_count"))
        vector__adopted_paragraph_candidates_require_unique_0_duplicates = (
            vector__adopted_paragraph_candidates_require_unique_0_duplicates.where(
                F.col("__structure_count") > F.lit(1)
            )
        )
        vector__adopted_paragraph_candidates_require_unique_0_violations = (
            vector__adopted_paragraph_candidates_require_unique_0_duplicates.agg(
                F.count(F.lit(1)).alias("__structure_violations")
            )
        )
        vector__adopted_paragraph_candidates_require_unique_0_assertion = (
            vector__adopted_paragraph_candidates_require_unique_0_violations.select(
                F.assert_true(
                    F.col("__structure_violations") == F.lit(0),
                    'REL-E0702: require_unique(...) found duplicate keys; see docs/Diagnostics.md#rel-e0702',
                ).alias("__structure_require_unique")
            )
        )
        vector__adopted_paragraph_candidates = (
            vector__adopted_paragraph_candidates_require_unique_0_assertion.crossJoin(
                vector__adopted_paragraph_candidates
            ).drop("__structure_require_unique")
        )
        vector__adopted_paragraph_candidates = vector__adopted_paragraph_candidates.select(
            F.col("paragraph_vector_candidate.query_document_id").alias("left_document_id"),
            F.col("paragraph_vector_candidate.query_section_id").alias("left_section_id"),
            F.col("paragraph_vector_candidate.query_paragraph_id").alias("left_paragraph_id"),
            F.col("paragraph_vector_candidate.document_id").alias("right_document_id"),
            F.col("paragraph_vector_candidate.section_id").alias("right_section_id"),
            F.col("paragraph_vector_candidate.paragraph_id").alias("right_paragraph_id"),
            F.lit(None).cast(T.LongType()).alias("lexical_rank"),
            F.col("paragraph_vector_candidate.rank").alias("vector_rank"),
            F.lit(None).cast(T.DoubleType()).alias("score_overlap"),
            F.lit(None).cast(T.DoubleType()).alias("bm25_left_to_right"),
            F.lit(None).cast(T.DoubleType()).alias("bm25_right_to_left"),
            F.lit(None).cast(T.DoubleType()).alias("bm25_mean"),
            F.col("paragraph_vector_candidate.cosine_similarity").alias("vector_similarity"),
            F.col("paragraph_vector_candidate.vector_backend"),
            F.col("paragraph_vector_candidate.model_id").alias("vector_model_id"),
            F.col("paragraph_vector_candidate.dimension").alias("vector_dimension"),
            F.col("paragraph_vector_candidate.content_revision").alias("vector_content_revision"),
            F.lit(0.0).alias("rrf_score"),
            F.lit(0).cast(T.LongType()).alias("rrf_k"),
            F.lit('').alias("experiment_id"),
        )
        assert_schema(
            vector__adopted_paragraph_candidates,
            PARAGRAPH_FUSED_SIMILARITY_CANDIDATE_SCHEMA,
            name="ParagraphFusedSimilarityCandidate",
            mode="strict",
        )
        return {
            "vector__adopted_paragraph_candidates": vector__adopted_paragraph_candidates,
        }


class FuseSimilarityParagraphsGenerated:
    def _step_fused_validate_policy_2(self, frames):
        # Step method: fused.validate_policy
        fused__valid_policy = frames["policy"].alias("similarity_fusion_policy")
        fused__valid_policy_require_all_0_violations = fused__valid_policy.where(
            ~F.coalesce(
                (
                    (
                        (
                            (F.col("similarity_fusion_policy.rrf_k") > F.lit(0))
                            & (F.col("similarity_fusion_policy.maximum_lexical_candidates") > F.lit(0))
                        )
                        & (F.col("similarity_fusion_policy.maximum_vector_candidates") > F.lit(0))
                    )
                    & (F.col("similarity_fusion_policy.maximum_results") > F.lit(0))
                ),
                F.lit(False),
            )
        ).agg(F.count(F.lit(1)).alias("__structure_violations"))
        fused__valid_policy_require_all_0_assertion = fused__valid_policy_require_all_0_violations.select(
            F.assert_true(
                F.col("__structure_violations") == F.lit(0),
                (
                    'REL-E0703: require_all(...) found rows that do not satisfy the predicate; see'
                    'docs/Diagnostics.md#rel-e0703'
                ),
            ).alias("__structure_require_all")
        )
        fused__valid_policy = fused__valid_policy_require_all_0_assertion.crossJoin(fused__valid_policy).drop(
            "__structure_require_all"
        )
        fused__valid_policy = fused__valid_policy.select(
            F.col("similarity_fusion_policy.rrf_k"),
            F.col("similarity_fusion_policy.maximum_lexical_candidates"),
            F.col("similarity_fusion_policy.maximum_vector_candidates"),
            F.col("similarity_fusion_policy.maximum_results"),
            F.col("similarity_fusion_policy.experiment_id"),
        )
        assert_schema(
            fused__valid_policy, SIMILARITY_FUSION_POLICY_SCHEMA, name="SimilarityFusionPolicy", mode="strict"
        )
        return {
            "fused__valid_policy": fused__valid_policy,
        }

    def _step_fused_merge_paragraphs_3(self, frames):
        # Step method: fused.merge_paragraphs
        fused__merged_candidates = frames["lexical__paragraph_candidates"].alias("paragraph_fused_similarity_candidate")
        fused__merged_candidates = fused__merged_candidates.union(frames["vector__adopted_paragraph_candidates"])
        fused__merged_candidates = fused__merged_candidates.alias("paragraph_fused_similarity_candidate")
        fused__merged_candidates = fused__merged_candidates.select(
            F.col("left_document_id"),
            F.col("left_section_id"),
            F.col("left_paragraph_id"),
            F.col("right_document_id"),
            F.col("right_section_id"),
            F.col("right_paragraph_id"),
            F.col("lexical_rank"),
            F.col("vector_rank"),
            F.col("score_overlap"),
            F.col("bm25_left_to_right"),
            F.col("bm25_right_to_left"),
            F.col("bm25_mean"),
            F.col("vector_similarity"),
            F.col("vector_backend"),
            F.col("vector_model_id"),
            F.col("vector_dimension"),
            F.col("vector_content_revision"),
            F.col("rrf_score"),
            F.col("rrf_k"),
            F.col("experiment_id"),
        )
        assert_schema(
            fused__merged_candidates,
            PARAGRAPH_FUSED_SIMILARITY_CANDIDATE_SCHEMA,
            name="ParagraphFusedSimilarityCandidate",
            mode="strict",
        )
        return {
            "fused__merged_candidates": fused__merged_candidates,
        }

    def _step_fused_fuse_paragraphs_4(self, frames):
        # Step method: fused.fuse_paragraphs
        fused__fused_candidates = frames["fused__merged_candidates"].alias("paragraph_fused_similarity_candidate")
        __structure_streaming_step = (
            frames["fused__merged_candidates"].isStreaming or frames["fused__valid_policy"].isStreaming
        )
        fused__fused_candidates_policy_exactly_one_1_count = frames["fused__valid_policy"].agg(
            F.count(F.lit(1)).alias("__structure_count")
        )
        fused__fused_candidates_policy_exactly_one_1_count = fused__fused_candidates_policy_exactly_one_1_count.select(
            F.assert_true(
                F.col("__structure_count") == F.lit(1),
                'REL-E0701: exactly_one(policy) requires exactly one row; see docs/Diagnostics.md#rel-e0701',
            ).alias("__structure_exactly_one")
        )
        fused__fused_candidates_policy_exactly_one_1 = fused__fused_candidates_policy_exactly_one_1_count.crossJoin(
            frames["fused__valid_policy"]
        ).drop("__structure_exactly_one")
        fused__valid_policy_param_joined = fused__fused_candidates_policy_exactly_one_1
        if not __structure_streaming_step:
            fused__valid_policy_param_joined_count = fused__fused_candidates_policy_exactly_one_1.agg(
                F.count(F.lit(1)).alias("__structure_count")
            )
            fused__valid_policy_param_joined_count = fused__valid_policy_param_joined_count.select(
                F.assert_true(
                    F.col("__structure_count") == F.lit(1),
                    'REL-E0701: exactly_one(policy) requires exactly one row; see docs/Diagnostics.md#rel-e0701',
                ).alias("__structure_exactly_one")
            )
            fused__valid_policy_param_joined = fused__valid_policy_param_joined_count.crossJoin(
                fused__fused_candidates_policy_exactly_one_1
            ).drop("__structure_exactly_one")
        fused__valid_policy_joined = fused__valid_policy_param_joined.alias("fused__valid_policy")
        fused__fused_candidates = fused__fused_candidates.crossJoin(fused__valid_policy_joined)
        fused__fused_candidates = (
            fused__fused_candidates.groupBy(
                F.col("paragraph_fused_similarity_candidate.left_document_id").alias("left_document_id"),
                F.col("paragraph_fused_similarity_candidate.left_section_id").alias("left_section_id"),
                F.col("paragraph_fused_similarity_candidate.left_paragraph_id").alias("left_paragraph_id"),
                F.col("paragraph_fused_similarity_candidate.right_document_id").alias("right_document_id"),
                F.col("paragraph_fused_similarity_candidate.right_section_id").alias("right_section_id"),
                F.col("paragraph_fused_similarity_candidate.right_paragraph_id").alias("right_paragraph_id"),
                F.col("fused__valid_policy.rrf_k").alias("rrf_k"),
                F.col("fused__valid_policy.experiment_id").alias("experiment_id"),
            )
            .agg(
                F.max(F.col("paragraph_fused_similarity_candidate.lexical_rank"))
                .cast(T.LongType())
                .alias("lexical_rank"),
                F.max(F.col("paragraph_fused_similarity_candidate.vector_rank"))
                .cast(T.LongType())
                .alias("vector_rank"),
                F.max(F.col("paragraph_fused_similarity_candidate.score_overlap"))
                .cast(T.DoubleType())
                .alias("score_overlap"),
                F.max(F.col("paragraph_fused_similarity_candidate.bm25_left_to_right"))
                .cast(T.DoubleType())
                .alias("bm25_left_to_right"),
                F.max(F.col("paragraph_fused_similarity_candidate.bm25_right_to_left"))
                .cast(T.DoubleType())
                .alias("bm25_right_to_left"),
                F.max(F.col("paragraph_fused_similarity_candidate.bm25_mean")).cast(T.DoubleType()).alias("bm25_mean"),
                F.max(F.col("paragraph_fused_similarity_candidate.vector_similarity"))
                .cast(T.DoubleType())
                .alias("vector_similarity"),
                F.max(F.col("paragraph_fused_similarity_candidate.vector_backend"))
                .cast(T.StringType())
                .alias("vector_backend"),
                F.max(F.col("paragraph_fused_similarity_candidate.vector_model_id"))
                .cast(T.StringType())
                .alias("vector_model_id"),
                F.max(F.col("paragraph_fused_similarity_candidate.vector_dimension"))
                .cast(T.LongType())
                .alias("vector_dimension"),
                F.max(F.col("paragraph_fused_similarity_candidate.vector_content_revision"))
                .cast(T.StringType())
                .alias("vector_content_revision"),
                F.max(F.col("paragraph_fused_similarity_candidate.rrf_score")).cast(T.DoubleType()).alias("rrf_score"),
            )
            .select(
                F.col("left_document_id"),
                F.col("left_section_id"),
                F.col("left_paragraph_id"),
                F.col("right_document_id"),
                F.col("right_section_id"),
                F.col("right_paragraph_id"),
                F.col("lexical_rank"),
                F.col("vector_rank"),
                F.col("score_overlap"),
                F.col("bm25_left_to_right"),
                F.col("bm25_right_to_left"),
                F.col("bm25_mean"),
                F.col("vector_similarity"),
                F.col("vector_backend"),
                F.col("vector_model_id"),
                F.col("vector_dimension"),
                F.col("vector_content_revision"),
                F.col("rrf_score"),
                F.col("rrf_k"),
                F.col("experiment_id"),
            )
        )
        assert_schema(
            fused__fused_candidates,
            PARAGRAPH_FUSED_SIMILARITY_CANDIDATE_SCHEMA,
            name="ParagraphFusedSimilarityCandidate",
            mode="strict",
        )
        return {
            "fused__fused_candidates": fused__fused_candidates,
        }

    def _step_fused_score_paragraphs_5(self, frames):
        # Step method: fused.score_paragraphs
        fused__scored_candidates = frames["fused__fused_candidates"].alias("paragraph_fused_similarity_candidate")
        __structure_streaming_step = (
            frames["fused__fused_candidates"].isStreaming or frames["fused__valid_policy"].isStreaming
        )
        fused__scored_candidates_policy_exactly_one_1_count = frames["fused__valid_policy"].agg(
            F.count(F.lit(1)).alias("__structure_count")
        )
        fused__scored_candidates_policy_exactly_one_1_count = (
            fused__scored_candidates_policy_exactly_one_1_count.select(
                F.assert_true(
                    F.col("__structure_count") == F.lit(1),
                    'REL-E0701: exactly_one(policy) requires exactly one row; see docs/Diagnostics.md#rel-e0701',
                ).alias("__structure_exactly_one")
            )
        )
        fused__scored_candidates_policy_exactly_one_1 = fused__scored_candidates_policy_exactly_one_1_count.crossJoin(
            frames["fused__valid_policy"]
        ).drop("__structure_exactly_one")
        fused__valid_policy_param_joined = fused__scored_candidates_policy_exactly_one_1
        if not __structure_streaming_step:
            fused__valid_policy_param_joined_count = fused__scored_candidates_policy_exactly_one_1.agg(
                F.count(F.lit(1)).alias("__structure_count")
            )
            fused__valid_policy_param_joined_count = fused__valid_policy_param_joined_count.select(
                F.assert_true(
                    F.col("__structure_count") == F.lit(1),
                    'REL-E0701: exactly_one(policy) requires exactly one row; see docs/Diagnostics.md#rel-e0701',
                ).alias("__structure_exactly_one")
            )
            fused__valid_policy_param_joined = fused__valid_policy_param_joined_count.crossJoin(
                fused__scored_candidates_policy_exactly_one_1
            ).drop("__structure_exactly_one")
        fused__valid_policy_joined = fused__valid_policy_param_joined.alias("fused__valid_policy")
        fused__scored_candidates = fused__scored_candidates.crossJoin(fused__valid_policy_joined)
        fused__scored_candidates = fused__scored_candidates.select(
            F.col("paragraph_fused_similarity_candidate.left_document_id"),
            F.col("paragraph_fused_similarity_candidate.left_section_id"),
            F.col("paragraph_fused_similarity_candidate.left_paragraph_id"),
            F.col("paragraph_fused_similarity_candidate.right_document_id"),
            F.col("paragraph_fused_similarity_candidate.right_section_id"),
            F.col("paragraph_fused_similarity_candidate.right_paragraph_id"),
            F.col("paragraph_fused_similarity_candidate.lexical_rank"),
            F.col("paragraph_fused_similarity_candidate.vector_rank"),
            F.col("paragraph_fused_similarity_candidate.score_overlap"),
            F.col("paragraph_fused_similarity_candidate.bm25_left_to_right"),
            F.col("paragraph_fused_similarity_candidate.bm25_right_to_left"),
            F.col("paragraph_fused_similarity_candidate.bm25_mean"),
            F.col("paragraph_fused_similarity_candidate.vector_similarity"),
            F.col("paragraph_fused_similarity_candidate.vector_backend"),
            F.col("paragraph_fused_similarity_candidate.vector_model_id"),
            F.col("paragraph_fused_similarity_candidate.vector_dimension"),
            F.col("paragraph_fused_similarity_candidate.vector_content_revision"),
            (
                F.coalesce(
                    F.when(
                        F.col("paragraph_fused_similarity_candidate.lexical_rank").isNotNull(),
                        (
                            F.lit(1.0)
                            / (
                                F.col("fused__valid_policy.rrf_k")
                                + F.col("paragraph_fused_similarity_candidate.lexical_rank")
                            )
                        ),
                    ).otherwise(F.lit(0.0)),
                    F.lit(0.0),
                )
                + F.coalesce(
                    F.when(
                        F.col("paragraph_fused_similarity_candidate.vector_rank").isNotNull(),
                        (
                            F.lit(1.0)
                            / (
                                F.col("fused__valid_policy.rrf_k")
                                + F.col("paragraph_fused_similarity_candidate.vector_rank")
                            )
                        ),
                    ).otherwise(F.lit(0.0)),
                    F.lit(0.0),
                )
            ).alias("rrf_score"),
            F.col("paragraph_fused_similarity_candidate.rrf_k"),
            F.col("paragraph_fused_similarity_candidate.experiment_id"),
        )
        assert_schema(
            fused__scored_candidates,
            PARAGRAPH_FUSED_SIMILARITY_CANDIDATE_SCHEMA,
            name="ParagraphFusedSimilarityCandidate",
            mode="strict",
        )
        return {
            "fused__scored_candidates": fused__scored_candidates,
        }

    def _step_fused_publish_paragraphs_6(self, frames):
        # Step method: fused.publish_paragraphs
        fused__paragraph_candidates = frames["fused__scored_candidates"].alias("paragraph_fused_similarity_candidate")
        __structure_streaming_step = (
            frames["fused__scored_candidates"].isStreaming or frames["fused__valid_policy"].isStreaming
        )
        fused__paragraph_candidates_policy_exactly_one_1_count = frames["fused__valid_policy"].agg(
            F.count(F.lit(1)).alias("__structure_count")
        )
        fused__paragraph_candidates_policy_exactly_one_1_count = (
            fused__paragraph_candidates_policy_exactly_one_1_count.select(
                F.assert_true(
                    F.col("__structure_count") == F.lit(1),
                    'REL-E0701: exactly_one(policy) requires exactly one row; see docs/Diagnostics.md#rel-e0701',
                ).alias("__structure_exactly_one")
            )
        )
        fused__paragraph_candidates_policy_exactly_one_1 = (
            fused__paragraph_candidates_policy_exactly_one_1_count.crossJoin(frames["fused__valid_policy"]).drop(
                "__structure_exactly_one"
            )
        )
        fused__valid_policy_param_joined = fused__paragraph_candidates_policy_exactly_one_1
        if not __structure_streaming_step:
            fused__valid_policy_param_joined_count = fused__paragraph_candidates_policy_exactly_one_1.agg(
                F.count(F.lit(1)).alias("__structure_count")
            )
            fused__valid_policy_param_joined_count = fused__valid_policy_param_joined_count.select(
                F.assert_true(
                    F.col("__structure_count") == F.lit(1),
                    'REL-E0701: exactly_one(policy) requires exactly one row; see docs/Diagnostics.md#rel-e0701',
                ).alias("__structure_exactly_one")
            )
            fused__valid_policy_param_joined = fused__valid_policy_param_joined_count.crossJoin(
                fused__paragraph_candidates_policy_exactly_one_1
            ).drop("__structure_exactly_one")
        fused__valid_policy_joined = fused__valid_policy_param_joined.alias("fused__valid_policy")
        fused__paragraph_candidates = fused__paragraph_candidates.crossJoin(fused__valid_policy_joined)
        fused__paragraph_candidates = fused__paragraph_candidates.where(
            (
                (
                    F.col("paragraph_fused_similarity_candidate.lexical_rank").isNull()
                    | (
                        F.col("paragraph_fused_similarity_candidate.lexical_rank")
                        <= F.col("fused__valid_policy.maximum_lexical_candidates")
                    )
                )
            )
            & (
                (
                    F.col("paragraph_fused_similarity_candidate.vector_rank").isNull()
                    | (
                        F.col("paragraph_fused_similarity_candidate.vector_rank")
                        <= F.col("fused__valid_policy.maximum_vector_candidates")
                    )
                )
            )
        )
        fused__paragraph_candidates = fused__paragraph_candidates.select(
            F.col("paragraph_fused_similarity_candidate.left_document_id"),
            F.col("paragraph_fused_similarity_candidate.left_section_id"),
            F.col("paragraph_fused_similarity_candidate.left_paragraph_id"),
            F.col("paragraph_fused_similarity_candidate.right_document_id"),
            F.col("paragraph_fused_similarity_candidate.right_section_id"),
            F.col("paragraph_fused_similarity_candidate.right_paragraph_id"),
            F.col("paragraph_fused_similarity_candidate.lexical_rank"),
            F.col("paragraph_fused_similarity_candidate.vector_rank"),
            F.col("paragraph_fused_similarity_candidate.score_overlap"),
            F.col("paragraph_fused_similarity_candidate.bm25_left_to_right"),
            F.col("paragraph_fused_similarity_candidate.bm25_right_to_left"),
            F.col("paragraph_fused_similarity_candidate.bm25_mean"),
            F.col("paragraph_fused_similarity_candidate.vector_similarity"),
            F.col("paragraph_fused_similarity_candidate.vector_backend"),
            F.col("paragraph_fused_similarity_candidate.vector_model_id"),
            F.col("paragraph_fused_similarity_candidate.vector_dimension"),
            F.col("paragraph_fused_similarity_candidate.vector_content_revision"),
            F.col("paragraph_fused_similarity_candidate.rrf_score"),
            F.col("paragraph_fused_similarity_candidate.rrf_k"),
            F.col("paragraph_fused_similarity_candidate.experiment_id"),
        )
        assert_schema(
            fused__paragraph_candidates,
            PARAGRAPH_FUSED_SIMILARITY_CANDIDATE_SCHEMA,
            name="ParagraphFusedSimilarityCandidate",
            mode="strict",
        )
        return {
            "fused__paragraph_candidates": fused__paragraph_candidates,
        }


class RerankSimilarityParagraphsGenerated:
    def _step_reranked_rank_paragraphs_7(self, frames):
        # Step method: reranked.rank_paragraphs
        reranked__ranked_paragraphs = frames["fused__paragraph_candidates"].alias(
            "paragraph_fused_similarity_candidate"
        )
        query_joined = frames["query"].alias("query")
        reranked__ranked_paragraphs = reranked__ranked_paragraphs.join(
            query_joined,
            (
                (
                    (F.col("query.id") == F.col("paragraph_fused_similarity_candidate.left_paragraph_id"))
                    & (F.col("query.document_id") == F.col("paragraph_fused_similarity_candidate.left_document_id"))
                )
                & (F.col("query.section_id") == F.col("paragraph_fused_similarity_candidate.left_section_id"))
            ),
            "inner",
        )
        paragraphs_2_joined = frames["paragraphs"].alias("paragraphs_2")
        reranked__ranked_paragraphs = reranked__ranked_paragraphs.join(
            paragraphs_2_joined,
            (
                (
                    (F.col("paragraphs_2.id") == F.col("paragraph_fused_similarity_candidate.right_paragraph_id"))
                    & (
                        F.col("paragraphs_2.document_id")
                        == F.col("paragraph_fused_similarity_candidate.right_document_id")
                    )
                )
                & (F.col("paragraphs_2.section_id") == F.col("paragraph_fused_similarity_candidate.right_section_id"))
            ),
            "inner",
        )
        reranked__ranked_paragraphs = reranked__ranked_paragraphs.select(
            F.col("paragraphs_2.id"),
            F.col("paragraphs_2.document_id"),
            F.col("paragraphs_2.section_id"),
            F.col("paragraphs_2.ordinal"),
            F.col("paragraphs_2.span_start"),
            F.col("paragraphs_2.span_end"),
            F.col("paragraph_fused_similarity_candidate.lexical_rank"),
            F.col("paragraph_fused_similarity_candidate.vector_rank"),
            F.col("paragraph_fused_similarity_candidate.score_overlap"),
            F.col("paragraph_fused_similarity_candidate.bm25_left_to_right").alias("score_bm25"),
            F.col("paragraph_fused_similarity_candidate.vector_similarity"),
            F.col("paragraph_fused_similarity_candidate.rrf_k"),
            F.col("paragraph_fused_similarity_candidate.rrf_score"),
            F.col("paragraph_fused_similarity_candidate.vector_backend"),
            F.col("paragraph_fused_similarity_candidate.vector_model_id"),
            F.col("paragraph_fused_similarity_candidate.vector_dimension"),
            F.col("paragraph_fused_similarity_candidate.vector_content_revision"),
            F.col("paragraph_fused_similarity_candidate.experiment_id"),
            F.row_number()
            .over(
                Window.partitionBy(
                    F.col("paragraph_fused_similarity_candidate.left_document_id"),
                    F.col("paragraph_fused_similarity_candidate.left_section_id"),
                    F.col("paragraph_fused_similarity_candidate.left_paragraph_id"),
                ).orderBy(
                    F.col("paragraph_fused_similarity_candidate.rrf_score").desc_nulls_last(),
                    F.col("paragraph_fused_similarity_candidate.vector_similarity").desc_nulls_last(),
                    F.col("paragraph_fused_similarity_candidate.bm25_mean").desc_nulls_last(),
                    F.col("paragraph_fused_similarity_candidate.right_document_id").asc_nulls_first(),
                    F.col("paragraph_fused_similarity_candidate.right_section_id").asc_nulls_first(),
                    F.col("paragraph_fused_similarity_candidate.right_paragraph_id").asc_nulls_first(),
                )
            )
            .cast(T.LongType())
            .alias("rank"),
        )
        assert_schema(
            reranked__ranked_paragraphs,
            HYBRID_INDEXED_SIMILAR_PARAGRAPH_SCHEMA,
            name="HybridIndexedSimilarParagraph",
            mode="strict",
        )
        return {
            "reranked__ranked_paragraphs": reranked__ranked_paragraphs,
        }

    def _step_reranked_limit_paragraphs_8(self, frames):
        # Step method: reranked.limit_paragraphs
        reranked__similar_paragraphs = frames["reranked__ranked_paragraphs"].alias("hybrid_indexed_similar_paragraph")
        __structure_streaming_step = frames["reranked__ranked_paragraphs"].isStreaming or frames["policy"].isStreaming
        reranked__similar_paragraphs_policy_exactly_one_1_count = frames["policy"].agg(
            F.count(F.lit(1)).alias("__structure_count")
        )
        reranked__similar_paragraphs_policy_exactly_one_1_count = (
            reranked__similar_paragraphs_policy_exactly_one_1_count.select(
                F.assert_true(
                    F.col("__structure_count") == F.lit(1),
                    'REL-E0701: exactly_one(policy) requires exactly one row; see docs/Diagnostics.md#rel-e0701',
                ).alias("__structure_exactly_one")
            )
        )
        reranked__similar_paragraphs_policy_exactly_one_1 = (
            reranked__similar_paragraphs_policy_exactly_one_1_count.crossJoin(frames["policy"]).drop(
                "__structure_exactly_one"
            )
        )
        policy_param_joined = reranked__similar_paragraphs_policy_exactly_one_1
        if not __structure_streaming_step:
            policy_param_joined_count = reranked__similar_paragraphs_policy_exactly_one_1.agg(
                F.count(F.lit(1)).alias("__structure_count")
            )
            policy_param_joined_count = policy_param_joined_count.select(
                F.assert_true(
                    F.col("__structure_count") == F.lit(1),
                    'REL-E0701: exactly_one(policy) requires exactly one row; see docs/Diagnostics.md#rel-e0701',
                ).alias("__structure_exactly_one")
            )
            policy_param_joined = policy_param_joined_count.crossJoin(
                reranked__similar_paragraphs_policy_exactly_one_1
            ).drop("__structure_exactly_one")
        policy_joined = policy_param_joined.alias("policy")
        reranked__similar_paragraphs = reranked__similar_paragraphs.crossJoin(policy_joined)
        reranked__similar_paragraphs = reranked__similar_paragraphs.where(
            ((F.col("hybrid_indexed_similar_paragraph.rank") <= F.col("policy.maximum_results")))
        )
        reranked__similar_paragraphs = reranked__similar_paragraphs.select(
            F.col("hybrid_indexed_similar_paragraph.id"),
            F.col("hybrid_indexed_similar_paragraph.document_id"),
            F.col("hybrid_indexed_similar_paragraph.section_id"),
            F.col("hybrid_indexed_similar_paragraph.ordinal"),
            F.col("hybrid_indexed_similar_paragraph.span_start"),
            F.col("hybrid_indexed_similar_paragraph.span_end"),
            F.col("hybrid_indexed_similar_paragraph.lexical_rank"),
            F.col("hybrid_indexed_similar_paragraph.vector_rank"),
            F.col("hybrid_indexed_similar_paragraph.score_overlap"),
            F.col("hybrid_indexed_similar_paragraph.score_bm25"),
            F.col("hybrid_indexed_similar_paragraph.vector_similarity"),
            F.col("hybrid_indexed_similar_paragraph.rrf_k"),
            F.col("hybrid_indexed_similar_paragraph.rrf_score"),
            F.col("hybrid_indexed_similar_paragraph.vector_backend"),
            F.col("hybrid_indexed_similar_paragraph.vector_model_id"),
            F.col("hybrid_indexed_similar_paragraph.vector_dimension"),
            F.col("hybrid_indexed_similar_paragraph.vector_content_revision"),
            F.col("hybrid_indexed_similar_paragraph.experiment_id"),
            F.col("hybrid_indexed_similar_paragraph.rank"),
        )
        return {
            "reranked__similar_paragraphs": reranked__similar_paragraphs,
        }


class SearchSimilarityParagraphsGenerated(
    AdoptLexicalParagraphsGenerated,
    AdoptVectorParagraphsGenerated,
    FuseSimilarityParagraphsGenerated,
    RerankSimilarityParagraphsGenerated,
):

    def __init__(self, *, spark: SparkSession, ctx=None):
        self.spark = spark
        self.ctx = ctx

    def close(self) -> None:
        close_plan_boundaries(self.spark)

    def run(
        self,
        *,
        paragraph_similarities: DataFrame,
        paragraph_vector_candidates: DataFrame,
        policy: DataFrame,
        query: DataFrame,
        paragraphs: DataFrame,
    ) -> TransformResult:
        assert_schema(paragraph_similarities, PARAGRAPH_SIMILARITY_SCHEMA, name="ParagraphSimilarity", mode="strict")
        assert_schema(
            paragraph_vector_candidates,
            PARAGRAPH_VECTOR_CANDIDATE_SCHEMA,
            name="ParagraphVectorCandidate",
            mode="strict",
        )
        assert_schema(policy, SIMILARITY_FUSION_POLICY_SCHEMA, name="SimilarityFusionPolicy", mode="strict")
        assert_schema(query, PARAGRAPH_SCHEMA, name="Paragraph", mode="strict")
        assert_schema(paragraphs, PARAGRAPH_SCHEMA, name="Paragraph", mode="strict")
        _input_paragraph_similarities = paragraph_similarities
        _input_paragraph_vector_candidates = paragraph_vector_candidates
        _input_policy = policy
        _input_query = query
        _input_paragraphs = paragraphs
        frames = {
            "paragraph_similarities": paragraph_similarities,
            "paragraph_vector_candidates": paragraph_vector_candidates,
            "policy": policy,
            "query": query,
            "paragraphs": paragraphs,
            "input:paragraph_similarities": _input_paragraph_similarities,
            "input:paragraph_vector_candidates": _input_paragraph_vector_candidates,
            "input:policy": _input_policy,
            "input:query": _input_query,
            "input:paragraphs": _input_paragraphs,
        }
        frames.update(self._step_lexical_adopt_paragraphs_0(frames))
        frames.update(self._step_vector_adopt_paragraphs_1(frames))
        frames.update(self._step_fused_validate_policy_2(frames))
        frames.update(self._step_fused_merge_paragraphs_3(frames))
        frames.update(self._step_fused_fuse_paragraphs_4(frames))
        frames.update(self._step_fused_score_paragraphs_5(frames))
        frames.update(self._step_fused_publish_paragraphs_6(frames))
        frames.update(self._step_reranked_rank_paragraphs_7(frames))
        frames.update(self._step_reranked_limit_paragraphs_8(frames))

        # Step method: similar_paragraphs
        similar_paragraphs = frames["reranked__similar_paragraphs"].alias("hybrid_indexed_similar_paragraph")
        assert_schema(
            similar_paragraphs,
            HYBRID_INDEXED_SIMILAR_PARAGRAPH_SCHEMA,
            name="HybridIndexedSimilarParagraph",
            mode="strict",
        )
        return TransformResult(
            {"similar_paragraphs": similar_paragraphs},
            single=True,
            schema={"similar_paragraphs": HYBRID_INDEXED_SIMILAR_PARAGRAPH_SCHEMA},
        )
