from __future__ import annotations

from collections.abc import Mapping, Sequence
from pathlib import Path

from structure.plugin.pyspark.files.model import GeneratedFileChange, GeneratedFileSetResult


class CompareGeneratedFiles:

    def __call__(
        self,
        files: Mapping[str, str],
        *,
        root: Path | str,
        ignore_prefixes: Sequence[str] = (),
    ) -> GeneratedFileSetResult:
        root_path = Path(root)
        changes = [self._change(path, text, root=root_path) for path, text in sorted(files.items())]
        changes.extend(self._removed(files, root=root_path, ignore_prefixes=ignore_prefixes))
        return GeneratedFileSetResult(tuple(changes))

    def _change(self, path: str, text: str, *, root: Path) -> GeneratedFileChange:
        target = root / Path(path)
        if not target.exists():
            return GeneratedFileChange(path, "added")
        if target.read_text(encoding="utf-8") != text:
            return GeneratedFileChange(path, "modified")
        return GeneratedFileChange(path, "unchanged")

    def _removed(
        self,
        files: Mapping[str, str],
        *,
        root: Path,
        ignore_prefixes: Sequence[str],
    ) -> list[GeneratedFileChange]:
        expected = {Path(path).as_posix() for path in files}
        if not root.exists():
            return []
        return [
            GeneratedFileChange(relative, "removed")
            for target in sorted(path for path in root.rglob("*") if path.is_file())
            if (relative := target.relative_to(root).as_posix()) not in expected
            and not any(relative.startswith(prefix) for prefix in ignore_prefixes)
            and self._owned(target)
        ]

    def _owned(self, target: Path) -> bool:
        try:
            text = target.read_text(encoding="utf-8")
        except UnicodeDecodeError:
            return False
        return text.startswith("# Generated by Structure. Do not edit by hand.") or (
            target.suffix == ".json"
            and (
                '"generated_by": "Structure"' in text
                or '"source_transform"' in text and '"generated_transform_class"' in text
            )
        )


compare_generated_files = CompareGeneratedFiles()
