# Generated by Structure. Do not edit by hand.
# Source: examples.search.transforms.similarities.SimilarSections.SimilarSections

from __future__ import annotations
from pyspark.sql import DataFrame, SparkSession
from pyspark.sql import functions as F
from pyspark.sql import types as T
from examples.structure_generated.search.runtime.schema_assert import (
    TransformResult,
    assert_schema,
    project_schema,
    apply_plan_boundary,
    close_plan_boundaries,
)
from examples.structure_generated.search.pyspark.schemas.similarity import (
    INDEXED_SIMILAR_SECTION_SCHEMA,
    SECTION_SIMILARITY_SCHEMA,
    SIMILARITY_SECTION_QUERY_SCHEMA,
)
from examples.structure_generated.search.pyspark.schemas.text import SECTION_SCHEMA


class SimilarSectionsGenerated:

    def __init__(self, *, spark: SparkSession, ctx=None):
        self.spark = spark
        self.ctx = ctx

    def close(self) -> None:
        close_plan_boundaries(self.spark)

    def run(
        self,
        *,
        query: DataFrame,
        sections: DataFrame,
        section_similarities: DataFrame,
    ) -> TransformResult:
        assert_schema(query, SIMILARITY_SECTION_QUERY_SCHEMA, name="SimilaritySectionQuery", mode="strict")
        assert_schema(sections, SECTION_SCHEMA, name="Section", mode="strict")
        assert_schema(section_similarities, SECTION_SIMILARITY_SCHEMA, name="SectionSimilarity", mode="strict")
        _input_query = query
        _input_sections = sections
        _input_section_similarities = section_similarities

        # Step method: rank
        query = query.alias("similarity_section_query")
        section_similarities_joined = section_similarities.alias("section_similarities")
        query = query.join(
            section_similarities_joined,
            (F.col("similarity_section_query.id") == F.col("section_similarities.left_section_id")),
            "inner",
        )
        sections_2_joined = sections.alias("sections_2")
        query = query.join(
            sections_2_joined,
            (F.col("sections_2.id") == F.col("section_similarities.right_section_id")),
            "inner",
        )
        query = query.select(
            F.col("sections_2.id"),
            F.col("sections_2.document_id"),
            F.col("sections_2.ordinal"),
            F.col("sections_2.heading"),
            F.col("similarity_section_query.id").alias("search_query_id"),
            F.col("section_similarities.score_overlap"),
            F.col("section_similarities.bm25_left_to_right").alias("score_bm25"),
            F.col("section_similarities.rank"),
        )
        assert_schema(query, INDEXED_SIMILAR_SECTION_SCHEMA, name="IndexedSimilarSection", mode="strict")

        # Step method: limit
        query = query.alias("indexed_similar_section")
        query = query.where(((F.col("indexed_similar_section.rank") <= F.lit(10))))
        query = query.select(
            F.col("indexed_similar_section.id"),
            F.col("indexed_similar_section.document_id"),
            F.col("indexed_similar_section.ordinal"),
            F.col("indexed_similar_section.heading"),
            F.col("indexed_similar_section.search_query_id"),
            F.col("indexed_similar_section.score_overlap"),
            F.col("indexed_similar_section.score_bm25"),
            F.col("indexed_similar_section.rank"),
        )

        # Step method: similar_sections
        similar_sections = query.alias("indexed_similar_section")
        assert_schema(similar_sections, INDEXED_SIMILAR_SECTION_SCHEMA, name="IndexedSimilarSection", mode="strict")
        return TransformResult(
            {"similar_sections": similar_sections},
            single=True,
            schema={"similar_sections": INDEXED_SIMILAR_SECTION_SCHEMA},
        )
