# Generated by Structure. Do not edit by hand.
# Source: examples.orders.transforms.order.EnrichOrders

from pyspark.sql import DataFrame, SparkSession
from pyspark.sql import functions as F
from pyspark.sql import types as T
from examples.orders.transforms.order import EnrichOrders
from examples.structure_generated.orders.runtime.schema_assert import TransformResult, assert_schema, project_schema, HookInputs
from examples.structure_generated.orders.pyspark.schemas.customer import CUSTOMER_SCHEMA
from examples.structure_generated.orders.pyspark.schemas.order import ORDER_NORMALIZED_SCHEMA, ORDER_PUBLISHED_SCHEMA, ORDER_RAW_SCHEMA, ORDER_WITH_CUSTOMER_SCHEMA, ORDER_WITH_PRODUCT_SCHEMA, ORDER_WITH_PROMOTION_SCHEMA
from examples.structure_generated.orders.pyspark.schemas.product import BLOCKED_PRODUCT_SCHEMA, PRODUCT_SCHEMA
from examples.structure_generated.orders.pyspark.schemas.promotion import PROMOTION_SCHEMA


class EnrichOrdersGenerated:

    def __init__(self, *, spark: SparkSession, ctx=None):
        self.spark = spark
        self.ctx = ctx
        self._impl = EnrichOrders()

    def run(
        self,
        *,
        orders: DataFrame,
        customers: DataFrame,
        products: DataFrame,
        blocked_products: DataFrame,
        promotions: DataFrame,
    ) -> TransformResult:
        assert_schema(orders, ORDER_RAW_SCHEMA, name="OrderRaw", mode="strict")
        assert_schema(customers, CUSTOMER_SCHEMA, name="Customer", mode="strict")
        assert_schema(products, PRODUCT_SCHEMA, name="Product", mode="strict")
        assert_schema(blocked_products, BLOCKED_PRODUCT_SCHEMA, name="BlockedProduct", mode="strict")
        assert_schema(promotions, PROMOTION_SCHEMA, name="Promotion", mode="strict")
        inputs = HookInputs(
            orders=orders,
            customers=customers,
            products=products,
            blocked_products=blocked_products,
            promotions=promotions,
        )
        _input_orders = orders
        _input_customers = customers
        _input_products = products
        _input_blocked_products = blocked_products
        _input_promotions = promotions

        # Subtransform: normalize
        orders = self._impl.use_current_orders(orders=orders, inputs=inputs, spark=self.spark, ctx=self.ctx)
        orders = orders.alias("order_raw")
        orders = orders.where((F.col("order_raw.id").isNotNull()) & (F.col("order_raw.customer_id").isNotNull()) & (F.col("order_raw.product_id").isNotNull()))
        orders = orders.select(
            F.col("order_raw.tenant"),
            F.col("order_raw.audit"),
            F.col("order_raw.business"),
            F.lower(F.trim(F.col("order_raw.id"))).alias("id"),
            F.lower(F.trim(F.col("order_raw.customer_id"))).alias("customer_id"),
            F.lower(F.trim(F.col("order_raw.product_id"))).alias("product_id"),
            F.lower(F.trim(F.col("order_raw.promo-code"))).alias("promotion_code"),
            F.coalesce(F.col("order_raw.total").cast("decimal(12,2)"), F.lit(0)).alias("total"),
            F.coalesce(F.col("order_raw.discount").cast("decimal(12,2)"), F.lit(0)).alias("discount"),
            (F.coalesce(F.col("order_raw.total").cast("decimal(12,2)"), F.lit(0)) - F.coalesce(F.col("order_raw.discount").cast("decimal(12,2)"), F.lit(0))).cast(T.DecimalType(12, 2)).alias("net_total"),
            F.coalesce(F.col("order_raw.quantity"), F.lit(1)).cast(T.LongType()).alias("quantity"),
            F.col("order_raw.tags"),
            F.col("order_raw.attributes"),
            F.col("order_raw.shipping"),
            (F.coalesce(F.col("order_raw.total").cast("decimal(12,2)"), F.lit(0)) > F.lit(1000)).alias("is_large"),
        )
        orders = self._impl.remove_negative_totals(orders=orders, spark=self.spark, ctx=self.ctx)
        assert_schema(orders, ORDER_NORMALIZED_SCHEMA, name="OrderNormalized", mode="strict")
        assert_schema(orders, ORDER_NORMALIZED_SCHEMA, name="OrderNormalized", mode="strict")

        # Subtransform: add_customer
        orders = orders.alias("order_normalized")
        customers_joined = F.broadcast(customers.alias("customers"))
        orders = orders.join(
            customers_joined,
            ((F.col("customers.tenant.tenant_id") == F.col("order_normalized.tenant.tenant_id")) & (F.lower(F.trim(F.col("customers.id"))) == F.col("order_normalized.customer_id"))),
            "left",
        )
        orders = orders.select(
            F.col("order_normalized.tenant"),
            F.col("order_normalized.audit"),
            F.col("order_normalized.business"),
            F.col("order_normalized.id"),
            F.col("order_normalized.customer_id"),
            F.col("order_normalized.product_id"),
            F.col("order_normalized.promotion_code"),
            F.col("order_normalized.total"),
            F.col("order_normalized.discount"),
            F.col("order_normalized.net_total"),
            F.col("order_normalized.quantity"),
            F.col("order_normalized.tags"),
            F.col("order_normalized.attributes"),
            F.col("order_normalized.shipping"),
            F.col("order_normalized.is_large"),
            F.col("customers.name").alias("customer_name"),
            F.col("customers.tier").alias("customer_tier"),
            F.col("customers.region").alias("customer_region"),
        )
        assert_schema(orders, ORDER_WITH_CUSTOMER_SCHEMA, name="OrderWithCustomer", mode="strict")

        # Subtransform: add_product
        orders = orders.alias("order_with_customer")
        products_joined = products.alias("products")
        orders = orders.join(
            products_joined,
            ((F.col("products.tenant.tenant_id") == F.col("order_with_customer.tenant.tenant_id")) & (F.col("products.id") == F.col("order_with_customer.product_id"))),
            "left_semi",
        )
        blocked_products_2_joined = blocked_products.alias("blocked_products_2")
        orders = orders.join(
            blocked_products_2_joined,
            ((F.col("blocked_products_2.tenant.tenant_id") == F.col("order_with_customer.tenant.tenant_id")) & (F.col("blocked_products_2.product_id") == F.col("order_with_customer.product_id"))),
            "left_anti",
        )
        products_3_joined = products.alias("products_3")
        orders = orders.join(
            products_3_joined,
            ((F.col("products_3.tenant.tenant_id") == F.col("order_with_customer.tenant.tenant_id")) & (F.col("products_3.id") == F.col("order_with_customer.product_id"))),
            "left",
        )
        orders = orders.where((F.col("products_3.id").isNotNull()))
        orders = orders.select(
            F.col("order_with_customer.tenant"),
            F.col("order_with_customer.audit"),
            F.col("order_with_customer.business"),
            F.col("order_with_customer.id"),
            F.col("order_with_customer.customer_id"),
            F.col("order_with_customer.product_id"),
            F.col("order_with_customer.promotion_code"),
            F.col("order_with_customer.total"),
            F.col("order_with_customer.discount"),
            F.col("order_with_customer.net_total"),
            F.col("order_with_customer.quantity"),
            F.col("order_with_customer.tags"),
            F.col("order_with_customer.attributes"),
            F.col("order_with_customer.shipping"),
            F.col("order_with_customer.is_large"),
            F.col("order_with_customer.customer_name"),
            F.col("order_with_customer.customer_tier"),
            F.col("order_with_customer.customer_region"),
            F.col("products_3.name").alias("product_name"),
            F.col("products_3.category").alias("product_category"),
            F.col("products_3.active").alias("product_active"),
            F.col("products_3.list_price").alias("product_list_price"),
        )
        assert_schema(orders, ORDER_WITH_PRODUCT_SCHEMA, name="OrderWithProduct", mode="strict")

        # Subtransform: add_promotion
        orders = orders.alias("order_with_product")
        promotions_joined = promotions.alias("promotions")
        orders = orders.join(
            promotions_joined,
            ((F.col("promotions.tenant.tenant_id") == F.col("order_with_product.tenant.tenant_id")) & F.lower(F.trim(F.col("promotions.code"))).eqNullSafe(F.col("order_with_product.promotion_code"))),
            "left",
        )
        orders = orders.select(
            F.col("order_with_product.tenant"),
            F.col("order_with_product.audit"),
            F.col("order_with_product.business"),
            F.col("order_with_product.id"),
            F.col("order_with_product.customer_id"),
            F.col("order_with_product.product_id"),
            F.col("order_with_product.promotion_code"),
            F.col("order_with_product.total"),
            F.col("order_with_product.discount"),
            F.col("order_with_product.net_total"),
            F.col("order_with_product.quantity"),
            F.col("order_with_product.tags"),
            F.col("order_with_product.attributes"),
            F.col("order_with_product.shipping"),
            F.col("order_with_product.is_large"),
            F.col("order_with_product.customer_name"),
            F.col("order_with_product.customer_tier"),
            F.col("order_with_product.customer_region"),
            F.col("order_with_product.product_name"),
            F.col("order_with_product.product_category"),
            F.col("order_with_product.product_active"),
            F.col("order_with_product.product_list_price"),
            F.col("promotions.name").alias("promotion_name"),
            F.col("promotions.discount").alias("promotion_discount"),
        )
        orders = self._impl.note_lookup_inputs(orders=orders, inputs=inputs, spark=self.spark, ctx=self.ctx)
        assert_schema(orders, ORDER_WITH_PROMOTION_SCHEMA, name="OrderWithPromotion", mode="allow_extra_columns")
        orders = project_schema(orders, ORDER_WITH_PROMOTION_SCHEMA)
        assert_schema(orders, ORDER_WITH_PROMOTION_SCHEMA, name="OrderWithPromotion", mode="strict")
        assert_schema(orders, ORDER_WITH_PROMOTION_SCHEMA, name="OrderWithPromotion", mode="strict")

        # Subtransform: publish
        published = orders.alias("order_with_promotion")
        published = published.select(
            F.col("order_with_promotion.tenant"),
            F.col("order_with_promotion.business"),
            F.col("order_with_promotion.id"),
            F.col("order_with_promotion.customer_id"),
            F.col("order_with_promotion.customer_name"),
            F.col("order_with_promotion.customer_tier"),
            F.col("order_with_promotion.product_name"),
            F.col("order_with_promotion.product_category"),
            F.col("order_with_promotion.promotion_name"),
            F.col("order_with_promotion.total"),
            F.col("order_with_promotion.discount"),
            F.col("order_with_promotion.net_total"),
            F.col("order_with_promotion.quantity"),
            F.col("order_with_promotion.is_large"),
            F.col("order_with_promotion.promotion_name").isNotNull().alias("has_promotion"),
        )
        published = self._impl.add_quality_columns(published=published, spark=self.spark, ctx=self.ctx)
        assert_schema(published, ORDER_PUBLISHED_SCHEMA, name="OrderPublished", mode="allow_extra_columns")
        published = project_schema(published, ORDER_PUBLISHED_SCHEMA)
        assert_schema(published, ORDER_PUBLISHED_SCHEMA, name="OrderPublished", mode="strict")

        # Subtransform: published
        published = published.alias("order_published")
        assert_schema(published, ORDER_PUBLISHED_SCHEMA, name="OrderPublished", mode="strict")
        return TransformResult({"published": published}, single=True, schema={"published": ORDER_PUBLISHED_SCHEMA})
