# Generated by Structure. Do not edit by hand.
# Source: examples.store.transforms.fulfillment.reconciliation.reconcile.ReconcileFulfillmentPlan

from __future__ import annotations
from pyspark.sql import DataFrame, SparkSession
from pyspark.sql import functions as F
from pyspark.sql import types as T
from examples.structure_generated.store.runtime.schema_assert import (
    TransformResult,
    assert_schema,
    project_schema,
    apply_plan_boundary,
    close_plan_boundaries,
)
from examples.structure_generated.store.pyspark.schemas.common import BUSINESS_DATE_SCHEMA, TENANT_KEY_SCHEMA
from examples.structure_generated.store.pyspark.schemas.order import ORDER_FULFILLMENT_SCHEMA
from examples.structure_generated.store.pyspark.schemas.plan import FULFILLMENT_PLAN_SCHEMA
from examples.structure_generated.store.pyspark.schemas.reconciliation import FULFILLMENT_RECONCILIATION_SCHEMA


class ReconcileFulfillmentPlanGenerated:

    def __init__(self, *, spark: SparkSession, ctx=None):
        self.spark = spark
        self.ctx = ctx

    def close(self) -> None:
        close_plan_boundaries(self.spark)

    def run(
        self,
        *,
        plans: DataFrame,
        fulfilled: DataFrame,
    ) -> TransformResult:
        assert_schema(plans, FULFILLMENT_PLAN_SCHEMA, name="FulfillmentPlan", mode="strict")
        assert_schema(fulfilled, ORDER_FULFILLMENT_SCHEMA, name="OrderFulfillment", mode="strict")
        _input_plans = plans
        _input_fulfilled = fulfilled

        # Step method: reconcile
        reconciliation = plans.alias("fulfillment_plan")
        fulfilled_joined = fulfilled.alias("fulfilled")
        reconciliation = reconciliation.join(
            fulfilled_joined,
            (
                (
                    (F.col("fulfilled.tenant.tenant_id") == F.col("fulfillment_plan.tenant.tenant_id"))
                    & (F.col("fulfilled.id") == F.col("fulfillment_plan.order_id"))
                )
                & (F.col("fulfilled.line_number") == F.col("fulfillment_plan.line_number"))
            ),
            "left",
        )
        reconciliation = (
            reconciliation.groupBy(
                F.col("fulfillment_plan.tenant.tenant_id").alias("tenant_id"),
                F.col("fulfillment_plan.order_id").alias("order_id"),
                F.col("fulfillment_plan.line_number").alias("line_number"),
                F.col("fulfillment_plan.product_id").alias("product_id"),
                F.col("fulfillment_plan.business").alias("business"),
                F.col("fulfillment_plan.plan_status").alias("planned_status"),
                F.col("fulfillment_plan.allocated_quantity").alias("allocated_quantity"),
                F.col("fulfillment_plan.backordered_quantity").alias("backordered_quantity"),
            )
            .agg(
                F.first(F.col("fulfillment_plan.tenant"), ignorenulls=False).alias("tenant"),
                F.sum(F.coalesce(F.col("fulfilled.quantity"), F.lit(0))).cast(T.LongType()).alias("shipped_quantity"),
                F.bool_or(F.col("fulfilled.id").isNotNull()).cast(T.BooleanType()).alias("shipped"),
                F.min(
                    F.when(F.col("fulfilled.id").isNotNull(), F.lit('planned_line_shipped')).otherwise(
                        F.lit('planned_line_not_shipped')
                    )
                )
                .cast(T.StringType())
                .alias("reconciliation_status"),
            )
            .select(
                F.col("tenant"),
                F.col("business"),
                F.col("order_id"),
                F.col("line_number"),
                F.col("product_id"),
                F.col("planned_status"),
                F.col("allocated_quantity").alias("planned_allocated_quantity"),
                F.col("backordered_quantity").alias("planned_backordered_quantity"),
                F.col("shipped_quantity"),
                F.col("shipped"),
                F.col("reconciliation_status"),
            )
        )

        # Step method: reconciliation
        reconciliation = reconciliation.alias("fulfillment_reconciliation")
        assert_schema(
            reconciliation, FULFILLMENT_RECONCILIATION_SCHEMA, name="FulfillmentReconciliation", mode="strict"
        )
        return TransformResult(
            {"reconciliation": reconciliation},
            single=True,
            schema={"reconciliation": FULFILLMENT_RECONCILIATION_SCHEMA},
        )
