# Generated by Structure. Do not edit by hand.
# Source: testing.model.v2.orders.schemas.order

from pyspark.sql import types as T
from testing.model.v2.structure_generated.orders.pyspark.schemas.common import ADDRESS_SCHEMA, AUDIT_STAMP_SCHEMA, BUSINESS_DATE_SCHEMA, TENANT_KEY_SCHEMA


ORDER_RAW_SCHEMA = T.StructType([
    T.StructField("tenant", TENANT_KEY_SCHEMA, False),
    T.StructField("audit", AUDIT_STAMP_SCHEMA, False),
    T.StructField("business", BUSINESS_DATE_SCHEMA, False),
    T.StructField("id", T.StringType(), False),
    T.StructField("customer_id", T.StringType(), False),
    T.StructField("product_id", T.StringType(), False),
    T.StructField("promo-code", T.StringType(), True),
    T.StructField("total", T.StringType(), True),
    T.StructField("discount", T.StringType(), True),
    T.StructField("quantity", T.IntegerType(), True),
    T.StructField("tags", T.ArrayType(T.StringType(), containsNull=False), True),
    T.StructField("attributes", T.MapType(T.StringType(), T.StringType(), valueContainsNull=True), True),
    T.StructField("shipping", ADDRESS_SCHEMA, True),
])

ORDER_CUSTOMER_RECONCILIATION_SCHEMA = T.StructType([
    T.StructField("tenant_id", T.StringType(), True),
    T.StructField("order_id", T.StringType(), True),
    T.StructField("order_customer_id", T.StringType(), True),
    T.StructField("customer_id", T.StringType(), True),
    T.StructField("customer_name", T.StringType(), True),
    T.StructField("match_status", T.StringType(), True),
])

CUSTOMER_ORDER_BACKFILL_SCHEMA = T.StructType([
    T.StructField("tenant_id", T.StringType(), True),
    T.StructField("order_id", T.StringType(), True),
    T.StructField("order_customer_id", T.StringType(), True),
    T.StructField("customer_id", T.StringType(), True),
    T.StructField("customer_name", T.StringType(), True),
    T.StructField("customer_region", T.StringType(), True),
])

ORDER_PRODUCT_CANDIDATE_SCHEMA = T.StructType([
    T.StructField("tenant_id", T.StringType(), True),
    T.StructField("order_id", T.StringType(), True),
    T.StructField("customer_id", T.StringType(), True),
    T.StructField("customer_name", T.StringType(), True),
    T.StructField("product_id", T.StringType(), True),
    T.StructField("product_name", T.StringType(), True),
])
