# Generated by Structure. Do not edit by hand.
# Source: examples.search.transforms.stats.ProfileDocuments.ProfileDocuments

from __future__ import annotations
from pyspark.sql import DataFrame, SparkSession
from pyspark.sql import Window
from pyspark.sql import functions as F
from pyspark.sql import types as T
from examples.structure_generated.search.runtime.schema_assert import (
    TransformResult,
    assert_schema,
    project_schema,
    apply_plan_boundary,
    close_plan_boundaries,
)
from examples.structure_generated.search.pyspark.schemas.analytics import DOCUMENT_PROFILE_SCHEMA
from examples.structure_generated.search.pyspark.schemas.text import DOCUMENT_SCHEMA


class ProfileDocumentsGenerated:

    def __init__(self, *, spark: SparkSession, ctx=None):
        self.spark = spark
        self.ctx = ctx

    def close(self) -> None:
        close_plan_boundaries(self.spark)

    def run(
        self,
        *,
        documents: DataFrame,
    ) -> TransformResult:
        assert_schema(documents, DOCUMENT_SCHEMA, name="Document", mode="strict")
        _input_documents = documents

        # Step method: profile
        documents = documents.alias("document")
        documents = documents.select(
            F.col("document.id").alias("document_id"),
            F.col("document.collection_id"),
            F.col("document.source"),
            F.col("document.language"),
            F.col("document.title"),
            F.col("document.url"),
            F.nullif(F.trim(F.col("document.title")), F.lit('Untitled')).alias("normalized_title"),
            F.lower(F.regexp_replace(F.trim(F.col("document.content")), '\\s+', ' ')).alias("normalized_content"),
            F.col("document.title").startswith('The ').alias("title_starts_with_the"),
            F.col("document.title").endswith('Guide').alias("title_ends_with_guide"),
            F.col("document.url").startswith('https://').alias("url_is_https"),
            F.col("document.content").contains('Structure').alias("content_contains_structure"),
            F.col("document.content").like('%guide%').alias("content_like_guide"),
            F.col("document.content").ilike('%STRUCTURE%').alias("content_ilike_structure"),
            F.col("document.content").rlike('.*[.!?].*').alias("content_matches_sentence"),
            F.substring(F.col("document.title"), 1, 12).alias("title_prefix"),
            F.split(F.col("document.title"), '\\s+', -1).alias("title_words"),
            F.slice(F.split(F.col("document.title"), '\\s+', -1), 1, 2).alias("leading_title_words"),
            F.array_sort(F.split(F.col("document.title"), '\\s+', -1)).alias("sorted_title_words"),
            F.regexp_replace(F.col("document.title"), '\\s+', '-').alias("title_slug"),
            F.regexp_extract(F.col("document.title"), '([0-9]+)', 1).alias("first_number"),
            F.length(F.col("document.content")).alias("content_length"),
            F.initcap(F.ltrim(F.rtrim(F.col("document.title")))).alias("title_case"),
            F.reverse(F.col("document.title")).alias("reversed_title"),
            F.translate(F.col("document.title"), '_', '-').alias("translated_title"),
            F.instr(F.col("document.content"), 'Structure').alias("structure_position"),
            F.levenshtein(F.col("document.title"), F.lit('Structure Guide')).alias("title_distance_to_guide"),
            F.concat_ws(' · ', F.col("document.source"), F.col("document.title"), F.col("document.url")).alias(
                "display_name"
            ),
            F.hash(F.col("document.title"), F.col("document.source")).alias("title_hash"),
            F.sha2(F.col("document.content"), 256).alias("content_sha2"),
            F.year(F.col("document.harvested_at")).alias("harvest_year"),
            F.datediff(F.col("document.harvested_at"), F.col("document.created_at")).alias("age_days"),
            F.sqrt(F.length(F.col("document.content"))).alias("content_length_sqrt"),
            F.log((F.length(F.col("document.content")) + F.lit(1))).alias("content_length_log"),
            F.bround(F.length(F.col("document.content")), 0).cast(T.DoubleType()).alias("rounded_content_length"),
            F.signum(F.length(F.col("document.content"))).alias("content_length_sign"),
            F.row_number()
            .over(
                Window.partitionBy(F.col("document.source")).orderBy(
                    F.col("document.harvested_at").desc_nulls_last(), F.col("document.id").asc_nulls_first()
                )
            )
            .cast(T.LongType())
            .alias("source_recency_rank"),
        )

        # Step method: features
        features = documents.alias("document_profile")
        assert_schema(features, DOCUMENT_PROFILE_SCHEMA, name="DocumentProfile", mode="strict")
        return TransformResult({"features": features}, single=True, schema={"features": DOCUMENT_PROFILE_SCHEMA})
