# Generated by Structure. Do not edit by hand.
# Source: examples.search.transforms.features.Features.Features

from __future__ import annotations
from pyspark.sql import DataFrame, SparkSession
from pyspark.sql import functions as F
from pyspark.sql import types as T
from examples.structure_generated.search.runtime.schema_assert import (
    TransformResult,
    assert_schema,
    project_schema,
    apply_plan_boundary,
    close_plan_boundaries,
)
from examples.structure_generated.search.pyspark.schemas.features import DOCUMENT_FEATURES_SCHEMA, QUERY_FEATURES_SCHEMA
from examples.structure_generated.search.pyspark.schemas.features_intermediate import (
    EXPANDED_QUERY_FEATURE_TOKEN_SCHEMA,
    QUERY_FEATURE_TOKEN_SCHEMA,
    QUERY_TOKEN_SUMMARY_SCHEMA,
)
from examples.structure_generated.search.pyspark.schemas.search import SEARCH_QUERY_SCHEMA
from examples.structure_generated.search.pyspark.schemas.text import DOCUMENT_SCHEMA


class BuildDocumentFeaturesGenerated:
    def _step_documents_built_build_0(self, frames):
        # Step method: documents_built.build
        documents_built__document_features = frames["documents"].alias("document")
        documents_built__document_features = documents_built__document_features.select(
            F.col("document.id").alias("document_id"),
            F.col("document.collection_id"),
            F.col("document.source"),
            F.col("document.language"),
            F.lower(F.trim(F.col("document.title"))).alias("normalized_title"),
            F.lower(F.regexp_replace(F.trim(F.col("document.content")), '\\s+', ' ')).alias("normalized_content"),
            F.length(F.col("document.title")).alias("title_length"),
            F.length(F.col("document.content")).alias("content_length"),
            F.col("document.url").startswith('https://').alias("url_is_https"),
        )
        assert_schema(
            documents_built__document_features, DOCUMENT_FEATURES_SCHEMA, name="DocumentFeatures", mode="strict"
        )
        return {
            "documents_built__document_features": documents_built__document_features,
        }


class BuildQueryFeaturesGenerated:
    def _step_queries_built_expand_tokens_1(self, frames):
        # Step method: queries_built.expand_tokens
        queries_built__expanded_query_tokens = frames["queries"].alias("search_query")
        queries_built__expanded_query_tokens = queries_built__expanded_query_tokens.select(
            "*",
            F.posexplode(
                F.transform(
                    F.split(F.trim(F.col("search_query.content")), '\\s+', -1),
                    lambda item: F.struct(
                        F.col("search_query.id").alias("query_id"),
                        F.lower(F.regexp_replace(F.trim(item), '^[^A-Za-z0-9]+|[^A-Za-z0-9]+$', '')).alias("token"),
                    ),
                )
            ).alias("__structure_query_feature_token_1_pos", "__structure_query_feature_token_1_item"),
        )
        queries_built__expanded_query_tokens = queries_built__expanded_query_tokens.withColumn(
            "ordinal",
            F.col("__structure_query_feature_token_1_pos").cast(T.LongType()),
        )
        queries_built__expanded_query_tokens = queries_built__expanded_query_tokens.withColumn(
            "query_id",
            F.col("__structure_query_feature_token_1_item.query_id"),
        )
        queries_built__expanded_query_tokens = queries_built__expanded_query_tokens.withColumn(
            "token",
            F.col("__structure_query_feature_token_1_item.token"),
        )
        queries_built__expanded_query_tokens = queries_built__expanded_query_tokens.drop(
            "__structure_query_feature_token_1_pos", "__structure_query_feature_token_1_item"
        )
        queries_built__expanded_query_tokens = queries_built__expanded_query_tokens.where(
            ((F.col("token") != F.lit('')))
        )
        queries_built__expanded_query_tokens = queries_built__expanded_query_tokens.select(
            F.col("query_id"),
            F.col("token"),
            F.col("ordinal"),
        )
        assert_schema(
            queries_built__expanded_query_tokens,
            EXPANDED_QUERY_FEATURE_TOKEN_SCHEMA,
            name="ExpandedQueryFeatureToken",
            mode="strict",
        )
        return {
            "queries_built__expanded_query_tokens": queries_built__expanded_query_tokens,
        }

    def _step_queries_built_select_tokens_2(self, frames):
        # Step method: queries_built.select_tokens
        queries_built__query_tokens = frames["queries_built__expanded_query_tokens"].alias(
            "expanded_query_feature_token"
        )
        queries_built__query_tokens = queries_built__query_tokens.select(
            F.col("expanded_query_feature_token.query_id"),
            F.col("expanded_query_feature_token.token"),
        )
        assert_schema(queries_built__query_tokens, QUERY_FEATURE_TOKEN_SCHEMA, name="QueryFeatureToken", mode="strict")
        return {
            "queries_built__query_tokens": queries_built__query_tokens,
        }

    def _step_queries_built_summarize_3(self, frames):
        # Step method: queries_built.summarize
        queries_built__query_token_summaries = frames["queries_built__query_tokens"].alias("query_feature_token")
        queries_built__query_token_summaries = (
            queries_built__query_token_summaries.groupBy(
                F.col("query_feature_token.query_id").alias("query_id"),
            )
            .agg(
                F.count(F.lit(1)).cast(T.LongType()).alias("token_count"),
                F.countDistinct(F.col("query_feature_token.token")).cast(T.LongType()).alias("distinct_token_count"),
            )
            .select(
                F.col("query_id"),
                F.col("token_count"),
                F.col("distinct_token_count"),
            )
        )
        assert_schema(
            queries_built__query_token_summaries, QUERY_TOKEN_SUMMARY_SCHEMA, name="QueryTokenSummary", mode="strict"
        )
        return {
            "queries_built__query_token_summaries": queries_built__query_token_summaries,
        }

    def _step_queries_built_build_4(self, frames):
        # Step method: queries_built.build
        queries_built__query_features = frames["queries"].alias("search_query")
        queries_built__query_token_summaries_joined = frames["queries_built__query_token_summaries"].alias(
            "queries_built__query_token_summaries"
        )
        queries_built__query_features = queries_built__query_features.join(
            queries_built__query_token_summaries_joined,
            (F.col("queries_built__query_token_summaries.query_id") == F.col("search_query.id")),
            "left",
        )
        queries_built__query_features = queries_built__query_features.select(
            F.col("search_query.id").alias("query_id"),
            F.col("search_query.queryset"),
            F.col("search_query.language"),
            F.lower(F.regexp_replace(F.trim(F.col("search_query.content")), '\\s+', ' ')).alias("normalized_content"),
            F.coalesce(F.col("queries_built__query_token_summaries.token_count"), F.lit(0)).alias("token_count"),
            F.coalesce(F.col("queries_built__query_token_summaries.distinct_token_count"), F.lit(0)).alias(
                "distinct_token_count"
            ),
            F.col("search_query.is_question"),
            F.col("search_query.is_time_sensitive"),
        )
        return {
            "queries_built__query_features": queries_built__query_features,
        }


class FeaturesGenerated(BuildDocumentFeaturesGenerated, BuildQueryFeaturesGenerated):

    def __init__(self, *, spark: SparkSession, ctx=None):
        self.spark = spark
        self.ctx = ctx

    def close(self) -> None:
        close_plan_boundaries(self.spark)

    def run(
        self,
        *,
        documents: DataFrame,
        queries: DataFrame,
    ) -> TransformResult:
        assert_schema(documents, DOCUMENT_SCHEMA, name="Document", mode="strict")
        assert_schema(queries, SEARCH_QUERY_SCHEMA, name="SearchQuery", mode="strict")
        _input_documents = documents
        _input_queries = queries
        frames = {
            "documents": documents,
            "queries": queries,
            "input:documents": _input_documents,
            "input:queries": _input_queries,
        }
        frames.update(self._step_documents_built_build_0(frames))
        frames.update(self._step_queries_built_expand_tokens_1(frames))
        frames.update(self._step_queries_built_select_tokens_2(frames))
        frames.update(self._step_queries_built_summarize_3(frames))
        frames.update(self._step_queries_built_build_4(frames))

        # Step method: document_features
        document_features = frames["documents_built__document_features"].alias("document_features")
        assert_schema(document_features, DOCUMENT_FEATURES_SCHEMA, name="DocumentFeatures", mode="strict")

        # Step method: query_features
        query_features = frames["queries_built__query_features"].alias("query_features")
        assert_schema(query_features, QUERY_FEATURES_SCHEMA, name="QueryFeatures", mode="strict")

        # Step method: _stage_output_0
        _stage_output_0 = frames["documents_built__document_features"].alias("document_features")
        assert_schema(_stage_output_0, DOCUMENT_FEATURES_SCHEMA, name="DocumentFeatures", mode="strict")

        # Step method: _stage_output_1
        _stage_output_1 = frames["queries_built__query_features"].alias("query_features")
        assert_schema(_stage_output_1, QUERY_FEATURES_SCHEMA, name="QueryFeatures", mode="strict")
        return TransformResult(
            {"document_features": document_features, "query_features": query_features},
            single=False,
            schema={"document_features": DOCUMENT_FEATURES_SCHEMA, "query_features": QUERY_FEATURES_SCHEMA},
            stage_records=[
                (('documents_built', 'document_features'), _stage_output_0, DOCUMENT_FEATURES_SCHEMA, ()),
                (('queries_built', 'query_features'), _stage_output_1, QUERY_FEATURES_SCHEMA, ()),
            ],
            stage_outputs_enabled=True,
            stage_names=('documents_built', 'queries_built'),
        )
